In [1]:
import sc2ts
import pandas
import numpy as np
import tszip
import matplotlib.pyplot as plt
import pandas as pd
import collections

from pangonet.pangonet import PangoNet

In [2]:
ts = tszip.load("data/sc2ts_viridian_v1.trees.tsz")
ts

In [3]:
ds = sc2ts.Dataset("data/viridian_mafft_2024-10-14_v1.vcz.zip")
ds

2025-08-06 15:43:53,958 INFO:Loading dataset @data/viridian_mafft_2024-10-14_v1.vcz.zip using None as date field

Dataset at data/viridian_mafft_2024-10-14_v1.vcz.zip with 4484157 samples, 29903 variants, and 30 metadata fields. See ds.metadata.field_descriptors() for a description of the fields.

In [4]:
df_node = sc2ts.node_data(ts).set_index("node_id")
df_node

2025-08-06 15:44:00,206 INFO:Computing inheritance counts

,pango,sample_id,scorpio,is_sample,is_recombinant,num_mutations,max_descendant_samples,date
node_id,,,,,,,,
0,B,Vestigial_ignore,.,False,False,0,0,2019-11-17
1,B,Wuhan/Hu-1/2019,.,False,False,0,2482157,2019-12-26
2,A,SRR11772659,.,True,False,1,255,2020-01-19
3,B,SRR11397727,.,True,False,0,1,2020-01-24
4,B,SRR11397730,.,True,False,0,1,2020-01-24
...,...,...,...,...,...,...,...,...
2689049,AY.103,,Delta (B.1.617.2-like),False,False,1,3,2021-11-11
2689050,BA.2.9,,Omicron (BA.2-like),False,False,3,2,2022-03-04
2689051,AY.4,,Delta (AY.4-like),False,False,1,3,2021-09-01
2689052,AY.44,,Delta (B.1.617.2-like),False,False,1,24,2021-10-15
2689053,B.1.561,,.,False,False,1,44,2020-10-08

In [5]:
df_samples = df_node[df_node.is_sample]

In [6]:
df_samples.date.max()

Timestamp('2023-02-20 00:00:00')

In [7]:
df_recombinants = pd.read_csv("data/recombinants.csv").set_index("recombinant")
df_recombinants

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,num_mutations_k1000,num_mutations_k4,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4
recombinant,,,,,,,,,,,,,,,,,,,,,
1530,ERR4437465,1,1,1,8783,13617,2,COVID-ARTIC-V3,3,2020-03-22,...,.,1153.000000,2019-12-26,True,7,2,2,5,5,True
22500,ERR4638271,1,1,1,26528,26714,2,COVID-ARTIC-V3,3,2020-07-23,...,.,1120.002530,2020-01-28,True,6,2,2,11,2,False
26465,ERR4615866,54,1,1,15325,21855,1,COVID-ARTIC-V3,3,2020-08-24,...,.,1120.205275,2020-01-28,True,6,1,2,4,10,True
27003,ERR4671078,3,1,1,22993,25563,2,COVID-ARTIC-V3,3,2020-08-26,...,.,1120.205275,2020-01-28,True,14,2,3,14,10,True
28379,SRR21719160,3,1,1,6542,9515,0,COVID-ARTIC-V3,.,2020-09-02,...,.,1120.205275,2020-01-28,False,4,0,2,5,19,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430261,ERR10839848,1,1,1,19327,20741,2,COVID-ARTIC-V4.1,4.1alt,2023-01-23,...,Omicron (BA.2-like),452.000000,2021-11-26,True,16,2,11,18,23,True
1430452,SRR23358540,1,1,1,9867,12160,1,COVID-ARTIC-V4.1,.,2023-01-23,...,Omicron (BA.2-like),452.000000,2021-11-26,True,12,1,16,13,30,True
1431988,ERR10931828,1,1,1,19887,21811,2,COVID-ARTIC-V4.1,4.1alt,2023-01-29,...,Omicron (BA.2-like),221.917393,2022-07-15,True,6,2,1,5,4,True
1432902,ERR10921923,2,1,1,20742,21765,3,COVID-ARTIC-V4.1,.,2023-02-02,...,Omicron (BA.2-like),452.000000,2021-11-26,True,18,3,18,23,24,True
1436032,ERR10933490,2,1,1,27916,29729,3,COVID-ARTIC-V4.1,4.1alt,2023-02-13,...,Omicron (BA.2-like),447.000000,2021-12-01,True,7,3,6,27,2,False

In [8]:
df_pango_x = pd.read_csv("data/bigtable_sc2ts.csv").set_index("pango")
df_pango_x

,github_issue,is_in_results,is_in_arg,is_in_matches,is_clean,is_nested,re_node,type,parent_left_pango,parent_right_pango,parents_extra,interval_left,interval_right,intervals_extra
pango,,,,,,,,,,,,,,
XA,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,False,122444.0,simple,B.1.177.18,B.1.1.7,NaN,20411,21767,NaN
XAA,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XAC,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,964555.0,simple,BA.2,BA.1.17.2,NaN,24504,26060,NaN
XAD,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,964555.0,simple,BA.2,BA.1.17.2,NaN,24504,26060,NaN
XAE,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,964555.0,simple,BA.2,BA.1.17.2,NaN,24504,26060,NaN
XAF,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,False,1177107.0,simple,BA.1.1,BA.2,NaN,10199,10447,NaN
XAG,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XAJ,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XAL,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1003220.0,simple,BA.1.1,BA.2,NaN,17411,21633,NaN
XAM,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XAN,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XAP,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,964555.0,simple,BA.2,BA.1.17.2,NaN,24504,26060,NaN
XAS,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XAU,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XAV,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XAZ,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XB,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XBB,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,False,1396207.0,simple,BA.2.10,BM.1.1.1,NaN,22332,22577,NaN
XBD,NaN,True,True,NaN,True,False,1378208.0,simple,BA.2.75.2,BA.5.2.1,NaN,23020,24620,NaN
XBE,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XBF,NaN,True,True,NaN,True,False,1420385.0,simple,BA.5.2.1,BM.1.1.1,NaN,5184,9866,NaN
XBG,NaN,True,True,NaN,True,False,1291970.0,simple,BA.2.76,BA.5.2,NaN,22305,22917,NaN
XBH,NaN,True,True,NaN,True,False,1379419.0,simple,BA.2,BA.2.75.2,NaN,15452,22001,NaN
XBK,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XBM,NaN,True,True,NaN,True,False,1348822.0,simple,BA.2.76,BF.3,NaN,22305,22917,NaN
XBQ,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XBR,NaN,True,True,NaN,True,False,1420166.0,simple,BN.3.1,BQ.1.25,NaN,22034,22190,NaN
XC,NaN,True,True,NaN,True,False,414488.0,simple,AY.29,B.1.1.7,NaN,26768,27390,NaN
XE,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,965353.0,simple,BA.1.17.2,BA.2,NaN,10448,11283,NaN
XF,NaN,True,True,NaN,True,False,946761.0,simple,AY.4,BA.1,NaN,5387,6402,NaN
XG,NaN,True,True,NaN,True,False,1083412.0,simple,BA.1.17,BA.2.9,NaN,5925,6513,NaN
XH,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,965353.0,simple,BA.1.17.2,BA.2,NaN,10448,11283,NaN
XJ,NaN,True,True,NaN,True,False,966905.0,simple,BA.1.17.2,BA.2,NaN,13196,17410,NaN
XL,NaN,True,True,NaN,True,False,1034619.0,simple,BA.1.17.2,BA.2,NaN,5925,8393,NaN
XM,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,True,1003220.0,simple,BA.1.1,BA.2,NaN,17411,21633,NaN
XN,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XP,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,NaN,-1.0,non,NaN,NaN,NaN,NaN,NaN,NaN
XQ,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XR,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XS,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,False,False,1000242.0,simple,AY.103,BA.1.1,NaN,9054,10449,NaN
XU,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,1058654.0,simple,BA.1.1.15,BA.2.9,NaN,4322,5386,NaN
XW,NaN,True,True,NaN,True,False,1159411.0,simple,BA.1.1.15,BA.2,NaN,2833,4321,NaN
XY,NaN,True,True,NaN,True,False,1187989.0,simple,BA.1.1,BA.2,NaN,11538,12880,NaN
XZ,https://github.com/jeromekelleher/sc2ts-paper/...,True,True,NaN,True,True,964555.0,simple,BA.2,BA.1.17.2,NaN,24504,26060,NaN
XAB,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,False,NaN,NaN,NaN,non,NaN,NaN,NaN,NaN,NaN,NaN
XAH,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,False,NaN,NaN,NaN,non,NaN,NaN,NaN,NaN,NaN,NaN
XAK,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,Unknown (R),BA.2,NaN,21642,21762,NaN
XAY,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,complex,BA.2.*,AY.*,BA.2.*;AY.4;BA.5.*;AY.4;BA.2.*,-,-,NaN
XBC,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,complex,AY.*,BM.1.1,AY.*,-,-,NaN
XBJ,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,BA.2.3.20,BA.5.2,NaN,23019,25810,NaN
XBL,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,non,NaN,NaN,NaN,NaN,NaN,NaN
XBN,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,False,NaN,NaN,NaN,simple,BN.1,XBB,NaN,5184,12444,NaN
XBP,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,BL.2,BQ.1.1.3,NaN,22191,22331,NaN
XBS,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,BA.2.75,BQ.1.1,NaN,22034,22190,NaN
XBT,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,complex,BA.5.2.34,BA.2.75,BA.5.2.34,5184,9866,22578-22898
XBU,https://github.com/jeromekelleher/sc2ts-paper/...,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
XBW,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,XBB.1.5,BQ.1.14,NaN,25417,26275,NaN
XBZ,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,False,NaN,NaN,NaN,non,NaN,NaN,NaN,NaN,NaN,NaN
XCA,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,True,NaN,NaN,NaN,simple,BA.2.75.2,BQ.1.1.1,NaN,22748,22893,NaN
XCG,https://github.com/jeromekelleher/sc2ts-paper/...,True,False,False,NaN,NaN,NaN,non,NaN,NaN,NaN,NaN,NaN,NaN

## Compute number of samples in ARG/dataset with descendant pango classification

For each pango, compute the number of samples with pangonet classisifications that are descenedants of it.

In [9]:
pn = PangoNet().build()

2025-08-06 15:44:13,244 INFO:Downloading file: ./alias_key.json
2025-08-06 15:44:13,827 INFO:Downloading file: ./lineage_notes.txt
2025-08-06 15:44:14,662 INFO:Creating aliases.
2025-08-06 15:44:14,667 INFO:Creating network.

In [135]:
df_pango_dataset = ds.metadata.as_dataframe(["Viridian_pangolin_1.29", "Date_tree"])
# FIXME we should also filter this by the sc2ts QC criteria - but this will be tricky to do without 
# actually just running sc2ts. Perhaps the best thing to do is look-up the matches file for 
# each sample.
df_pango_dataset = df_pango_dataset[df_pango_dataset["Date_tree"] <= "2023-02-20"]
df_pango_dataset

            Viridian_pangolin_1.29   Date_tree
sample_id
SRR11772659                      A  2020-01-19
SRR11597132                      A  2020-01-29
SRR12162233                    B.1  2020-01-30
SRR12162234                    B.1  2020-01-30
SRR11597217                      A  2020-02-02
...                            ...         ...
ERR13177412                 BQ.1.1  2023-02-15
ERR13177413                XBB.1.5  2023-02-15
ERR13177414               BQ.1.1.4  2023-02-16
ERR13177415                 BQ.1.1  2023-02-16
ERR13177416                   BE.9  2023-02-08

[4355041 rows x 2 columns]

# Alternative analysis based on pango X clusters

In [480]:

arg_counts = collections.Counter(df_samples.pango)
ds_counts = collections.Counter(df_pango_dataset["Viridian_pangolin_1.29"])
pango_x_arg_counts = collections.Counter()
pango_x_ds_counts = collections.Counter()
pango_x_descendants = {}
for pango_x in df_pango_x.index.values:
    descendants = pn.get_descendants(pango_x)    
    pango_x_descendants[pango_x] = descendants
    for pango in [pango_x] + descendants:
        pango_x_arg_counts[pango_x] += arg_counts[pango]
        pango_x_ds_counts[pango_x] += ds_counts[pango]

In [481]:
tree = ts.first()

In [482]:
def analyse_pango_x(pango_x):
   
    df_pango = df_node[df_node.pango.isin([pango_x] + pango_x_descendants[pango_x])]
    #print(pango_x_descendants[pango_x])
    #print(df_pango) 
    events = []
    pango_nodes = set(df_pango.index.values)

    while len(pango_nodes) > 0:
        # Each iteration of this loop corresponds to an event
        descendants = set()
        pairs = sorted([(-ts.nodes_time[u], u) for u in pango_nodes])
        assert len(pairs) == 1 or pairs[0][0] != pairs[1][0]
        first = df_node.loc[pairs[0][1]]
        pango_samples = 0
        non_pango_samples = collections.Counter()
        root = first.name
        for v in tree.nodes(root):
            e = tree.edge(v)
            if ts.edges_left[e] != 0 and ts.edges_right[e] != ts.sequence_length:
                raise ValueError("Recombinant in subgraph")
            descendants.add(v)    

            if tree.is_sample(v):
                if v in pango_nodes:
                    pango_samples += 1
                else:
                    non_pango_samples[df_node.loc[v]["pango"]] += 1

        remaining_pango = pango_nodes - descendants
        non_pango_descendants = descendants - pango_nodes
        #print(df_node.loc[non_pango_descendants]["pango"].value_counts())
        if first.is_sample:
            root_type = "S"
        elif ts.nodes_flags[first.name] & sc2ts.NODE_IS_RECOMBINANT:
            root_type = "R"
        else:
            root_type = "I"
            
        u = root 
        while u != -1 and (ts.nodes_flags[u] & sc2ts.NODE_IS_RECOMBINANT) == 0:
            u = tree.parent(u)
        closest_recombinant = u

        closest_recombinant_path_len = np.inf
        closest_recombinant_time = np.inf
        averted_muts = -1
        if closest_recombinant != -1:
            recomb_record =  df_node.loc[closest_recombinant]
            
            if recomb_record["max_descendant_samples"] < 100_000:    
                closest_recombinant_path_len = tree.path_length(root, closest_recombinant)
                closest_recombinant_time = ts.nodes_time[closest_recombinant] - ts.nodes_time[root] 
                recomb_info = df_recombinants.loc[closest_recombinant]
                averted_muts = recomb_info["num_mutations_k1000"] - recomb_info["num_mutations_k4"]
            else:
                print("Dropping closest recomb", df_node.loc[closest_recombinant].pango)
                closest_recombinant = -1

            
        events.append({
            "pango": pango_x,
            "root": root,
            "root_pango": first.pango,
            "root_mutations": first.num_mutations,
            "root_type": root_type,
            "pango_samples": pango_samples,
            "non_pango_samples": dict(non_pango_samples),
            "arg_count": pango_x_arg_counts[pango_x],
            "ds_count": pango_x_ds_counts[pango_x],
            "closest_recombinant": closest_recombinant,
            "closest_recombinant_path_len": closest_recombinant_path_len,
            "closest_recombinant_time": closest_recombinant_time, 
            "closest_recombinant_averted_mutations": averted_muts,
        })
        
        pango_nodes = remaining_pango
   
    
    return events
e =  analyse_pango_x("XBK") 
pd.DataFrame(e)

Dropping closest recomb BA.2

,pango,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,arg_count,ds_count,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_averted_mutations
0,XBK,1425824,XBK,1,I,7,{},7,157,-1,inf,inf,-1

In [ ]:
analyse_pango_x

In [483]:
data = []
for pango_x in df_pango_x.index.values:
    if pango_x in []: #["XBB", "XM", "XAC", "XAD"]:
        continue
    events = analyse_pango_x(pango_x)
    
    if len(events) > 1:
        events.sort(key=lambda x: -x["pango_samples"])
        print("dropping multi events", pango_x, len(events[1:]))
    data.extend(events[:1])
    
df = pd.DataFrame(data)

dropping multi events XBB 1
Dropping closest recomb BA.5
Dropping closest recomb BA.2
Dropping closest recomb BA.2
Dropping closest recomb BA.5
Dropping closest recomb BA.2
Dropping closest recomb BA.2
Dropping closest recomb BA.5
Dropping closest recomb BA.2
dropping multi events XAC 3
Dropping closest recomb BA.2
Dropping closest recomb BA.5
dropping multi events XM 3
dropping multi events XAD 1

In [440]:
df

,pango,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,arg_count,ds_count,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_averted_mutations
0,XBB,1396207,XBB,14,R,6452,{'BA.2': 1},6454,30882,1396207,0.0,0.000000,8
1,XE,965352,XE,2,S,1116,{},1116,1530,965353,1.0,19.000000,6
2,XBF,1420385,XBF,3,R,185,{},185,705,1420385,0.0,0.000000,6
3,XQ,1058654,XQ,3,R,55,"{'BA.2': 35, 'XAA': 17, 'XU': 1, 'XAM': 21, 'X...",55,76,1058654,0.0,0.000000,7
4,XAZ,1285706,XAZ,3,I,133,{},133,306,-1,inf,inf,-1
5,XN,1061700,XN,2,S,120,{'BA.2': 1},120,203,-1,inf,inf,-1
6,XAS,1265115,XAS,1,S,77,{},77,111,-1,inf,inf,-1
7,XJ,966904,XJ,2,S,68,{'BA.2': 3},68,87,966905,1.0,5.000000,5
8,XBE,1363926,XBE,3,I,65,{},65,109,-1,inf,inf,-1
9,XL,1034619,XL,1,R,64,{},64,84,1034619,0.0,0.000000,8
10,XZ,1163537,XZ,2,I,48,{},48,63,964555,3.0,46.424634,6
11,XP,1092789,XP,1,S,45,{},45,63,-1,inf,inf,-1
12,XA,122444,XA,1,R,39,{},39,42,122444,0.0,0.000000,12
13,XW,1159411,XW,1,R,32,{},32,49,1159411,0.0,0.000000,4
14,XBD,1378208,XBD,0,R,30,{},30,64,1378208,0.0,0.000000,7
15,XBG,1291970,XBG,2,R,25,{},25,48,1291970,0.0,0.000000,8
16,XY,1187989,XY,2,R,23,{},23,32,1187989,0.0,0.000000,5
17,XB,223239,XB,2,I,192,{},192,369,-1,inf,inf,-1
18,XAM,1240312,XAM,4,I,21,{},21,32,1058654,4.0,33.300763,7
19,XAP,1216836,XAP,1,I,20,{},20,26,964555,4.0,64.779711,6
20,XAJ,1276376,XAJ,11,I,18,{},18,32,-1,inf,inf,-1
21,XR,1148222,XR,4,I,17,{'BA.2': 1},17,20,1058654,3.0,11.000000,7
22,XAA,1183815,XAA,3,I,17,{},17,22,1058654,5.0,33.000000,7
23,XS,1000242,XS,1,R,17,{},17,25,1000242,0.0,0.000000,11
24,XF,946761,XF,1,R,16,{},16,25,946761,0.0,0.000000,5
25,XBQ,1422955,XBQ,1,I,14,{},14,33,-1,inf,inf,-1
26,XAV,1269391,XAV,3,S,13,{},13,14,-1,inf,inf,-1
27,XBM,1358392,XBM,1,I,10,{},10,22,1348822,1.0,23.976698,6
28,XAE,1118099,XAE,7,S,9,{},9,12,964555,2.0,47.000000,6
29,XAU,1231548,XAU,1,S,8,{},8,14,-1,inf,inf,-1
30,XAC,1241084,XAC,3,S,9,{},18,34,964555,4.0,120.000000,6
31,XBK,1425824,XBK,1,I,7,{},7,157,-1,inf,inf,-1
32,XAN,1301399,XAN,5,I,7,{},7,31,-1,inf,inf,-1
33,XAG,1248341,XAG,5,I,6,{},6,20,1058654,4.0,50.405054,7
34,XC,414488,XC,1,R,5,{},5,6,414488,0.0,0.000000,14
35,XG,1083412,XG,3,R,3,{},3,178,1083412,0.0,0.000000,4
36,XAL,1264107,XAL,2,I,3,{},3,15,1003220,3.0,63.758451,6
37,XH,1098084,XH,7,S,2,{},2,49,965353,1.0,55.000000,6
38,XBH,1395926,XBH,2,I,2,{},2,6,1379419,1.0,35.971066,5
39,XAF,1314603,XAF,9,S,1,{},1,19,1177107,3.0,140.000000,5
40,XM,1003220,XM,0,R,26,"{'BA.2': 16, 'XAL': 3}",29,45,1003220,0.0,0.000000,6
41,XAD,1108280,XAD,6,S,1,{},2,4,964555,3.0,44.000000,6
42,XBR,1420166,XBR,2,R,1,{},1,4,1420166,0.0,0.000000,22
43,XU,1243765,XU,4,S,1,{},1,1,1058654,5.0,103.000000,7

In [443]:
df = df.sort_values(["closest_recombinant", "closest_recombinant_path_len"], ascending=False)
df["outside"] = df["arg_count"] - df["pango_samples"]

In [449]:
col_name_map = {
    "pango": "pango",
    "root_mutations": "muts",
    "root_type": "type",
    "root": "root",
    "closest_recombinant": "recomb",
    "closest_recombinant_averted_mutations": "averted",
    "closest_recombinant_time": "t recomb",
    "closest_recombinant_path_len": "p recomb",
    "pango_samples": "samples", 
    "outside": "outside",
    "non_pango_samples": "extra" 
    
}

pango_events_tbl = df[list(col_name_map.keys())]
pango_events_tbl

,pango,root_mutations,root_type,root,closest_recombinant,closest_recombinant_averted_mutations,closest_recombinant_time,closest_recombinant_path_len,pango_samples,outside,non_pango_samples
2,XBF,3,R,1420385,1420385,6,0.000000,0.0,185,0,{}
42,XBR,2,R,1420166,1420166,22,0.000000,0.0,1,0,{}
0,XBB,14,R,1396207,1396207,8,0.000000,0.0,6452,2,{'BA.2': 1}
38,XBH,2,I,1395926,1379419,5,35.971066,1.0,2,0,{}
14,XBD,0,R,1378208,1378208,7,0.000000,0.0,30,0,{}
27,XBM,1,I,1358392,1348822,6,23.976698,1.0,10,0,{}
15,XBG,2,R,1291970,1291970,8,0.000000,0.0,25,0,{}
16,XY,2,R,1187989,1187989,5,0.000000,0.0,23,0,{}
39,XAF,9,S,1314603,1177107,5,140.000000,3.0,1,0,{}
13,XW,1,R,1159411,1159411,4,0.000000,0.0,32,0,{}
35,XG,3,R,1083412,1083412,4,0.000000,0.0,3,0,{}
22,XAA,3,I,1183815,1058654,7,33.000000,5.0,17,0,{}
43,XU,4,S,1243765,1058654,7,103.000000,5.0,1,0,{}
18,XAM,4,I,1240312,1058654,7,33.300763,4.0,21,0,{}
33,XAG,5,I,1248341,1058654,7,50.405054,4.0,6,0,{}
21,XR,4,I,1148222,1058654,7,11.000000,3.0,17,0,{'BA.2': 1}
3,XQ,3,R,1058654,1058654,7,0.000000,0.0,55,0,"{'BA.2': 35, 'XAA': 17, 'XU': 1, 'XAM': 21, 'X..."
9,XL,1,R,1034619,1034619,8,0.000000,0.0,64,0,{}
36,XAL,2,I,1264107,1003220,6,63.758451,3.0,3,0,{}
40,XM,0,R,1003220,1003220,6,0.000000,0.0,26,3,"{'BA.2': 16, 'XAL': 3}"
23,XS,1,R,1000242,1000242,11,0.000000,0.0,17,0,{}
7,XJ,2,S,966904,966905,5,5.000000,1.0,68,0,{'BA.2': 3}
1,XE,2,S,965352,965353,6,19.000000,1.0,1116,0,{}
37,XH,7,S,1098084,965353,6,55.000000,1.0,2,0,{}
19,XAP,1,I,1216836,964555,6,64.779711,4.0,20,0,{}
30,XAC,3,S,1241084,964555,6,120.000000,4.0,9,9,{}
10,XZ,2,I,1163537,964555,6,46.424634,3.0,48,0,{}
41,XAD,6,S,1108280,964555,6,44.000000,3.0,1,1,{}
28,XAE,7,S,1118099,964555,6,47.000000,2.0,9,0,{}
24,XF,1,R,946761,946761,5,0.000000,0.0,16,0,{}
34,XC,1,R,414488,414488,14,0.000000,0.0,5,0,{}
12,XA,1,R,122444,122444,12,0.000000,0.0,39,0,{}
4,XAZ,3,I,1285706,-1,-1,inf,inf,133,0,{}
5,XN,2,S,1061700,-1,-1,inf,inf,120,0,{'BA.2': 1}
6,XAS,1,S,1265115,-1,-1,inf,inf,77,0,{}
8,XBE,3,I,1363926,-1,-1,inf,inf,65,0,{}
11,XP,1,S,1092789,-1,-1,inf,inf,45,0,{}
17,XB,2,I,223239,-1,-1,inf,inf,192,0,{}
20,XAJ,11,I,1276376,-1,-1,inf,inf,18,0,{}
25,XBQ,1,I,1422955,-1,-1,inf,inf,14,0,{}
26,XAV,3,S,1269391,-1,-1,inf,inf,13,0,{}
29,XAU,1,S,1231548,-1,-1,inf,inf,8,0,{}
31,XBK,1,I,1425824,-1,-1,inf,inf,7,0,{}
32,XAN,5,I,1301399,-1,-1,inf,inf,7,0,{}

In [452]:
recombs_tbl = pango_events_tbl[pango_events_tbl["root_type"] == "R"].sort_values(
    "closest_recombinant_averted_mutations", ascending=False)
recombs_tbl

,pango,root_mutations,root_type,root,closest_recombinant,closest_recombinant_averted_mutations,closest_recombinant_time,closest_recombinant_path_len,pango_samples,outside,non_pango_samples
42,XBR,2,R,1420166,1420166,22,0.0,0.0,1,0,{}
34,XC,1,R,414488,414488,14,0.0,0.0,5,0,{}
12,XA,1,R,122444,122444,12,0.0,0.0,39,0,{}
23,XS,1,R,1000242,1000242,11,0.0,0.0,17,0,{}
0,XBB,14,R,1396207,1396207,8,0.0,0.0,6452,2,{'BA.2': 1}
15,XBG,2,R,1291970,1291970,8,0.0,0.0,25,0,{}
9,XL,1,R,1034619,1034619,8,0.0,0.0,64,0,{}
14,XBD,0,R,1378208,1378208,7,0.0,0.0,30,0,{}
3,XQ,3,R,1058654,1058654,7,0.0,0.0,55,0,"{'BA.2': 35, 'XAA': 17, 'XU': 1, 'XAM': 21, 'X..."
2,XBF,3,R,1420385,1420385,6,0.0,0.0,185,0,{}
40,XM,0,R,1003220,1003220,6,0.0,0.0,26,3,"{'BA.2': 16, 'XAL': 3}"
16,XY,2,R,1187989,1187989,5,0.0,0.0,23,0,{}
24,XF,1,R,946761,946761,5,0.0,0.0,16,0,{}
13,XW,1,R,1159411,1159411,4,0.0,0.0,32,0,{}
35,XG,3,R,1083412,1083412,4,0.0,0.0,3,0,{}

In [464]:
close_recombs = pango_events_tbl[(pango_events_tbl["root_type"] != "R")
    & (pango_events_tbl["closest_recombinant"] != -1)]
close_recombs = close_recombs.sort_values(["closest_recombinant", "closest_recombinant_time"])
close_recombs

,pango,root_mutations,root_type,root,closest_recombinant,closest_recombinant_averted_mutations,closest_recombinant_time,closest_recombinant_path_len,pango_samples,outside,non_pango_samples
41,XAD,6,S,1108280,964555,6,44.000000,3.0,1,1,{}
10,XZ,2,I,1163537,964555,6,46.424634,3.0,48,0,{}
28,XAE,7,S,1118099,964555,6,47.000000,2.0,9,0,{}
19,XAP,1,I,1216836,964555,6,64.779711,4.0,20,0,{}
30,XAC,3,S,1241084,964555,6,120.000000,4.0,9,9,{}
1,XE,2,S,965352,965353,6,19.000000,1.0,1116,0,{}
37,XH,7,S,1098084,965353,6,55.000000,1.0,2,0,{}
7,XJ,2,S,966904,966905,5,5.000000,1.0,68,0,{'BA.2': 3}
36,XAL,2,I,1264107,1003220,6,63.758451,3.0,3,0,{}
21,XR,4,I,1148222,1058654,7,11.000000,3.0,17,0,{'BA.2': 1}
22,XAA,3,I,1183815,1058654,7,33.000000,5.0,17,0,{}
18,XAM,4,I,1240312,1058654,7,33.300763,4.0,21,0,{}
33,XAG,5,I,1248341,1058654,7,50.405054,4.0,6,0,{}
43,XU,4,S,1243765,1058654,7,103.000000,5.0,1,0,{}
39,XAF,9,S,1314603,1177107,5,140.000000,3.0,1,0,{}
27,XBM,1,I,1358392,1348822,6,23.976698,1.0,10,0,{}
38,XBH,2,I,1395926,1379419,5,35.971066,1.0,2,0,{}

In [474]:
non_recombs = pango_events_tbl[pango_events_tbl["closest_recombinant"] == -1]
non_recombs = non_recombs.sort_values(["root_mutations", "pango_samples"])
non_recombs

,pango,root_mutations,root_type,root,closest_recombinant,closest_recombinant_averted_mutations,closest_recombinant_time,closest_recombinant_path_len,pango_samples,outside,non_pango_samples
31,XBK,1,I,1425824,-1,-1,inf,inf,7,0,{}
29,XAU,1,S,1231548,-1,-1,inf,inf,8,0,{}
25,XBQ,1,I,1422955,-1,-1,inf,inf,14,0,{}
11,XP,1,S,1092789,-1,-1,inf,inf,45,0,{}
6,XAS,1,S,1265115,-1,-1,inf,inf,77,0,{}
5,XN,2,S,1061700,-1,-1,inf,inf,120,0,{'BA.2': 1}
17,XB,2,I,223239,-1,-1,inf,inf,192,0,{}
26,XAV,3,S,1269391,-1,-1,inf,inf,13,0,{}
8,XBE,3,I,1363926,-1,-1,inf,inf,65,0,{}
4,XAZ,3,I,1285706,-1,-1,inf,inf,133,0,{}
32,XAN,5,I,1301399,-1,-1,inf,inf,7,0,{}
20,XAJ,11,I,1276376,-1,-1,inf,inf,18,0,{}

In [484]:
out = []
for tbl in [recombs_tbl, close_recombs, non_recombs]:

    s = tbl.to_latex(
        escape=True, index=False, columns=col_name_map.keys(), header=list(col_name_map.values()),
        float_format="%.0f")
    s = s.replace("'", "").replace(": ", ":")
    s = s.replace("{BA.2:35, XAA:17, XU:1, XAM:21, XAG:6, XR:17}", "{BA.2:35, $\star$}")
    splits = s.splitlines()
    footer = splits[-2:]
    splits = splits[:-2]
    if len(out) > 0:
        splits = splits[3:]
    out.extend(splits)
    

out.extend(footer)
print("\n".join(out))

\begin{tabular}{lrlrrrrrrrl}
\toprule
pango & muts & type & root & recomb & averted & t recomb & p recomb & samples & outside & extra \\
\midrule
XBR & 2 & R & 1420166 & 1420166 & 22 & 0 & 0 & 1 & 0 & {} \\
XC & 1 & R & 414488 & 414488 & 14 & 0 & 0 & 5 & 0 & {} \\
XA & 1 & R & 122444 & 122444 & 12 & 0 & 0 & 39 & 0 & {} \\
XS & 1 & R & 1000242 & 1000242 & 11 & 0 & 0 & 17 & 0 & {} \\
XBB & 14 & R & 1396207 & 1396207 & 8 & 0 & 0 & 6452 & 2 & {BA.2:1} \\
XBG & 2 & R & 1291970 & 1291970 & 8 & 0 & 0 & 25 & 0 & {} \\
XL & 1 & R & 1034619 & 1034619 & 8 & 0 & 0 & 64 & 0 & {} \\
XBD & 0 & R & 1378208 & 1378208 & 7 & 0 & 0 & 30 & 0 & {} \\
XQ & 3 & R & 1058654 & 1058654 & 7 & 0 & 0 & 55 & 0 & {BA.2:35, $\star$} \\
XBF & 3 & R & 1420385 & 1420385 & 6 & 0 & 0 & 185 & 0 & {} \\
XM & 0 & R & 1003220 & 1003220 & 6 & 0 & 0 & 26 & 3 & {BA.2:16, XAL:3} \\
XY & 2 & R & 1187989 & 1187989 & 5 & 0 & 0 & 23 & 0 & {} \\
XF & 1 & R & 946761 & 946761 & 5 & 0 & 0 & 16 & 0 & {} \\
XW & 1 & R & 1159411 & 1159411 & 4 & 0 & 0 & 32 & 0 & {} \\
XG & 3 & R & 1083412 & 1083412 & 4 & 0 & 0 & 3 & 0 & {} \\
\midrule
XAD & 6 & S & 1108280 & 964555 & 6 & 44 & 3 & 1 & 1 & {} \\
XZ & 2 & I & 1163537 & 964555 & 6 & 46 & 3 & 48 & 0 & {} \\
XAE & 7 & S & 1118099 & 964555 & 6 & 47 & 2 & 9 & 0 & {} \\
XAP & 1 & I & 1216836 & 964555 & 6 & 65 & 4 & 20 & 0 & {} \\
XAC & 3 & S & 1241084 & 964555 & 6 & 120 & 4 & 9 & 9 & {} \\
XE & 2 & S & 965352 & 965353 & 6 & 19 & 1 & 1116 & 0 & {} \\
XH & 7 & S & 1098084 & 965353 & 6 & 55 & 1 & 2 & 0 & {} \\
XJ & 2 & S & 966904 & 966905 & 5 & 5 & 1 & 68 & 0 & {BA.2:3} \\
XAL & 2 & I & 1264107 & 1003220 & 6 & 64 & 3 & 3 & 0 & {} \\
XR & 4 & I & 1148222 & 1058654 & 7 & 11 & 3 & 17 & 0 & {BA.2:1} \\
XAA & 3 & I & 1183815 & 1058654 & 7 & 33 & 5 & 17 & 0 & {} \\
XAM & 4 & I & 1240312 & 1058654 & 7 & 33 & 4 & 21 & 0 & {} \\
XAG & 5 & I & 1248341 & 1058654 & 7 & 50 & 4 & 6 & 0 & {} \\
XU & 4 & S & 1243765 & 1058654 & 7 & 103 & 5 & 1 & 0 & {} \\
XAF & 9 & S & 1314603 & 1177107 & 5 & 140 & 3 & 1 & 0 & {} \\
XBM & 1 & I & 1358392 & 1348822 & 6 & 24 & 1 & 10 & 0 & {} \\
XBH & 2 & I & 1395926 & 1379419 & 5 & 36 & 1 & 2 & 0 & {} \\
\midrule
XBK & 1 & I & 1425824 & -1 & -1 & inf & inf & 7 & 0 & {} \\
XAU & 1 & S & 1231548 & -1 & -1 & inf & inf & 8 & 0 & {} \\
XBQ & 1 & I & 1422955 & -1 & -1 & inf & inf & 14 & 0 & {} \\
XP & 1 & S & 1092789 & -1 & -1 & inf & inf & 45 & 0 & {} \\
XAS & 1 & S & 1265115 & -1 & -1 & inf & inf & 77 & 0 & {} \\
XN & 2 & S & 1061700 & -1 & -1 & inf & inf & 120 & 0 & {BA.2:1} \\
XB & 2 & I & 223239 & -1 & -1 & inf & inf & 192 & 0 & {} \\
XAV & 3 & S & 1269391 & -1 & -1 & inf & inf & 13 & 0 & {} \\
XBE & 3 & I & 1363926 & -1 & -1 & inf & inf & 65 & 0 & {} \\
XAZ & 3 & I & 1285706 & -1 & -1 & inf & inf & 133 & 0 & {} \\
XAN & 5 & I & 1301399 & -1 & -1 & inf & inf & 7 & 0 & {} \\
XAJ & 11 & I & 1276376 & -1 & -1 & inf & inf & 18 & 0 & {} \\
\bottomrule
\end{tabular}