In [1]:
import pandas as pd

In [2]:
# Downloaded from https://zenodo.org/records/19815950
#
# md5sum-lite
# 66d90af3a722fe22ad8b5e22f25f8366  flagged_samples_5_0_10_3.txt
#
# 10,942 potentially contaminant samples
phycd_df = pd.read_csv("flagged_samples_5_0_10_3.txt", skiprows=1, header=None)
contam_samples = phycd_df[0].to_list()
contam_samples

['SRR27368009',
 'ERR7712066',
 'SRR25440453',
 'SRR25690600',
 'ERR5990373',
 'ERR8223706',
 'ERR11255108',
 'SRR22375832',
 'ERR8257863',
 'ERR12539249',
 'SRR18603732',
 'SRR17905556',
 'ERR8229135',
 'SRR16007713',
 'SRR17211780',
 'SRR25414926',
 'SRR23472929',
 'SRR21487391',
 'SRR17901891',
 'SRR18978381',
 'ERR12255674',
 'SRR25416876',
 'ERR8179538',
 'ERR8238928',
 'SRR17723906',
 'SRR18530416',
 'SRR25414589',
 'SRR18978279',
 'ERR8221414',
 'SRR18978295',
 'SRR18978378',
 'SRR18978394',
 'SRR18978380',
 'ERR11743178',
 'SRR25727347',
 'SRR17253923',
 'SRR22573634',
 'ERR8240382',
 'SRR25415237',
 'SRR19570474',
 'SRR21784723',
 'SRR27492319',
 'ERR8180113',
 'SRR25414957',
 'SRR18978236',
 'ERR8169643',
 'SRR18978300',
 'SRR15515980',
 'SRR18978238',
 'ERR8211693',
 'SRR23895638',
 'SRR19371806',
 'ERR8246546',
 'ERR12014478',
 'SRR15187251',
 'ERR12047846',
 'SRR28812961',
 'SRR18903290',
 'SRR25414947',
 'ERR5973151',
 'ERR8254343',
 'SRR19050577',
 'SRR26978140',
 'SRR19465959',
 'SRR19447785',
 'SRR18978340',
 'SRR18978376',
 'ERR13176398',
 'ERR8441796',
 'ERR9904010',
 'SRR18978307',
 'SRR21502952',
 'SRR18978302',
 'ERR5495972',
 'ERR8208713',
 'SRR19465709',
 'SRR17913776',
 'SRR15513703',
 'SRR16829369',
 'SRR26969451',
 'SRR22968632',
 'SRR17077600',
 'SRR29553026',
 'SRR21114172',
 'ERR8204488',
 'SRR18978216',
 'SRR18978308',
 'SRR24083377',
 'SRR28557362',
 'SRR19051817',
 'SRR25161647',
 'SRR19600214',
 'ERR5514052',
 'SRR27366540',
 'SRR12278624',
 'SRR17416682',
 'ERR8216159',
 'ERR6756005',
 'SRR25678943',
 'SRR19375044',
 'SRR19484302',
 'ERR7716207',
 'SRR27828579',
 'SRR17856259',
 'ERR9124201',
 'SRR19473432',
 'SRR28103224',
 'ERR5670203',
 'ERR7705904',
 'ERR12055683',
 'SRR14884175',
 'SRR18978342',
 'ERR13248526',
 'SRR18047355',
 'SRR24427483',
 'SRR17350691',
 'ERR8209761',
 'SRR18687879',
 'SRR24428800',
 'SRR26583958',
 'ERR11516614',
 'ERR8220088',
 'SRR28104662',
 'SRR18430455',
 'ERR9030617',
 'SRR15698363',
 'ERR8259002',
 'ERR9981029',
 'SRR18978391',
 'SRR15024911',
 'SRR14884214',
 'SRR18978399',
 'SRR28347317',
 'SRR15891565',
 'SRR25517146',
 'ERR5501728',
 'ERR5739144',
 'SRR17813896',
 'ERR5666357',
 'SRR15418133',
 'ERR8171590',
 'SRR19485181',
 'SRR17856202',
 'SRR14707657',
 'ERR6880225',
 'SRR16595882',
 'ERR5739142',
 'SRR19466477',
 'ERR7206163',
 'ERR6424265',
 'ERR7015910',
 'ERR8179584',
 'SRR17960846',
 'SRR25665622',
 'SRR17090254',
 'ERR5499313',
 'SRR17887319',
 'ERR7582819',
 'ERR13173496',
 'SRR17417455',
 'ERR5941762',
 'SRR12181105',
 'SRR19469503',
 'SRR18545090',
 'SRR23979751',
 'SRR16326356',
 'ERR7891542',
 'SRR18687875',
 'SRR12045839',
 'ERR5739145',
 'SRR15053603',
 'SRR18677447',
 'ERR8236648',
 'ERR7446140',
 'SRR23133653',
 'ERR8180826',
 'ERR8209796',
 'SRR16298381',
 'SRR22972971',
 'ERR5758833',
 'SRR18038888',
 'ERR12670020',
 'SRR19827217',
 'SRR21935701',
 'ERR9940487',
 'SRR28435675',
 'SRR27719918',
 'SRR17754070',
 'SRR18533678',
 'SRR14476354',
 'ERR8194069',
 'ERR8239799',
 'SRR14570483',
 'SRR19473450',
 'SRR27353628',
 'SRR18688196',
 'SRR14658660',
 'SRR18978224',
 'SRR19473521',
 'SRR27365888',
 'SRR18978296',
 'SRR17905521',
 'SRR16750153',
 'SRR17889094',
 'SRR21994186',
 'SRR21935501',
 'SRR28114494',
 'SRR21158568',
 'SRR24428782',
 'ERR12121366',
 'ERR5495439',
 'SRR17627054',
 'SRR14994767',
 'ERR8225353',
 'SRR23625464',
 'SRR19600528',
 'SRR21925125',
 'SRR14994694',
 'ERR10749031',
 'ERR7686591',
 'SRR14709556',
 'SRR29364124',
 'SRR19473522',
 'SRR19473505',
 'ERR11896819',
 'ERR8208102',
 'SRR22246454',
 'ERR7240784',
 'ERR8169662',
 'SRR19600185',
 'SRR15891389',
 'SRR25519783',
 'ERR11763850',
 'SRR24993195',
 'SRR18020776',
 'SRR29049513',
 'SRR17176273',
 'SRR23204764',
 'SRR28446067',
 'SRR17351757',
 'ERR6566904',
 'SRR23979896',
 'SRR25669676',
 'ERR12055068',
 'ERR12014219',
 'SRR27387066',
 'ERR6742286',
 'SRR18688208',
 'ERR6879537',
 'SRR22573413',
 'SRR18152103',
 'SRR18068325',
 'SRR18688034',
 'ERR6835672',
 'ERR6299170',
 'SRR23979844',
 'SRR14711664',
 'SRR24607869',
 'SRR19695106',
 'ERR9981467',
 'SRR18688353',
 'SRR18431572',
 'SRR18688358',
 'ERR11743116',
 'ERR8173021',
 'ERR6720435',
 'SRR18125523',
 'SRR18688492',
 'SRR23980017',
 'ERR12666380',
 'SRR19156146',
 'SRR18688270',
 'ERR6437364',
 'SRR27719449',
 'SRR23011204',
 'ERR7200423',
 'ERR13085256',
 'SRR17697189',
 'SRR24603483',
 'ERR5506449',
 'SRR18687892',
 'SRR18688033',
 'SRR18014672',
 'ERR5628180',
 'SRR18301478',
 'SRR18152527',
 'ERR5747917',
 'SRR24602643',
 'SRR27920084',
 'SRR14699089',
 'SRR18978287',
 'SRR18687915',
 'SRR24602874',
 'SRR18978401',
 'ERR8287699',
 'SRR17903416',
 'ERR9715111',
 'ERR9846943',
 'SRR23593373',
 'ERR9714503',
 'ERR8185745',
 'SRR16253831',
 'SRR23979837',
 'SRR23625584',
 'SRR18978265',
 'ERR8564417',
 'SRR19675833',
 'SRR23979491',
 'SRR18152477',
 'ERR6722262',
 'SRR24603243',
 'SRR18853558',
 'SRR14023732',
 'ERR6756509',
 'SRR24603283',
 'ERR5758832',
 'SRR17766394',
 'SRR24602668',
 'SRR16792891',
 'ERR12539032',
 'SRR24602684',
 'SRR14709525',
 'SRR18688483',
 'ERR8213626',
 'SRR17019142',
 'SRR24427907',
 'ERR8234483',
 'ERR8200592',
 'ERR10150285',
 'ERR5515204',
 'SRR24427914',
 'SRR18554345',
 'ERR12121374',
 'SRR18556967',
 'ERR7583869',
 'SRR18554278',
 'SRR15919796',
 'SRR18152480',
 'ERR9836021',
 'ERR11177896',
 'SRR16547902',
 'ERR8482102',
 'ERR8108055',
 'ERR8755710',
 'SRR21935690',
 'SRR26722570',
 'SRR19684959',
 'SRR19464876',
 'SRR15390515',
 'ERR8250753',
 'SRR16129632',
 'SRR15515078',
 'SRR17030919',
 'ERR11896656',
 'ERR7320298',
 'SRR18666223',
 'SRR24603546',
 'ERR5758831',
 'SRR19156124',
 'SRR24428790',
 'ERR5631763',
 'ERR11742636',
 'SRR25414870',
 'ERR6758873',
 'SRR19195451',
 'ERR7003958',
 'ERR5511990',
 'SRR29433495',
 'SRR12270091',
 'SRR29433539',
 'SRR18532362',
 'SRR25665352',
 'SRR25690651',
 'SRR24428640',
 'ERR10476316',
 'SRR15635761',
 'SRR15689205',
 'SRR21925070',
 'ERR8191617',
 'SRR23957298',
 'ERR13052662',
 'SRR21022367',
 'SRR21158694',
 'SRR22470608',
 'SRR19602687',
 'SRR14225665',
 'SRR25673565',
 'ERR10163645',
 'ERR9309429',
 'SRR15571680',
 'SRR23079619',
 'SRR18666357',
 'SRR17708399',
 'SRR25025843',
 'ERR4892498',
 'ERR4182254',
 'ERR8258058',
 'SRR15270601',
 'SRR19461480',
 'SRR14711769',
 'ERR8177712',
 'SRR17471359',
 'SRR18688093',
 'SRR18372146',
 'ERR6740486',
 'ERR12155769',
 'SRR22243731',
 'SRR17253914',
 'ERR6377309',
 'SRR17690941',
 'SRR17417189',
 'SRR19375189',
 'SRR29433589',
 'ERR5699430',
 'SRR22076628',
 'SRR18666116',
 'ERR12524715',
 'ERR13076763',
 'SRR20951729',
 'ERR12742247',
 'SRR18666036',
 'ERR4839106',
 'SRR22020279',
 'SRR15891488',
 'SRR28812949',
 'SRR17026722',
 'SRR18454999',
 'SRR16904265',
 'SRR18665690',
 'ERR7891635',
 'SRR18241460',
 'ERR4891957',
 'SRR16547856',
 'SRR16350622',
 'SRR19468270',
 'SRR16220599',
 'SRR18666298',
 'ERR9379536',
 'ERR8236961',
 'SRR15226346',
 'SRR17521902',
 'SRR16149229',
 'SRR18586974',
 'SRR19323029',
 'SRR29049464',
 'SRR27828628',
 'SRR18978225',
 'SRR25414896',
 'SRR19822170',
 'SRR18666050',
 'SRR24798143',
 'ERR13176484',
 'ERR9847937',
 'SRR18688146',
 'SRR18128855',
 'ERR9594779',
 'ERR8252665',
 'SRR18151965',
 'ERR6720183',
 'SRR21022413',
 'SRR16589455',
 'ERR9979855',
 'SRR13603880',
 'ERR6062823',
 'SRR24992755',
 'ERR8210251',
 'ERR7799183',
 'SRR23979654',
 'ERR10109691',
 'SRR14711661',
 'SRR29049471',
 'ERR10428751',
 'ERR8203860',
 'SRR18688342',
 'SRR18687827',
 'SRR17871700',
 'SRR18666270',
 'SRR18687896',
 'ERR8981845',
 'SRR18710903',
 'SRR16501614',
 'SRR17577171',
 'SRR18688356',
 'ERR7239300',
 'SRR18665809',
 'SRR18688169',
 'SRR18687877',
 'SRR21935991',
 'ERR6865050',
 'SRR18978311',
 'SRR16618306',
 'SRR18666268',
 'SRR18989781',
 'SRR14711608',
 'ERR5513385',
 'SRR11840024',
 'ERR11967143',
 'SRR16986762',
 'SRR29288910',
 'SRR16073830',
 'SRR14916288',
 'ERR8182977',
 'SRR28101302',
 'SRR21830521',
 'SRR17018855',
 'SRR15945266',
 'ERR9851361',
 'SRR18688152',
 'SRR15983165',
 'ERR8962390',
 'SRR24429542',
 'SRR16883883',
 'SRR19683454',
 'SRR26444316',
 'SRR19183748',
 'SRR25440682',
 'SRR20185155',
 'SRR16169831',
 'SRR20258246',
 'ERR8181700',
 'ERR5517369',
 'SRR18689187',
 'ERR4640567',
 'SRR17267751',
 'SRR16853471',
 'SRR19471689',
 'SRR23979676',
 'SRR15226858',
 'ERR8572844',
 'ERR12076588',
 'SRR20912934',
 'ERR5779746',
 'ERR10150279',
 'SRR22972997',
 'ERR12083176',
 'ERR6888753',
 'ERR12157274',
 'SRR18091886',
 'ERR8227992',
 'ERR9975483',
 'SRR20914833',
 'ERR10481251',
 'SRR18047212',
 'SRR21092001',
 'SRR24428602',
 'SRR19465359',
 'ERR5496268',
 'ERR8182932',
 'SRR20116475',
 'SRR23979814',
 'ERR8257735',
 'ERR8564439',
 'SRR15513345',
 'SRR13899549',
 'SRR17889065',
 'SRR12763455',
 'ERR8176085',
 'ERR12083177',
 'SRR25187675',
 'SRR19045634',
 'SRR15187271',
 'ERR8218908',
 'SRR23625275',
 'SRR21093857',
 'ERR5746299',
 'SRR23625437',
 'SRR23979868',
 'SRR18504272',
 'SRR23381198',
 'SRR25025414',
 'ERR7317565',
 'SRR23979440',
 'SRR19485543',
 'SRR23537778',
 'SRR15513485',
 'SRR24427917',
 'SRR14712370',
 'SRR24602659',
 'SRR21084567',
 'SRR24603263',
 'ERR12155425',
 'SRR18015046',
 'SRR23979656',
 'SRR18207701',
 'SRR19480928',
 'ERR7708571',
 'ERR8206927',
 'SRR24428631',
 'SRR18554353',
 'ERR7232035',
 'ERR7770936',
 'SRR14400989',
 'SRR14655817',
 'ERR5746348',
 'SRR24427934',
 'ERR12164066',
 'SRR18160481',
 'ERR9420253',
 'SRR18666335',
 'SRR18081986',
 'SRR16753508',
 'ERR8610936',
 'SRR14707630',
 'SRR20210000',
 'SRR18155127',
 'SRR17220348',
 'SRR16566726',
 'SRR20114252',
 'SRR25682756',
 'SRR23979858',
 'SRR23625171',
 'SRR19374769',
 'SRR21935787',
 'SRR24428590',
 'SRR25416883',
 'SRR28557405',
 'SRR17971349',
 'ERR6594181',
 'ERR10286839',
 'ERR7936501',
 'SRR28122172',
 'ERR8215515',
 'ERR9270638',
 'ERR12178743',
 'SRR17712543',
 'ERR10805165',
 'SRR16003227',
 'SRR18614283',
 'SRR19491723',
 'ERR9981251',
 'SRR24583489',
 'ERR9979993',
 'SRR22361772',
 'SRR19155870',
 'ERR6765059',
 'SRR18848309',
 'SRR19468448',
 'SRR24427439',
 'SRR17117455',
 'SRR26275557',
 'SRR24429550',
 'SRR28334736',
 'SRR12212581',
 'SRR19602392',
 'SRR20900053',
 'ERR12155422',
 'SRR24602855',
 'SRR19148703',
 'SRR17665107',
 'ERR5502660',
 'SRR16593437',
 'SRR18312141',
 'SRR28397929',
 'SRR27334516',
 'SRR14210318',
 'SRR19473627',
 'ERR5507473',
 'ERR9836020',
 'ERR5747608',
 'SRR13899635',
 'ERR7006354',
 'SRR17785297',
 'SRR15334248',
 'SRR19115859',
 'ERR8233297',
 'SRR18241092',
 'ERR9880878',
 'ERR8959783',
 'ERR6305524',
 'ERR7702510',
 'ERR8578948',
 'SRR15516270',
 'SRR23217263',
 'ERR7380488',
 'SRR16155103',
 'SRR21925296',
 'ERR7001397',
 'SRR18848677',
 'SRR16175028',
 'SRR17971384',
 'SRR22740143',
 'SRR15140259',
 'SRR29147439',
 'SRR24427945',
 'ERR8192282',
 'ERR5501341',
 'SRR19466503',
 'SRR23979446',
 'ERR9975510',
 'SRR17138879',
 'SRR23980131',
 'SRR24429565',
 'SRR23979545',
 'SRR23907243',
 'SRR23408512',
 'ERR6545805',
 'SRR23979480',
 'SRR22572476',
 'SRR15542420',
 'ERR12160837',
 'SRR26069380',
 'SRR24428801',
 'SRR19602897',
 'SRR23138498',
 'SRR23980125',
 'SRR24427436',
 'SRR27365893',
 'SRR15024797',
 'ERR9226554',
 'SRR18151889',
 'SRR23979433',
 'ERR5509694',
 'SRR23979420',
 'SRR17006740',
 'SRR15035752',
 'SRR18613966',
 'ERR4645468',
 'SRR23979914',
 'SRR23979951',
 'SRR27365710',
 'SRR24428611',
 'SRR24124705',
 'SRR24427369',
 'SRR29433559',
 'SRR24428637',
 'SRR28334813',
 'SRR24427391',
 'SRR19532119',
 'SRR17871637',
 'SRR28347275',
 'ERR5746043',
 'SRR20209437',
 'SRR23979502',
 'SRR16075521',
 'SRR24427429',
 'SRR24428770',
 'ERR8194057',
 'SRR15709667',
 'SRR19807876',
 'SRR28813015',
 'ERR6633703',
 'ERR7004372',
 'SRR24427437',
 'SRR20661206',
 'SRR21563042',
 'SRR16839846',
 'SRR24427428',
 'SRR29433446',
 'SRR28557386',
 'SRR20190481',
 'SRR16127456',
 'ERR6343940',
 'SRR18704215',
 'ERR4597827',
 'SRR24603535',
 'SRR24427054',
 'SRR18152402',
 'SRR24427382',
 'SRR18310260',
 'SRR18971257',
 'SRR23980122',
 'SRR21022374',
 'SRR14400739',
 'SRR17211828',
 'ERR7718752',
 'SRR23676857',
 'SRR23318786',
 'SRR24428596',
 'ERR8176507',
 'SRR16579882',
 'SRR24428609',
 'SRR17444585',
 'SRR12879612',
 'SRR23980117',
 'ERR7235341',
 'SRR18666159',
 'SRR24427445',
 'SRR17611730',
 'SRR24427882',
 'SRR14712329',
 'SRR19156318',
 'SRR24428799',
 'SRR18152375',
 'SRR18666245',
 'SRR17889016',
 'SRR21093777',
 'SRR17477018',
 'SRR24428606',
 'ERR5514838',
 'ERR12533971',
 'SRR18687952',
 'SRR29049491',
 'SRR23045923',
 'ERR8409343',
 'SRR18152346',
 'SRR25440418',
 'SRR24990822',
 'SRR24427875',
 'SRR14401069',
 'SRR16003335',
 'SRR20779940',
 'SRR18688046',
 'SRR18820423',
 'ERR5439270',
 'SRR18703828',
 'SRR25191075',
 'SRR18038958',
 'SRR15289980',
 'SRR13644072',
 'SRR13129641',
 'ERR6021317',
 'ERR12163981',
 'SRR23253118',
 'SRR25066243',
 'SRR25693824',
 'ERR6720217',
 'SRR16291086',
 'ERR11967168',
 'SRR24583490',
 'ERR10933792',
 'ERR8172950',
 'SRR19570327',
 'SRR13368719',
 'SRR23046402',
 'ERR4866161',
 'SRR20202452',
 'SRR23079502',
 'ERR7834752',
 'SRR18151926',
 'SRR28557354',
 'ERR10015814',
 'SRR18688456',
 'SRR28334842',
 'SRR17435486',
 'SRR21132735',
 'ERR7941513',
 'ERR9510543',
 'SRR18688474',
 'SRR22559221',
 'SRR23273633',
 'ERR10017822',
 'SRR16928730',
 'ERR8246580',
 'SRR28516189',
 'SRR19156107',
 'SRR18241558',
 'SRR23625598',
 'SRR12751276',
 'SRR18425526',
 'SRR15552190',
 'SRR25440312',
 'SRR21389681',
 'SRR12973333',
 'SRR16175025',
 'SRR17860672',
 'ERR8498047',
 'SRR23979453',
 'SRR19466285',
 'SRR25871154',
 'SRR25053187',
 'SRR16162394',
 'SRR24635583',
 'SRR18140657',
 'SRR17836309',
 'SRR27366015',
 'SRR16710122',
 'SRR19942497',
 'SRR17138156',
 'ERR8983859',
 'SRR14119508',
 'SRR24993006',
 'SRR18688025',
 'SRR16104260',
 'SRR18665657',
 'SRR15516275',
 'SRR23079580',
 'SRR19258458',
 'SRR24883842',
 'SRR18688023',
 'SRR18666120',
 'SRR21139063',
 'ERR5758830',
 'ERR8173022',
 'SRR18666125',
 'ERR7152297',
 'SRR15514998',
 'ERR13086159',
 'SRR18539542',
 'ERR5504290',
 'SRR22910834',
 'SRR14657656',
 'SRR27387235',
 'SRR17885085',
 'ERR5780424',
 'ERR7012873',
 'SRR27828626',
 'ERR9981509',
 'ERR7013151',
 'ERR8250894',
 'SRR18688209',
 'ERR8980937',
 'SRR16604022',
 'ERR7427083',
 'ERR5747732',
 'SRR15035714',
 'SRR19755187',
 'SRR15975277',
 'SRR22020321',
 'SRR22470594',
 'SRR18124886',
 'SRR18211615',
 'ERR8516306',
 'SRR19993163',
 'SRR18666063',
 'SRR25694319',
 'ERR6063826',
 'SRR18688320',
 'ERR10365862',
 'ERR7762674',
 'SRR18665630',
 'SRR15513770',
 'SRR15916134',
 'SRR17253901',
 'SRR16851851',
 'ERR6622008',
 'ERR7802928',
 'ERR12792940',
 'SRR16781457',
 'SRR16127525',
 'ERR9275907',
 'SRR18152219',
 'SRR21158582',
 'SRR23381088',
 'SRR18665907',
 'SRR17918717',
 'SRR28334804',
 'SRR18666203',
 'SRR16857834',
 'ERR6768734',
 'SRR18666178',
 'ERR12476757',
 'ERR8256233',
 'SRR18688440',
 'SRR18687835',
 'ERR12373518',
 'SRR18152014',
 'ERR5505020',
 'SRR18688154',
 'ERR8236442',
 'SRR18919234',
 'SRR16884023',
 'SRR16205285',
 'SRR18688184',
 'SRR16710008',
 'ERR12155474',
 'ERR8977584',
 'ERR12115093',
 'SRR23462047',
 'SRR18687921',
 'ERR8165737',
 'SRR19600597',
 'SRR17753659',
 'SRR23381219',
 'ERR5633749',
 'SRR18742629',
 'ERR6072494',
 'SRR16022651',
 'SRR18688032',
 'SRR19461995',
 'SRR16087170',
 'SRR28397892',
 'SRR17022634',
 'ERR7444465',
 'ERR6619535',
 'SRR19051776',
 'ERR7891653',
 'SRR18665717',
 'SRR21198900',
 'SRR18848659',
 'SRR17018843',
 'SRR18613749',
 'SRR17846706',
 'SRR15659016',
 'SRR15149301',
 'SRR17350688',
 'ERR11828834',
 'ERR9118786',
 'SRR15268179',
 'ERR6116426',
 'SRR15572489',
 'ERR6719035',
 'SRR18666299',
 'SRR18666256',
 'SRR26828140',
 'SRR18839600',
 'ERR6714862',
 'SRR17324254',
 'SRR18688174',
 'SRR12836333',
 'SRR20423610',
 ...]

In [3]:
recomb_df = pd.read_csv("../data/recombinants.csv")
recomb_df

,recombinant,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,...,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,num_mns_left,mns_left,num_mns_right,mns_right
0,1438485,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,...,True,3,2,55,False,6,1,mnS1,1,MNM3
1,1540098,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,...,False,4,1,12,False,9,0,NaN,1,MNM3
2,752970,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,...,False,2,2,19,False,5,1,mnS1,0,NaN
3,1639593,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,...,False,3,0,12,False,6,0,NaN,1,MNM3
4,1798227,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,...,False,12,1,43,False,10,0,NaN,1,MNM3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1315,1750111,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,...,False,11,35,2,False,6,0,NaN,0,NaN
1316,1756402,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,...,False,13,36,2,False,7,0,NaN,0,NaN
1317,1556610,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,...,False,6,24,2,False,6,0,NaN,0,NaN
1318,1179998,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,...,False,4,62,1,False,5,1,mnS3,0,NaN
1319,1771531,ERR11006399,1,1,1,28704,29754,3,COVID-ARTIC-V4.1,.,...,True,11,48,1,False,7,1,MNM3,0,NaN

In [4]:
recomb_df[recomb_df.sample_id.isin(contam_samples)]

,recombinant,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,...,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,num_mns_left,mns_left,num_mns_right,mns_right
1,1540098,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,...,False,4,1,12,False,9,0,NaN,1,MNM3
3,1639593,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,...,False,3,0,12,False,6,0,NaN,1,MNM3
6,1502624,ERR9848224,7,1,1,695,1627,0,COVID-ARTIC-V4.1,.,...,False,3,1,8,False,8,0,NaN,0,NaN
9,1659458,ERR10306608,1,1,1,695,1931,1,COVID-ARTIC-V4.1,.,...,False,4,1,10,False,9,0,NaN,0,NaN
13,1501333,ERR9848047,65,1,1,1600,2790,3,COVID-ARTIC-V4.1,.,...,False,3,1,51,False,7,0,NaN,0,NaN
32,1664439,ERR10306538,2,1,1,695,5194,1,COVID-ARTIC-V4.1,.,...,False,1,0,6,False,7,0,NaN,0,NaN
41,1192767,ERR8572924,1,1,1,695,5672,1,COVID-ARTIC-V4.1,.,...,False,1,1,4,False,5,0,NaN,0,NaN
364,1889369,SRR28993025,1,1,1,21143,21610,0,COVID-ARTIC-V5.0-5.3.2_400,.,...,False,2,9,2,False,7,0,NaN,0,NaN
910,988526,SRR17901911,16,1,1,22205,22673,0,COVID-ARTIC-V3,.,...,False,1,6,4,True,5,0,NaN,0,NaN
947,1162100,SRR18978401,1,1,1,23014,23040,1,COVID-ARTIC-V3,.,...,False,2,13,7,True,7,0,NaN,0,NaN
950,1048238,SRR17510738,1,1,1,23041,23048,0,COVID-ARTIC-V3,.,...,False,1,10,4,True,4,0,NaN,0,NaN
1096,1613891,ERR10120291,1,1,1,17293,26491,1,COVID-ARTIC-V4.1,4.1alt,...,False,0,8,4,True,5,0,NaN,0,NaN
1229,361121,ERR6333468,1,1,1,27385,27875,0,COVID-ARTIC-V3,3,...,False,2,9,2,False,4,0,NaN,2,"MNM7,MNM7a"
1290,1790988,SRR24638789,6,3,1,29511,29571,1,COVID-ARTIC-V3,.,...,True,13,103,2,False,6,2,"MNM3,mnS3",0,NaN
1313,1818024,SRR25053154,1,1,1,28331,29733,1,COVID-MIDNIGHT-1200,.,...,True,10,46,4,True,10,1,MNM3,0,NaN

In [5]:
# QC-passing
recomb_df[recomb_df.sample_id.isin(contam_samples) & recomb_df.net_min_supporting_loci_lft_rgt_ge_4]

,recombinant,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,...,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,num_mns_left,mns_left,num_mns_right,mns_right
910,988526,SRR17901911,16,1,1,22205,22673,0,COVID-ARTIC-V3,.,...,False,1,6,4,True,5,0,NaN,0,NaN
947,1162100,SRR18978401,1,1,1,23014,23040,1,COVID-ARTIC-V3,.,...,False,2,13,7,True,7,0,NaN,0,NaN
950,1048238,SRR17510738,1,1,1,23041,23048,0,COVID-ARTIC-V3,.,...,False,1,10,4,True,4,0,NaN,0,NaN
1096,1613891,ERR10120291,1,1,1,17293,26491,1,COVID-ARTIC-V4.1,4.1alt,...,False,0,8,4,True,5,0,NaN,0,NaN
1313,1818024,SRR25053154,1,1,1,28331,29733,1,COVID-MIDNIGHT-1200,.,...,True,10,46,4,True,10,1,MNM3,0,NaN

In [6]:
# QC-failing
recomb_df[recomb_df.sample_id.isin(contam_samples) & ~recomb_df.net_min_supporting_loci_lft_rgt_ge_4]

,recombinant,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,...,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,num_mns_left,mns_left,num_mns_right,mns_right
1,1540098,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,...,False,4,1,12,False,9,0,NaN,1,MNM3
3,1639593,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,...,False,3,0,12,False,6,0,NaN,1,MNM3
6,1502624,ERR9848224,7,1,1,695,1627,0,COVID-ARTIC-V4.1,.,...,False,3,1,8,False,8,0,NaN,0,NaN
9,1659458,ERR10306608,1,1,1,695,1931,1,COVID-ARTIC-V4.1,.,...,False,4,1,10,False,9,0,NaN,0,NaN
13,1501333,ERR9848047,65,1,1,1600,2790,3,COVID-ARTIC-V4.1,.,...,False,3,1,51,False,7,0,NaN,0,NaN
32,1664439,ERR10306538,2,1,1,695,5194,1,COVID-ARTIC-V4.1,.,...,False,1,0,6,False,7,0,NaN,0,NaN
41,1192767,ERR8572924,1,1,1,695,5672,1,COVID-ARTIC-V4.1,.,...,False,1,1,4,False,5,0,NaN,0,NaN
364,1889369,SRR28993025,1,1,1,21143,21610,0,COVID-ARTIC-V5.0-5.3.2_400,.,...,False,2,9,2,False,7,0,NaN,0,NaN
1229,361121,ERR6333468,1,1,1,27385,27875,0,COVID-ARTIC-V3,3,...,False,2,9,2,False,4,0,NaN,2,"MNM7,MNM7a"
1290,1790988,SRR24638789,6,3,1,29511,29571,1,COVID-ARTIC-V3,.,...,True,13,103,2,False,6,2,"MNM3,mnS3",0,NaN