# Generate the table for displaying Pango X events

In [1]:

import numpy as np
import pandas as pd
import tszip
import sc2ts

In [2]:
ts = tszip.load("../data/sc2ts_viridian_v2.2.trees.tsz")
df_node = sc2ts.node_data(ts, inheritance_stats=False)

In [3]:
dfe = pd.read_csv("../data/pango_x_events.csv")
dfe

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,pango
0,1728703,XBS,3,R,19,{},1728703,0.0,0.000000,{'XBS': 19},XBS
1,1868714,XDP,0,R,100,"{'XEB': 5, 'JN.1.4': 3}",1868714,0.0,0.000000,"{'XDP': 62, 'XDP.1': 24, 'XDP.3': 13, 'XEB': 5...",XDP
2,1874983,XDP,0,R,28,"{'JN.1.4': 2, 'XEB': 4}",1874983,0.0,0.000000,"{'XDP': 18, 'XDP.1': 8, 'XEB': 4, 'JN.1.4': 2,...",XDP
3,1251095,XQ,1,R,58,"{'BA.2': 42, 'XR': 18, 'XAA': 22, 'XU': 1, 'XA...",1251095,0.0,0.000000,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",XQ
4,1834477,XCZ,3,R,6,{},1834477,0.0,0.000000,"{'XCZ': 6, 'XBB.1.9': 1}",XCZ
...,...,...,...,...,...,...,...,...,...,...,...
92,1073547,XH,3,S,40,{},1073548,1.0,8.000000,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",XH
93,1095085,XM,0,R,1,{'BA.1': 1},1095085,0.0,0.000000,"{'XM': 1, 'BA.1': 1}",XM
94,1178986,XM,0,R,31,"{'BA.2': 7, 'XAL': 14}",1178986,0.0,0.000000,"{'XM': 31, 'XAL': 14, 'BA.2': 7}",XM
95,1357484,XM,1,R,1,{},1357484,0.0,0.000000,{'XM': 1},XM
96,468298,XC,1,I,5,{},463545,1.0,19.876887,"{'XC': 5, 'B.1.617.2': 1}",XC

In [4]:
# Convert dictionaries to Python objects.
conv1 = {}
conv2 = {}
descendants = {}
for k, row in dfe.iterrows():
    conv1[k] = eval(row["closest_recombinant_descendants"])
    conv2[k] = eval(row["non_pango_samples"])
    descendants[k] = {row["pango"]: row["pango_samples"], **conv2[k]}
dfe["closest_recombinant_descendants"] = conv1
dfe["non_pango_samples"] = conv2
dfe["descendants"] = descendants

In [5]:
dfr = pd.read_csv("../data/recombinants.csv").set_index("recombinant")
dfr

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts
recombinant,,,,,,,,,,,,,,,,,,,,,
1438470,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,2022-04-15,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,True,3,2,55,False,6
1540083,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,2022-06-27,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,4,1,12,False,9
752955,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,2021-10-21,...,B.1.617.2,Delta (B.1.617.2-like),1268.244029,2020-12-16,False,2,2,19,False,5
1639578,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,2022-08-30,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,3,0,12,False,6
1798212,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,2023-03-20,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,12,1,43,False,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1556595,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,2022-07-06,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,6,24,2,False,6
1750096,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,2023-01-20,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,11,35,2,False,6
1756387,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,2023-01-30,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,False,13,36,2,False,7
1179983,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,2022-01-29,...,B.1,.,1591.661216,2020-01-28,False,4,62,1,False,5
1771516,ERR11006399,1,1,1,28704,29754,3,COVID-ARTIC-V4.1,.,2023-02-16,...,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12,True,11,48,1,False,7

In [6]:
dfr["mutations_averted"] = dfr["k1000_muts"] - dfr["num_mutations"]

In [7]:
dfe = dfe.join(dfr, "closest_recombinant")

## Outlier recombinants

In [8]:
df_pe = pd.read_csv("../data/pango_events_in_arg.csv").set_index("root")

In [9]:
dfr[dfr["num_descendant_samples"] > 5000]

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
recombinant,,,,,,,,,,,,,,,,,,,,,
1673437,SRR22255464,112220,10,1,22332,22577,14,COVID-ARTIC-V4.1,.,2022-09-29,...,Omicron (BA.2-like),961.384849,2021-10-19,True,6,13,10,True,21,7
1428716,SRR21340546,244601,11,2,23041,26858,4,COVID-ARTIC-V4.1,.,2022-04-09,...,Omicron (BA.2-like),961.384849,2021-10-19,False,2,6,5,True,9,5
1213517,ERR8619597,244192,1,1,26859,27382,0,COVID-ARTIC-V4.1,4.1alt,2022-02-05,...,Omicron (Unassigned),1333.857513,2020-10-12,False,4,46,3,False,5,5

In [10]:
outliers = dfr[dfr["num_descendant_samples"] > 5000].index
for u in outliers:
    if u in df_pe.index:
        print(u, df_pe.loc[u]["pango"])

1673437 XBB
1428716 BA.5

In [60]:
dfe[dfe["num_descendant_samples"] > 5000]

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
17,1673437,XBB,15,R,112005,"{'BQ.1.1.13': 2, 'JN.1.1': 11, 'JN.3': 1, 'JN....",1673437,0.0,0.000000,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
38,1841699,XDF,6,S,1,{},1673437,12.0,481.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
41,1814205,XBL,5,I,13,{},1673437,5.0,189.868325,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
63,1814047,XDB,7,S,1,{},1673437,11.0,334.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
64,1814888,XDB,2,S,12,{},1673437,11.0,337.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
76,1711075,XBZ,4,S,165,{},1428716,16.0,265.000001,{'too_many_to_classify': 244541},...,Omicron (BA.2-like),961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0
82,1525011,XAV,3,S,13,{},1428716,7.0,106.000001,{'too_many_to_classify': 244541},...,Omicron (BA.2-like),961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0

So, the nodes we need to keep track of as closest recombinants that may not really be recombinants are the XBB root and BA.5 root.

In [21]:
xbb_root = 1673437
ba5_root = 1428716

## Number of pango X lineages in the ARG

In [11]:
all_x_events = dfe["root_pango"].unique()
all_x_events

<StringArray>
[       'XBS',        'XDP',         'XQ',        'XCZ',        'XCL',
         'XL',         'XG',        'XBF',        'XCC',        'XCP',
        'XAC',        'XAA',         'XW',        'XBB',      'XBB.1',
        'XBV',    'XBB.1.5', 'XBB.1.5.16',    'XBB.2.3',        'XCE',
 'XBB.1.16.4',  'XBC.1.2.1',        'XBM',         'XN',        'XDF',
        'XCY',        'XBG',        'XBL',        'XAM',         'XZ',
        'XAS',        'XBD',         'XE',      'XDV.1',         'XB',
        'XAP',        'XAE',         'XU',        'XDA',         'XS',
        'XAJ',        'XBR',        'XBK',         'XV',        'XAU',
        'XAZ',        'XBH',        'XDY',        'XDB',        'XBQ',
        'XDD',        'XDR',        'XAN',         'XF',        'XAG',
        'XBW',        'XAL',        'XBE',        'XAB',        'XCH',
        'XBZ',        'XAD',      'XAY.2',         'XY',        'XCT',
        'XAV',        'XCQ',        'XCF',        'XCR',         'XR',
         'XA',         'XP',         'XJ',        'XDK',         'XH',
         'XM',         'XC']
Length: 77, dtype: str

In [10]:
len(all_x_events)

77

In [12]:
xs = [x for x in df_node.pango.unique() if x.startswith("X") and "." not in x]
len(xs)

70

# Subset to single-origin events

Exclude events which are non single origin for the given pango lineage. These will need to be analysed separately.

In [13]:
counts = dfe["root_pango"].value_counts() 
multiple = counts[counts > 1]
multiple

root_pango
XBB.1.5    5
XDP        4
XAC        4
XBB.1      4
XM         3
XCC        2
XBV        2
XCE        2
XAP        2
XDB        2
Name: count, dtype: int64

In [14]:
dfe[dfe["root_pango"].isin(multiple.index)]

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
1,1868714,XDP,0,R,100,"{'XEB': 5, 'JN.1.4': 3}",1868714,0.0,0.000000,"{'XDP': 62, 'XDP.1': 24, 'XDP.3': 13, 'XEB': 5...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,71.0,6.0,True,7.0,6.0
2,1874983,XDP,0,R,28,"{'JN.1.4': 2, 'XEB': 4}",1874983,0.0,0.000000,"{'XDP': 18, 'XDP.1': 8, 'XEB': 4, 'JN.1.4': 2,...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,67.0,6.0,True,5.0,5.0
9,1766388,XCC,0,R,15,{},1766388,0.0,0.000000,{'XCC': 15},...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,9.0,28.0,True,10.0,9.0
11,1462028,XAC,1,I,8,{},1448913,2.0,30.438818,{'XAC': 19},...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,45.0,4.0,True,7.0,4.0
12,1488108,XAC,2,I,9,{},1448913,2.0,71.979366,{'XAC': 19},...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,45.0,4.0,True,7.0,4.0
13,1448912,XAC,2,S,1,{},1448913,2.0,80.019366,{'XAC': 19},...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,45.0,4.0,True,7.0,4.0
14,1478564,XAC,1,S,1,{},1448913,2.0,100.019366,{'XAC': 19},...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,45.0,4.0,True,7.0,4.0
18,1740122,XBB.1,0,R,1,{},1740122,0.0,0.000000,{'XBB.1': 1},...,Omicron (BA.2-like),961.384849,2021-10-19,True,10.0,6.0,29.0,True,6.0,6.0
19,1766388,XCC,0,R,15,{},1766388,0.0,0.000000,{'XCC': 15},...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,9.0,28.0,True,10.0,9.0
20,1719442,XBV,3,R,3,{},1719442,0.0,0.000000,"{'XBV': 3, 'XBB.1': 1}",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,14.0,25.0,True,17.0,14.0
21,1741937,XBB.1,0,R,1,{},1741937,0.0,0.000000,{'XBB.1': 1},...,Omicron (BA.5-like),828.000001,2022-03-01,True,11.0,12.0,30.0,True,12.0,12.0
22,1750864,XBB.1,1,R,4,{},1750864,0.0,0.000000,{'XBB.1': 4},...,Omicron (BA.2-like),961.384849,2021-10-19,True,15.0,20.0,27.0,True,6.0,5.0
23,1764888,XBB.1.5,0,R,2,{},1764888,0.0,0.000000,"{'XBB.1.5.49': 1, 'XBB.1.5': 1}",...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,4.0,38.0,True,4.0,4.0
24,1752088,XBB.1.5,2,R,7,{},1752088,0.0,0.000000,{'XBB.1.5': 7},...,Omicron (BA.2-like),961.384849,2021-10-19,True,15.0,6.0,37.0,True,6.0,4.0
26,1787791,XBB.1.5,3,R,1,{},1787791,0.0,0.000000,{'XBB.1.5': 1},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,0.0,31.0,False,8.0,5.0
27,1782627,XBB.1.5,2,R,2,{},1782627,0.0,0.000000,{'XBB.1.5': 2},...,Omicron (BA.2-like),961.384849,2021-10-19,True,14.0,5.0,42.0,True,6.0,4.0
29,1793239,XBB.1.5,3,R,5,{},1793239,0.0,0.000000,{'XBB.1.5': 5},...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,5.0,38.0,True,7.0,4.0
30,1804167,XBB.1,3,R,1,{},1804167,0.0,0.000000,{'XBB.1': 1},...,Omicron (BA.2-like),961.384849,2021-10-19,True,15.0,12.0,37.0,True,14.0,11.0
31,1818894,XCE,2,R,1,{},1818894,0.0,0.000000,{'XCE': 1},...,Omicron (BA.2-like),961.384849,2021-10-19,True,17.0,4.0,43.0,True,6.0,4.0
33,1868714,XDP,0,R,105,{'JN.1.4': 3},1868714,0.0,0.000000,"{'XDP': 62, 'XDP.1': 24, 'XDP.3': 13, 'XEB': 5...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,71.0,6.0,True,7.0,6.0
34,1874983,XDP,0,R,32,{'JN.1.4': 2},1874983,0.0,0.000000,"{'XDP': 18, 'XDP.1': 8, 'XEB': 4, 'JN.1.4': 2,...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,67.0,6.0,True,5.0,5.0
49,1447906,XAP,1,I,17,{},1133051,3.0,50.446317,"{'BA.2': 218, 'XZ': 51, 'XAP': 21}",...,Omicron (Unassigned),1333.857513,2020-10-12,False,4.0,43.0,5.0,True,7.0,7.0
50,1455454,XAP,1,S,4,{},1133051,4.0,98.000000,"{'BA.2': 218, 'XZ': 51, 'XAP': 21}",...,Omicron (Unassigned),1333.857513,2020-10-12,False,4.0,43.0,5.0,True,7.0,7.0
63,1814047,XDB,7,S,1,{},1673437,11.0,334.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
64,1814888,XDB,2,S,12,{},1673437,11.0,337.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
78,1818894,XCE,2,R,1,{},1818894,0.0,0.000000,{'XCE': 1},...,Omicron (BA.2-like),961.384849,2021-10-19,True,17.0,4.0,43.0,True,6.0,4.0
89,1719442,XBV,3,R,3,{},1719442,0.0,0.000000,"{'XBV': 3, 'XBB.1': 1}",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,14.0,25.0,True,17.0,14.0
93,1095085,XM,0,R,1,{'BA.1': 1},1095085,0.0,0.000000,"{'XM': 1, 'BA.1': 1}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,30.0,15.0,True,30.0,30.0
94,1178986,XM,0,R,31,"{'BA.2': 7, 'XAL': 14}",1178986,0.0,0.000000,"{'XM': 31, 'XAL': 14, 'BA.2': 7}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,25.0,23.0,True,9.0,8.0
95,1357484,XM,1,R,1,{},1357484,0.0,0.000000,{'XM': 1},...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,29.0,21.0,True,5.0,4.0

In [14]:
dfe[dfe["root_pango"].isin(multiple.index)]["pango_samples"].sum()

np.int64(413)

In the v1 analysis we added in specific events as there was only 26 samples for multiple events, and XM/XAC/XAD accounted for most. For now we just exclude all multiples.

In [15]:
#pango_events_tbl = dfe[~dfe["root_pango"].isin(["XM", "XAC", "XAD"])]
#pango_events_tbl = pd.concat([pango_events_tbl, dfe[dfe["root"] == 1003220]]).copy()
pango_events_tbl = dfe[~dfe["root_pango"].isin(multiple.index)]
pango_events_tbl

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
0,1728703,XBS,3,R,19,{},1728703,0.0,0.000000,{'XBS': 19},...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,21.0,21.0,True,23.0,20.0
3,1251095,XQ,1,R,58,"{'BA.2': 42, 'XR': 18, 'XAA': 22, 'XU': 1, 'XA...",1251095,0.0,0.000000,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
4,1834477,XCZ,3,R,6,{},1834477,0.0,0.000000,"{'XCZ': 6, 'XBB.1.9': 1}",...,Omicron (XBB.1-like),695.299735,2022-07-12,True,9.0,13.0,16.0,True,16.0,13.0
5,1836320,XCL,1,R,22,{},1836320,0.0,0.000000,{'XCL': 22},...,Omicron (XBB.1.5-like),637.061153,2022-09-08,True,3.0,8.0,9.0,True,11.0,8.0
6,1218637,XL,1,R,67,{},1218637,0.0,0.000000,{'XL': 67},...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,10.0,40.0,True,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1291412,XP,1,S,48,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,1133210,XJ,1,R,71,{'BA.2': 3},1133210,0.0,0.000000,"{'XJ': 71, 'BA.2': 3}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,21.0,29.0,True,7.0,6.0
91,1871605,XDK,0,R,84,{},1871605,0.0,0.000000,"{'XDK': 47, 'XDK.1': 12, 'XDK.5': 9, 'XDK.4.1'...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,6.0,70.0,True,9.0,6.0
92,1073547,XH,3,S,40,{},1073548,1.0,8.000000,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,14.0,36.0,True,16.0,13.0
96,468298,XC,1,I,5,{},463545,1.0,19.876887,"{'XC': 5, 'B.1.617.2': 1}",...,.,1591.661216,2020-01-28,True,5.0,40.0,15.0,True,37.0,36.0

In [16]:
sorted(list(pango_events_tbl["root_pango"]))

['XA',
 'XAA',
 'XAB',
 'XAD',
 'XAE',
 'XAG',
 'XAJ',
 'XAL',
 'XAM',
 'XAN',
 'XAS',
 'XAU',
 'XAV',
 'XAY.2',
 'XAZ',
 'XB',
 'XBB',
 'XBB.1.16.4',
 'XBB.1.5.16',
 'XBB.2.3',
 'XBC.1.2.1',
 'XBD',
 'XBE',
 'XBF',
 'XBG',
 'XBH',
 'XBK',
 'XBL',
 'XBM',
 'XBQ',
 'XBR',
 'XBS',
 'XBW',
 'XBZ',
 'XC',
 'XCF',
 'XCH',
 'XCL',
 'XCP',
 'XCQ',
 'XCR',
 'XCT',
 'XCY',
 'XCZ',
 'XDA',
 'XDD',
 'XDF',
 'XDK',
 'XDR',
 'XDV.1',
 'XDY',
 'XE',
 'XF',
 'XG',
 'XH',
 'XJ',
 'XL',
 'XN',
 'XP',
 'XQ',
 'XR',
 'XS',
 'XU',
 'XV',
 'XW',
 'XY',
 'XZ']

Also remove the derived "." lineages

In [17]:
derived_lins = [x for x in list(pango_events_tbl["root_pango"]) if "." in x]
derived_lins

['XBB.1.5.16', 'XBB.2.3', 'XBB.1.16.4', 'XBC.1.2.1', 'XDV.1', 'XAY.2']

In [18]:
pango_events_tbl = pango_events_tbl[~(pango_events_tbl["root_pango"].isin(derived_lins))].copy()
pango_events_tbl.shape[0]

61

We're left with 61 lineages/events

# Assigning types to each event

In [25]:
type_1_row = pango_events_tbl["root_type"] == "R"
pango_events_tbl.loc[type_1_row, "type"] = 1

type_4_row = (
    pango_events_tbl["closest_recombinant"].isin([-1, xbb_root, ba5_root]) & 
    (pango_events_tbl["closest_recombinant_path_len"] > 3)
)
pango_events_tbl.loc[type_4_row, "type"] = 4

unclassified = set(pango_events_tbl[pango_events_tbl["type"].isnull()]["closest_recombinant"])
unclassified

{242304, 463545, 1073548, 1093814, 1133051, 1178986, 1251095, 1767510}

In [26]:
xb_root = 242304

unclassified = list(unclassified - {xb_root, ba5_root, xbb_root})
unclassified

[1178986, 1073548, 1251095, 1767510, 1093814, 463545, 1133051]

In [27]:
pango_events_tbl[pango_events_tbl["closest_recombinant"].isin(unclassified)].sort_values("closest_recombinant")

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted,type
96,468298,XC,1,I,5,{},463545,1.0,19.876887,"{'XC': 5, 'B.1.617.2': 1}",...,1591.661216,2020-01-28,True,5.0,40.0,15.0,True,37.0,36.0,NaN
46,1129760,XE,4,I,1256,{},1073548,2.0,9.456944,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",...,1333.857513,2020-10-12,True,3.0,14.0,36.0,True,16.0,13.0,NaN
92,1073547,XH,3,S,40,{},1073548,1.0,8.000000,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",...,1333.857513,2020-10-12,True,3.0,14.0,36.0,True,16.0,13.0,NaN
7,1117665,XG,3,I,159,{},1093814,3.0,5.781627,"{'XG': 159, 'BA.2': 11}",...,1333.857513,2020-10-12,True,4.0,8.0,41.0,True,7.0,7.0,NaN
43,1380286,XZ,1,I,51,{},1133051,4.0,52.000000,"{'BA.2': 218, 'XZ': 51, 'XAP': 21}",...,1333.857513,2020-10-12,False,4.0,43.0,5.0,True,7.0,7.0,NaN
72,1502277,XAL,2,I,14,{},1178986,4.0,70.756330,"{'XM': 31, 'XAL': 14, 'BA.2': 7}",...,1333.857513,2020-10-12,True,3.0,25.0,23.0,True,9.0,8.0,NaN
42,1477814,XAM,3,I,26,{},1251095,7.0,27.724456,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
3,1251095,XQ,1,R,58,"{'BA.2': 42, 'XR': 18, 'XAA': 22, 'XU': 1, 'XA...",1251095,0.0,0.000000,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,1.0
70,1486589,XAG,4,I,17,{},1251095,7.0,44.031003,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
52,1489437,XU,13,S,1,{},1251095,7.0,113.724456,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
15,1406886,XAA,3,I,22,{},1251095,7.0,43.724456,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
74,1480504,XAB,1,I,3,{},1251095,7.0,42.022492,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
86,1361112,XR,4,I,18,{'BA.2': 1},1251095,4.0,21.724456,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0,NaN
84,1821991,XCF,5,I,45,{},1767510,4.0,23.179691,"{'XCF': 38, 'XBB.1.5': 6, 'XCF.3': 6, 'XCF.1':...",...,1333.857513,2020-10-12,True,5.0,25.0,1.0,False,5.0,4.0,NaN

In [35]:
event_synonyms = {
    463545: "XC?",
    1073548: "XE/XH",
    1093814: "XG?",
    1133051: "XZ?",
    1178986: "XAL?",
    1251095: "XQ",
    1767510: "XCF",
}
assert set(event_synonyms.keys()) == set(unclassified)

In [36]:
set(event_synonyms.keys()), set(unclassified)

({463545, 1073548, 1093814, 1133051, 1178986, 1251095, 1767510},
 {463545, 1073548, 1093814, 1133051, 1178986, 1251095, 1767510})

In [37]:
type_3_row = (
   pango_events_tbl["type"].isnull()
)
pango_events_tbl.loc[type_3_row, "type"] = 3

# Formatting the table

In [38]:

def format_parent_col(df_in, parent_col, pango_col):
    parent_pango = {}
    for k, row in df_in.iterrows():
        
        focal = int(row["root"])
        parent = row[parent_col]
        if parent == -1 or np.isnan(parent):
            continue
        parent = int(parent)
        node_row = df_node.loc[parent]
        pango = node_row["pango"]
        #print(row)
        #print(node_row)
        if node_row["is_sample"]:
            is_sample = True
        else:
            children = list(ts.edges_child[ts.edges_parent == parent])
            if focal in children:
                children.remove(focal)
            df = df_node.loc[children]
            is_sample = np.any(df["is_sample"] & (df["num_mutations"] == 0))
        if is_sample:
            parent_pango[k] = "\\textbf{" + pango + "}"
        else:
            parent_pango[k] = pango
    df_in[pango_col] = parent_pango

In [39]:
format_parent_col(pango_events_tbl, "parent_left", "parent_left_pango")
format_parent_col(pango_events_tbl, "parent_right", "parent_right_pango")

## Type I

In [44]:
col_name_map = {
    "root_pango": "pango",
    "mutations_averted": "averted",
    "parent_left_pango": "left p",
    "parent_right_pango": "right p",
    "interval_left": "left",
    "interval_right": "right",
    "descendants": "descendants",
    #"pango_samples": "samples", 
    #"non_pango_samples": "nested",
}
type_1_events = pango_events_tbl[pango_events_tbl["type"] == 1].copy()
type_1_events = type_1_events.sort_values("mutations_averted", ascending=False)
type_1_events[list(col_name_map.keys())]

,root_pango,mutations_averted,parent_left_pango,parent_right_pango,interval_left,interval_right,descendants
66,XDD,67.0,JN.1.1,EG.5.1.1,25700.0,26275.0,{'XDD': 112}
81,XCT,26.0,\textbf{JG.4},DV.7.1,18584.0,19326.0,{'XCT': 57}
56,XBR,24.0,\textbf{BN.3.1},\textbf{BQ.1.25},22034.0,22190.0,{'XBR': 3}
0,XBS,20.0,BY.1,\textbf{BQ.1.1},22034.0,22190.0,{'XBS': 19}
87,XA,19.0,\textbf{B.1.177.18},\textbf{B.1.1.7},21256.0,21765.0,{'XA': 39}
54,XS,13.0,AY.103,\textbf{BA.1.1},9054.0,10449.0,{'XS': 19}
4,XCZ,13.0,\textbf{EG.5.1.1},GK.1.1,18493.0,21718.0,{'XCZ': 6}
85,XCR,10.0,GK.1.1,FU.1.1,23674.0,25045.0,"{'XCR': 84, 'XBB.1.5.70': 1}"
39,XCY,10.0,\textbf{EG.5.1.3},GK.3.1,21719.0,22480.0,{'XCY': 1}
10,XCP,9.0,\textbf{EG.5.1.10},\textbf{JD.1.1},14190.0,14634.0,{'XCP': 40}
40,XBG,9.0,\textbf{BA.2.76},\textbf{BA.5.2},22600.0,22917.0,{'XBG': 31}
5,XCL,8.0,\textbf{XBB.1.5},GK.2.1,12468.0,15755.0,{'XCL': 22}
36,XBM,8.0,\textbf{BA.2.76},\textbf{BF.3},22787.0,22882.0,{'XBM': 21}
45,XBD,8.0,\textbf{BA.2.75.2},\textbf{BA.5.2.1},23020.0,24620.0,{'XBD': 46}
17,XBB,7.0,\textbf{BA.2.10},BM.1.1.1,22332.0,22577.0,"{'XBB': 112005, 'BQ.1.1.13': 2, 'JN.1.1': 11, ..."
8,XBF,7.0,\textbf{BA.5.2.1},CJ.1,5184.0,9866.0,{'XBF': 832}
91,XDK,6.0,\textbf{XBB.1.5},\textbf{JN.1.1.1},5315.0,6183.0,{'XDK': 84}
61,XBH,6.0,\textbf{BA.2},BA.2.75.2,15452.0,22016.0,{'XBH': 7}
71,XBW,6.0,\textbf{XBB.1.5.107},BQ.1.1,25417.0,26275.0,{'XBW': 5}
90,XJ,6.0,\textbf{BA.1.17.2},\textbf{BA.2},13196.0,15240.0,"{'XJ': 71, 'BA.2': 3}"
69,XF,5.0,\textbf{AY.4},\textbf{BA.1.16},5387.0,6402.0,{'XF': 18}
77,XAD,5.0,\textbf{BA.2},\textbf{BA.1.1},26061.0,26530.0,{'XAD': 2}
67,XDR,5.0,\textbf{JN.1.1},JN.1.1,11043.0,11727.0,{'XDR': 6}
68,XAN,5.0,\textbf{BA.2},\textbf{BA.5.1.23},17823.0,19862.0,{'XAN': 26}
51,XAE,5.0,\textbf{BA.2},BA.1.1,24504.0,26060.0,{'XAE': 10}
3,XQ,4.0,BA.1.1.15,\textbf{BA.2.5},4322.0,5386.0,"{'XQ': 58, 'BA.2': 42, 'XR': 18, 'XAA': 22, 'X..."
16,XW,4.0,BA.1.1.2,\textbf{BA.2},2833.0,4321.0,"{'XW': 37, 'BA.2': 3}"
6,XL,4.0,\textbf{BA.1.17.2},\textbf{BA.2.5},5925.0,8393.0,{'XL': 67}
83,XCQ,4.0,\textbf{XBB.2.3.15},XBB.1.5.15,23124.0,23757.0,{'XCQ': 8}
60,XAZ,4.0,\textbf{BA.2.5},\textbf{BA.5},3359.0,9866.0,{'XAZ': 212}
58,XV,4.0,\textbf{BA.1},\textbf{BA.2},13196.0,15240.0,{'XV': 9}
62,XDY,4.0,\textbf{LB.1.2.1},KP.3.2,22132.0,22599.0,{'XDY': 3}
80,XY,4.0,\textbf{BA.1.1},\textbf{BA.2},11538.0,12880.0,{'XY': 23}
73,XBE,4.0,\textbf{BA.5.2.6},\textbf{BE.4},22600.0,27012.0,{'XBE': 74}
53,XDA,3.0,\textbf{XBB.1.16.20},HN.5,22102.0,22928.0,{'XDA': 105}
75,XCH,3.0,GK.1,\textbf{FY.2},23674.0,25045.0,{'XCH': 155}

In [45]:
s = type_1_events[list(col_name_map.keys())].to_latex(
        escape=False, index=False, header=list(col_name_map.values()),
        float_format="%.0f")
s = s.replace("'", "").replace(": ", ":")
#s = s.replace("{BA.2:37, XR:17, XAA:17, XU:1, XAM:21, XAG:6\}", "{BA.2:37, $\star$\}")
print(s)

\begin{tabular}{lrllrrl}
\toprule
pango & averted & left p & right p & left & right & descendants \\
\midrule
XDD & 67 & JN.1.1 & EG.5.1.1 & 25700 & 26275 & {XDD:112} \\
XCT & 26 & \textbf{JG.4} & DV.7.1 & 18584 & 19326 & {XCT:57} \\
XBR & 24 & \textbf{BN.3.1} & \textbf{BQ.1.25} & 22034 & 22190 & {XBR:3} \\
XBS & 20 & BY.1 & \textbf{BQ.1.1} & 22034 & 22190 & {XBS:19} \\
XA & 19 & \textbf{B.1.177.18} & \textbf{B.1.1.7} & 21256 & 21765 & {XA:39} \\
XS & 13 & AY.103 & \textbf{BA.1.1} & 9054 & 10449 & {XS:19} \\
XCZ & 13 & \textbf{EG.5.1.1} & GK.1.1 & 18493 & 21718 & {XCZ:6} \\
XCR & 10 & GK.1.1 & FU.1.1 & 23674 & 25045 & {XCR:84, XBB.1.5.70:1} \\
XCY & 10 & \textbf{EG.5.1.3} & GK.3.1 & 21719 & 22480 & {XCY:1} \\
XCP & 9 & \textbf{EG.5.1.10} & \textbf{JD.1.1} & 14190 & 14634 & {XCP:40} \\
XBG & 9 & \textbf{BA.2.76} & \textbf{BA.5.2} & 22600 & 22917 & {XBG:31} \\
XCL & 8 & \textbf{XBB.1.5} & GK.2.1 & 12468 & 15755 & {XCL:22} \\
XBM & 8 & \textbf{BA.2.76} & \textbf{BF.3} & 22787 & 22882 & {XBM:21} \\
XBD & 8 & \textbf{BA.2.75.2} & \textbf{BA.5.2.1} & 23020 & 24620 & {XBD:46} \\
XBB & 7 & \textbf{BA.2.10} & BM.1.1.1 & 22332 & 22577 & {XBB:112005, BQ.1.1.13:2, JN.1.1:11, JN.3:1, JN.18:1, BA.2:1} \\
XBF & 7 & \textbf{BA.5.2.1} & CJ.1 & 5184 & 9866 & {XBF:832} \\
XDK & 6 & \textbf{XBB.1.5} & \textbf{JN.1.1.1} & 5315 & 6183 & {XDK:84} \\
XBH & 6 & \textbf{BA.2} & BA.2.75.2 & 15452 & 22016 & {XBH:7} \\
XBW & 6 & \textbf{XBB.1.5.107} & BQ.1.1 & 25417 & 26275 & {XBW:5} \\
XJ & 6 & \textbf{BA.1.17.2} & \textbf{BA.2} & 13196 & 15240 & {XJ:71, BA.2:3} \\
XF & 5 & \textbf{AY.4} & \textbf{BA.1.16} & 5387 & 6402 & {XF:18} \\
XAD & 5 & \textbf{BA.2} & \textbf{BA.1.1} & 26061 & 26530 & {XAD:2} \\
XDR & 5 & \textbf{JN.1.1} & JN.1.1 & 11043 & 11727 & {XDR:6} \\
XAN & 5 & \textbf{BA.2} & \textbf{BA.5.1.23} & 17823 & 19862 & {XAN:26} \\
XAE & 5 & \textbf{BA.2} & BA.1.1 & 24504 & 26060 & {XAE:10} \\
XQ & 4 & BA.1.1.15 & \textbf{BA.2.5} & 4322 & 5386 & {XQ:58, BA.2:42, XR:18, XAA:22, XU:1, XAM:26, XAB:3, XAG:17} \\
XW & 4 & BA.1.1.2 & \textbf{BA.2} & 2833 & 4321 & {XW:37, BA.2:3} \\
XL & 4 & \textbf{BA.1.17.2} & \textbf{BA.2.5} & 5925 & 8393 & {XL:67} \\
XCQ & 4 & \textbf{XBB.2.3.15} & XBB.1.5.15 & 23124 & 23757 & {XCQ:8} \\
XAZ & 4 & \textbf{BA.2.5} & \textbf{BA.5} & 3359 & 9866 & {XAZ:212} \\
XV & 4 & \textbf{BA.1} & \textbf{BA.2} & 13196 & 15240 & {XV:9} \\
XDY & 4 & \textbf{LB.1.2.1} & KP.3.2 & 22132 & 22599 & {XDY:3} \\
XY & 4 & \textbf{BA.1.1} & \textbf{BA.2} & 11538 & 12880 & {XY:23} \\
XBE & 4 & \textbf{BA.5.2.6} & \textbf{BE.4} & 22600 & 27012 & {XBE:74} \\
XDA & 3 & \textbf{XBB.1.16.20} & HN.5 & 22102 & 22928 & {XDA:105} \\
XCH & 3 & GK.1 & \textbf{FY.2} & 23674 & 25045 & {XCH:155} \\
\bottomrule
\end{tabular}

## Type IV events

In [47]:
type_4_events = pango_events_tbl[pango_events_tbl["type"] == 4].copy()
type_4_events = type_4_events.sort_values(["root_mutations", "root_pango"], ascending=True)
type_4_events

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted,type
44,1518721,XAS,1,S,84,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
59,1472899,XAU,1,S,9,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
57,1725053,XBK,1,I,178,{'CJ.1': 1},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
65,1733651,XBQ,1,I,36,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
37,1253868,XN,1,S,141,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
88,1291412,XP,1,S,48,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
82,1525011,XAV,3,S,13,{},1428716,7.0,106.000001,{'too_many_to_classify': 244541},...,961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0,4.0
76,1711075,XBZ,4,S,165,{},1428716,16.0,265.000001,{'too_many_to_classify': 244541},...,961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0,4.0
41,1814205,XBL,5,I,13,{},1673437,5.0,189.868325,{'too_many_to_classify': 112021},...,961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0,4.0
38,1841699,XDF,6,S,1,{},1673437,12.0,481.558324,{'too_many_to_classify': 112021},...,961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0,4.0
55,1534989,XAJ,11,I,21,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0

In [79]:
xbb_root, ba5_root

(1673437, 1428716)

In [50]:
tree = ts.first()
root_parent = {}
root_parent_pango = {}
for k, row in type_4_events.iterrows():  
    u = tree.parent_array[row["root"]]
    root_parent[k] = u
    root_parent_pango[k] = df_node.loc[u, "pango"]

type_4_events["root_parent"] = root_parent
type_4_events["root_parent_pango"] = root_parent_pango
format_parent_col(type_4_events, "root_parent", "root_parent_pango")

In [51]:
col_name_map = {
    "root_pango": "pango",
    "root_mutations": "mutations",
    "root_parent_pango": "parent",
    #"parent_is_observed_sample": "parent sample",
    "descendants": "descendants",
    #"closest_recombinant_descendants": "by pango",
}

type_4_events[list(col_name_map.keys())]

   root_pango  root_mutations root_parent_pango              descendants
44        XAS               1              BA.4              {'XAS': 84}
59        XAU               1              BA.2               {'XAU': 9}
57        XBK               1              CJ.1  {'XBK': 178, 'CJ.1': 1}
65        XBQ               1              CJ.1              {'XBQ': 36}
37         XN               1     \textbf{BA.2}              {'XN': 141}
88         XP               1   \textbf{BA.1.1}               {'XP': 48}
82        XAV               3         BA.5.1.24              {'XAV': 13}
76        XBZ               4     \textbf{EF.1}             {'XBZ': 165}
41        XBL               5        XBB.1.5.57              {'XBL': 13}
38        XDF               6            EG.5.1               {'XDF': 1}
55        XAJ              11  \textbf{BA.2.12}              {'XAJ': 21}

In [90]:
list(type_4_events["root_pango"])

['XAS', 'XAU', 'XBK', 'XBQ', 'XN', 'XP', 'XAV', 'XBZ', 'XBL', 'XDF', 'XAJ']

In [52]:
s = type_4_events[list(col_name_map.keys())].to_latex(
        escape=False, index=False, header=list(col_name_map.values()),
        float_format="%.0f")
s = s.replace("'", "").replace(": ", ":")
print(s)

\begin{tabular}{lrll}
\toprule
pango & mutations & parent & descendants \\
\midrule
XAS & 1 & BA.4 & {XAS:84} \\
XAU & 1 & BA.2 & {XAU:9} \\
XBK & 1 & CJ.1 & {XBK:178, CJ.1:1} \\
XBQ & 1 & CJ.1 & {XBQ:36} \\
XN & 1 & \textbf{BA.2} & {XN:141} \\
XP & 1 & \textbf{BA.1.1} & {XP:48} \\
XAV & 3 & BA.5.1.24 & {XAV:13} \\
XBZ & 4 & \textbf{EF.1} & {XBZ:165} \\
XBL & 5 & XBB.1.5.57 & {XBL:13} \\
XDF & 6 & EG.5.1 & {XDF:1} \\
XAJ & 11 & \textbf{BA.2.12} & {XAJ:21} \\
\bottomrule
\end{tabular}

# OLD Examine nested BA.2 samples

In [24]:
df_nested = pango_events_tbl[pango_events_tbl["non_pango_samples"] != {}]
df_nested

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
3,1251095,XQ,1,R,58,"{'BA.2': 42, 'XR': 18, 'XAA': 22, 'XU': 1, 'XA...",1251095,0.0,0.000000,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
16,1375030,XW,1,R,37,{'BA.2': 3},1375030,0.0,0.000000,"{'XW': 37, 'BA.2': 3}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,4.0,44.0,True,5.0,4.0
17,1673437,XBB,15,R,112005,"{'BQ.1.1.13': 2, 'JN.1.1': 11, 'JN.3': 1, 'JN....",1673437,0.0,0.000000,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
57,1725053,XBK,1,I,178,{'CJ.1': 1},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,1833719,XCR,2,R,84,{'XBB.1.5.70': 1},1833719,0.0,0.000000,"{'XCR': 84, 'XBB.1.5.70': 1}",...,Omicron (XBB.1-like),695.299735,2022-07-12,True,8.0,18.0,11.0,True,12.0,10.0
86,1361112,XR,4,I,18,{'BA.2': 1},1251095,4.0,21.724456,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
90,1133210,XJ,1,R,71,{'BA.2': 3},1133210,0.0,0.000000,"{'XJ': 71, 'BA.2': 3}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,21.0,29.0,True,7.0,6.0

## Cells left over from v1

These cells are based on same old assumptions about non X lineages being BA.2, but this isn't reasonable any more. 

Keeping for now in case we want similar logic later on.

In [25]:
# All the nested samples are either BA.2 or from X lineages
for d in df_nested["non_pango_samples"].values:
    for k in d:
        assert k.startswith("X") or k == "BA.2"

AssertionError:

In [24]:
# Get the amiguous nodes from the tree sequence
descendants = {row["root"]: set() for _, row in df_nested.iterrows()}
for tree in ts.trees():
    for root, desc in descendants.items():
        for u in tree.samples(root):
            if ts.node(u).metadata["pango"] == "BA.2":
                desc.add(u)
descendants

KeyboardInterrupt:

# Per lineage analysis for marginal cases

This analysis is based on the lineage report data in v1. It may not be relevant any more, keeping for now.

In [26]:
df_pangolin = pd.read_csv("../arg_postprocessing/sc2ts_v1_2023-02-21_pr_pp_mp_aph_bps.lineage_report.csv").set_index("taxon")
df_pangolin

FileNotFoundError: [Errno 2] No such file or directory: '../arg_postprocessing/sc2ts_v1_2023-02-21_pr_pp_mp_aph_bps.lineage_report.csv'

In [23]:
data = []
pango_lookup = pango_events_tbl.set_index("root")
for root, desc in descendants.items():
    for u in desc:
        row = df_pangolin.loc[f"n{u}"]
        data.append({"root": root, "node": u, 
                     "pango":pango_lookup.loc[root]["pango"],
                     **dict(row)})
df_ba2_calls = pd.DataFrame(data)

## XJ

The three nested BA.2 calls under XJ could equally equally have been called XJ by the Usher placements.

In [24]:
df_ba2_calls[df_ba2_calls["pango"] == "XJ"][["scorpio_call","conflict", "note"]]

,scorpio_call,conflict,note
0,Omicron (Unassigned),0.5,Usher placements: BA.2(1/2) XJ(1/2); scorpio f...
1,Omicron (Unassigned),0.5,Usher placements: BA.2(1/2) XJ(1/2); scorpio f...
2,Omicron (Unassigned),0.5,Usher placements: BA.2(1/2) XJ(1/2); scorpio f...

## XR

The single nested XR sample was unambiguously assinged by Usher

In [25]:
df_ba2_calls[df_ba2_calls["pango"] == "XR"][["scorpio_call", "conflict", "note"]]

          scorpio_call  conflict                         note
3  Omicron (BA.2-like)       0.0  Usher placements: BA.2(1/1)

## XQ

2 of the 37 embedded samples could have been designated XU, otherwise there are all confident BA.2 placments (some done from lineage hashes also)

In [26]:
df_ba2_calls[df_ba2_calls["pango"] == "XQ"][["scorpio_call", "conflict", "note"]].reset_index()

,index,scorpio_call,conflict,note
0,4,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
1,5,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
2,6,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
3,7,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
4,8,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
5,9,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
6,10,Omicron (BA.2-like),0.5,Usher placements: BA.2(1/2) XU(1/2)
7,11,Omicron (BA.2-like),0.5,Usher placements: BA.2(1/2) XU(1/2)
8,12,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
9,13,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
10,14,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
11,15,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
12,16,Omicron (BA.2-like),0.0,Assigned from designation hash.
13,17,Omicron (BA.2-like),0.0,Assigned from designation hash.
14,18,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
15,19,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
16,20,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
17,21,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
18,22,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
19,23,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
20,24,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
21,25,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
22,26,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
23,27,Omicron (BA.2-like),0.0,Usher placements: BA.2(4/4)
24,28,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
25,29,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
26,30,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
27,31,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
28,32,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
29,33,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
30,34,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
31,35,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
32,36,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
33,37,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
34,38,Omicron (BA.2-like),0.0,Usher placements: BA.2(1/1)
35,39,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)
36,40,Omicron (BA.2-like),0.0,Usher placements: BA.2(3/3)

## XN

The one nested pango here could have been called as XN (2 of the 3 placements were XN?)

In [27]:
df_ba2_calls[df_ba2_calls["pango"] == "XN"][["conflict", "note"]].reset_index()

   index  conflict                                 note
0     41  0.666667  Usher placements: BA.2(1/3) XN(2/3)

## XBB

The single XBB sample seems to have a strong pango and Scorpio call for BA.2

In [28]:
df_ba2_calls[df_ba2_calls["pango"] == "XBB"][["scorpio_call", "conflict", "note"]].reset_index()

   index         scorpio_call  conflict                         note
0     42  Omicron (BA.2-like)       0.0  Usher placements: BA.2(1/1)

## XM

All got BA.2 assigments, with scorpio finding insufficient support and giving generic "Omicron (Unassigned)"

In [29]:
df_ba2_calls[df_ba2_calls["pango"] == "XM"][["scorpio_call", "conflict", "note"]].reset_index()

,index,scorpio_call,conflict,note
0,43,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
1,44,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
2,45,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
3,46,Omicron (Unassigned),0.0,Usher placements: BA.2(1/1); scorpio found ins...
4,47,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
5,48,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
6,49,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
7,50,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
8,51,Omicron (Unassigned),0.0,Usher placements: BA.2(1/1); scorpio found ins...
9,52,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
10,53,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
11,54,Omicron (Unassigned),0.0,Usher placements: BA.2(3/3); scorpio found ins...
12,55,Omicron (Unassigned),0.0,Usher placements: BA.2(1/1); scorpio found ins...
13,56,Omicron (Unassigned),0.0,Usher placements: BA.2(1/1); scorpio found ins...
14,57,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...
15,58,Omicron (Unassigned),0.0,Usher placements: BA.2(2/2); scorpio found ins...

In [30]:
df_ba2_calls[df_ba2_calls["pango"] == "XM"]["note"].values[0]

'Usher placements: BA.2(2/2); scorpio found insufficient support to assign a specific lineage'

## Overall

Overall, we've got 59 samples with BA.2 assignments. There are highly enriched for ambiguous calls, with 6/59 having multiple potential placements by Usher (10%) versus 2.75% over 2,747,985 nodes, and 25 of the 357 "Omicron (Unassigned)" Scorpio calls.

In [25]:
def format(n):
    return f"{n * 100:4g}%"

In [32]:
df_ba2_calls.shape[0], df_pangolin.shape[0]

(59, 2747985)

In [33]:
np.sum(df_ba2_calls["conflict"] > 0)

np.int64(6)

In [34]:
format(np.sum(df_ba2_calls["conflict"] > 0) / df_ba2_calls.shape[0])

'10.1695%'

In [35]:
format(np.sum(df_pangolin["conflict"] > 0) / df_pangolin.shape[0])

'2.7486%'

In [36]:
np.sum(df_ba2_calls["scorpio_call"] == "Omicron (Unassigned)")

np.int64(25)

In [37]:
np.sum(df_pangolin["scorpio_call"] == "Omicron (Unassigned)")

np.int64(357)

In [38]:
format(np.sum(df_ba2_calls["scorpio_call"] == "Omicron (Unassigned)") /
      np.sum(df_pangolin["scorpio_call"] == "Omicron (Unassigned)"))

'7.0028%'


# Type I RE events: recombinantion coinciding with Pango origin node.

In [27]:
type_1_events = pango_events_tbl[(pango_events_tbl["root_type"] == "R")]
type_1_events = type_1_events.sort_values(["mutations_averted", "root_pango"], ascending=False)
type_1_events

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
66,1872109,XDD,0,R,112,{},1872109,0.0,0.0,"{'XDD': 68, 'XDD.1': 17, 'XDD.1.1': 17, 'XDD.1...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,14.0,62.0,11.0,True,67.0,67.0
81,1840333,XCT,3,R,57,{},1840333,0.0,0.0,"{'XCT.1': 32, 'XCT': 25}",...,Omicron (BA.2-like),961.384849,2021-10-19,True,19.0,27.0,34.0,True,29.0,26.0
56,1729101,XBR,1,R,3,{},1729101,0.0,0.0,{'XBR': 3},...,Omicron (BA.2-like),961.384849,2021-10-19,True,13.0,25.0,26.0,True,26.0,24.0
0,1728703,XBS,3,R,19,{},1728703,0.0,0.0,{'XBS': 19},...,Omicron (BA.2-like),961.384849,2021-10-19,True,12.0,21.0,21.0,True,23.0,20.0
87,132996,XA,0,R,39,{},132996,0.0,0.0,{'XA': 39},...,.,1591.661216,2020-01-28,True,4.0,20.0,26.0,True,19.0,19.0
54,1169967,XS,0,R,19,{},1169967,0.0,0.0,{'XS': 19},...,.,1591.661216,2020-01-28,True,7.0,14.0,76.0,True,13.0,13.0
4,1834477,XCZ,3,R,6,{},1834477,0.0,0.0,"{'XCZ': 6, 'XBB.1.9': 1}",...,Omicron (XBB.1-like),695.299735,2022-07-12,True,9.0,13.0,16.0,True,16.0,13.0
39,1848677,XCY,1,R,1,{},1848677,0.0,0.0,{'XCY': 1},...,Omicron (XBB.1-like),695.299735,2022-07-12,True,9.0,14.0,11.0,True,11.0,10.0
85,1833719,XCR,2,R,84,{'XBB.1.5.70': 1},1833719,0.0,0.0,"{'XCR': 84, 'XBB.1.5.70': 1}",...,Omicron (XBB.1-like),695.299735,2022-07-12,True,8.0,18.0,11.0,True,12.0,10.0
10,1833066,XCP,0,R,40,{},1833066,0.0,0.0,{'XCP': 40},...,Omicron (XBB.1-like),695.299735,2022-07-12,True,9.0,9.0,15.0,True,9.0,9.0
40,1554790,XBG,2,R,31,{},1554790,0.0,0.0,{'XBG': 31},...,Omicron (BA.2-like),961.384849,2021-10-19,True,4.0,11.0,15.0,True,11.0,9.0
5,1836320,XCL,1,R,22,{},1836320,0.0,0.0,{'XCL': 22},...,Omicron (XBB.1.5-like),637.061153,2022-09-08,True,3.0,8.0,9.0,True,11.0,8.0
36,1629518,XBM,1,R,21,{},1629518,0.0,0.0,{'XBM': 21},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,9.0,17.0,True,11.0,8.0
45,1667113,XBD,0,R,46,{},1667113,0.0,0.0,{'XBD': 46},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,23.0,12.0,True,9.0,8.0
8,1705711,XBF,3,R,832,{},1705711,0.0,0.0,"{'XBF': 631, 'XBF.4': 65, 'XBF.3': 64, 'XBF.9'...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,10.0,8.0,29.0,True,10.0,7.0
17,1673437,XBB,15,R,112005,"{'BQ.1.1.13': 2, 'JN.1.1': 11, 'JN.3': 1, 'JN....",1673437,0.0,0.0,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
90,1133210,XJ,1,R,71,{'BA.2': 3},1133210,0.0,0.0,"{'XJ': 71, 'BA.2': 3}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,21.0,29.0,True,7.0,6.0
91,1871605,XDK,0,R,84,{},1871605,0.0,0.0,"{'XDK': 47, 'XDK.1': 12, 'XDK.5': 9, 'XDK.4.1'...",...,Omicron (BA.2-like),961.384849,2021-10-19,True,11.0,6.0,70.0,True,9.0,6.0
71,1788178,XBW,1,R,5,{},1788178,0.0,0.0,{'XBW': 5},...,Omicron (BA.2-like),961.384849,2021-10-19,True,16.0,32.0,11.0,True,9.0,6.0
61,1668622,XBH,2,R,7,{},1668622,0.0,0.0,{'XBH': 7},...,Omicron (BA.2-like),961.384849,2021-10-19,True,2.0,7.0,13.0,True,8.0,6.0
69,1105581,XF,1,R,18,{},1105581,0.0,0.0,{'XF': 18},...,.,1591.661216,2020-01-28,True,7.0,7.0,73.0,True,6.0,5.0
67,1883456,XDR,0,R,6,{},1883456,0.0,0.0,{'XDR': 6},...,Omicron (BA.2-like),961.384849,2021-10-19,True,0.0,14.0,5.0,True,8.0,5.0
68,1500071,XAN,0,R,26,{},1500071,0.0,0.0,{'XAN': 26},...,Omicron (BA.2-like),961.384849,2021-10-19,True,4.0,5.0,18.0,True,7.0,5.0
51,1322988,XAE,2,R,10,{},1322988,0.0,0.0,{'XAE': 10},...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,43.0,7.0,True,7.0,5.0
77,1311512,XAD,1,R,2,{},1311512,0.0,0.0,{'XAD': 2},...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,46.0,5.0,True,7.0,5.0
80,1413955,XY,2,R,23,{},1413955,0.0,0.0,{'XY': 23},...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,22.0,31.0,True,7.0,4.0
16,1375030,XW,1,R,37,{'BA.2': 3},1375030,0.0,0.0,"{'XW': 37, 'BA.2': 3}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,4.0,44.0,True,5.0,4.0
58,1300637,XV,0,R,9,{},1300637,0.0,0.0,{'XV': 9},...,Omicron (Unassigned),1333.857513,2020-10-12,True,2.0,21.0,28.0,True,5.0,4.0
3,1251095,XQ,1,R,58,"{'BA.2': 42, 'XR': 18, 'XAA': 22, 'XU': 1, 'XA...",1251095,0.0,0.0,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
6,1218637,XL,1,R,67,{},1218637,0.0,0.0,{'XL': 67},...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,10.0,40.0,True,5.0,4.0
62,1892436,XDY,2,R,3,{},1892436,0.0,0.0,{'XDY': 3},...,Omicron (BA.2-like),232.006024,2023-10-18,True,9.0,6.0,4.0,True,6.0,4.0
83,1825916,XCQ,1,R,8,{},1825916,0.0,0.0,{'XCQ': 8},...,Omicron (XBB-like),747.558324,2022-05-21,True,6.0,9.0,4.0,True,5.0,4.0
73,1623858,XBE,1,R,74,{},1623858,0.0,0.0,{'XBE': 74},...,Omicron (BA.5-like),828.000001,2022-03-01,True,5.0,7.0,5.0,True,5.0,4.0
60,1485232,XAZ,0,R,212,{},1485232,0.0,0.0,{'XAZ': 212},...,Omicron (BA.2-like),961.384849,2021-10-19,True,3.0,4.0,13.0,True,5.0,4.0
53,1863208,XDA,4,R,105,{},1863208,0.0,0.0,"{'XDA': 97, 'XDA.1': 8}",...,Omicron (XBB.1-like),695.299735,2022-07-12,True,8.0,12.0,7.0,True,9.0,3.0
75,1841603,XCH,6,R,155,{},1841603,0.0,0.0,"{'XCH': 103, 'XCH.1': 52}",...,Omicron (XBB.1-like),637.061153,2022-09-08,True,6.0,18.0,5.0,True,11.0,3.0

\begin{tabular}{lrllrrl}
\toprule
pango & averted & left p & right p & left & right & descendants \\
\midrule
XDD & 67 & JN.1.1 & EG.5.1.1 & 25700 & 26275 & {XDD:112} \\
XCT & 26 & \textbf{JG.4} & DV.7.1 & 18584 & 19326 & {XCT:57} \\
XBR & 24 & \textbf{BN.3.1} & \textbf{BQ.1.25} & 22034 & 22190 & {XBR:3} \\
XBS & 20 & BY.1 & \textbf{BQ.1.1} & 22034 & 22190 & {XBS:19} \\
XA & 19 & \textbf{B.1.177.18} & \textbf{B.1.1.7} & 21256 & 21765 & {XA:39} \\
XS & 13 & AY.103 & \textbf{BA.1.1} & 9054 & 10449 & {XS:19} \\
XCZ & 13 & \textbf{EG.5.1.1} & GK.1.1 & 18493 & 21718 & {XCZ:6} \\
XCY & 10 & \textbf{EG.5.1.3} & GK.3.1 & 21719 & 22480 & {XCY:1} \\
XCR & 10 & GK.1.1 & FU.1.1 & 23674 & 25045 & {XCR:84, XBB.1.5.70:1} \\
XCP & 9 & \textbf{EG.5.1.10} & \textbf{JD.1.1} & 14190 & 14634 & {XCP:40} \\
XBG & 9 & \textbf{BA.2.76} & \textbf{BA.5.2} & 22600 & 22917 & {XBG:31} \\
XCL & 8 & \textbf{XBB.1.5} & GK.2.1 & 12468 & 15755 & {XCL:22} \\
XBM & 8 & \textbf{BA.2.76} & \textbf{BF.3} & 22787 & 22882 & {XBM:21} \\
XBD & 8 & \textbf{BA.2.75.2} & \textbf{BA.5.2.1} & 23020 & 24620 & {XBD:46} \\
XBF & 7 & \textbf{BA.5.2.1} & CJ.1 & 5184 & 9866 & {XBF:832} \\
XBB & 7 & \textbf{BA.2.10} & BM.1.1.1 & 22332 & 22577 & {XBB:112005, BQ.1.1.13:2, JN.1.1:11, JN.3:1, JN.18:1, BA.2:1} \\
XJ & 6 & \textbf{BA.1.17.2} & \textbf{BA.2} & 13196 & 15240 & {XJ:71, BA.2:3} \\
XDK & 6 & \textbf{XBB.1.5} & \textbf{JN.1.1.1} & 5315 & 6183 & {XDK:84} \\
XBW & 6 & \textbf{XBB.1.5.107} & BQ.1.1 & 25417 & 26275 & {XBW:5} \\
XBH & 6 & \textbf{BA.2} & BA.2.75.2 & 15452 & 22016 & {XBH:7} \\
XF & 5 & \textbf{AY.4} & \textbf{BA.1.16} & 5387 & 6402 & {XF:18} \\
XDR & 5 & \textbf{JN.1.1} & JN.1.1 & 11043 & 11727 & {XDR:6} \\
XAN & 5 & \textbf{BA.2} & \textbf{BA.5.1.23} & 17823 & 19862 & {XAN:26} \\
XAE & 5 & \textbf{BA.2} & BA.1.1 & 24504 & 26060 & {XAE:10} \\
XAD & 5 & \textbf{BA.2} & \textbf{BA.1.1} & 26061 & 26530 & {XAD:2} \\
XY & 4 & \textbf{BA.1.1} & \textbf{BA.2} & 11538 & 12880 & {XY:23} \\
XW & 4 & BA.1.1.2 & \textbf{BA.2} & 2833 & 4321 & {XW:37, BA.2:3} \\
XV & 4 & \textbf{BA.1} & \textbf{BA.2} & 13196 & 15240 & {XV:9} \\
XQ & 4 & BA.1.1.15 & \textbf{BA.2.5} & 4322 & 5386 & {XQ:58, BA.2:42, XR:18, XAA:22, XU:1, XAM:26, XAB:3, XAG:17} \\
XL & 4 & \textbf{BA.1.17.2} & \textbf{BA.2.5} & 5925 & 8393 & {XL:67} \\
XDY & 4 & \textbf{LB.1.2.1} & KP.3.2 & 22132 & 22599 & {XDY:3} \\
XCQ & 4 & \textbf{XBB.2.3.15} & XBB.1.5.15 & 23124 & 23757 & {XCQ:8} \\
XBE & 4 & \textbf{BA.5.2.6} & \textbf{BE.4} & 22600 & 27012 & {XBE:74} \\
XAZ & 4 & \textbf{BA.2.5} & \textbf{BA.5} & 3359 & 9866 & {XAZ:212} \\
XDA & 3 & \textbf{XBB.1.16.20} & HN.5 & 22102 & 22928 & {XDA:105} \\
XCH & 3 & GK.1 & \textbf{FY.2} & 23674 & 25045 & {XCH:155} \\
\bottomrule
\end{tabular}

## Type III RE events.

In [76]:
type_3_events = pango_events_tbl[
    (pango_events_tbl["root_type"] != "R") & ~(pango_events_tbl["closest_recombinant"].isin([-1, ba5_root]))].copy()
#type_3_events = pango_events_tbl[(pango_events_tbl["root_type"] != "R")].copy()

type_3_events

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
7,1117665,XG,3,I,159,{},1093814,3.0,5.781627e+00,"{'XG': 159, 'BA.2': 11}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,4.0,8.0,41.0,True,7.0,7.0
15,1406886,XAA,3,I,22,{},1251095,7.0,4.372446e+01,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
38,1841699,XDF,6,S,1,{},1673437,12.0,4.815583e+02,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
41,1814205,XBL,5,I,13,{},1673437,5.0,1.898683e+02,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
42,1477814,XAM,3,I,26,{},1251095,7.0,2.772446e+01,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
43,1380286,XZ,1,I,51,{},1133051,4.0,5.200000e+01,"{'BA.2': 218, 'XZ': 51, 'XAP': 21}",...,Omicron (Unassigned),1333.857513,2020-10-12,False,4.0,43.0,5.0,True,7.0,7.0
46,1129760,XE,4,I,1256,{},1073548,2.0,9.456944e+00,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,14.0,36.0,True,16.0,13.0
48,242303,XB,2,I,202,{},242304,2.0,2.000888e-10,"{'B.1': 224, 'XB': 202}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,1489437,XU,13,S,1,{},1251095,7.0,1.137245e+02,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
70,1486589,XAG,4,I,17,{},1251095,7.0,4.403100e+01,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
72,1502277,XAL,2,I,14,{},1178986,4.0,7.075633e+01,"{'XM': 31, 'XAL': 14, 'BA.2': 7}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,25.0,23.0,True,9.0,8.0
74,1480504,XAB,1,I,3,{},1251095,7.0,4.202249e+01,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
84,1821991,XCF,5,I,45,{},1767510,4.0,2.317969e+01,"{'XCF': 38, 'XBB.1.5': 6, 'XCF.3': 6, 'XCF.1':...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,25.0,1.0,False,5.0,4.0
86,1361112,XR,4,I,18,{'BA.2': 1},1251095,4.0,2.172446e+01,"{'XQ': 58, 'BA.2': 42, 'XAM': 26, 'XAA': 22, '...",...,Omicron (Unassigned),1333.857513,2020-10-12,True,5.0,7.0,44.0,True,5.0,4.0
92,1073547,XH,3,S,40,{},1073548,1.0,8.000000e+00,"{'XE': 1256, 'XH': 40, 'BA.2': 34}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,14.0,36.0,True,16.0,13.0
96,468298,XC,1,I,5,{},463545,1.0,1.987689e+01,"{'XC': 5, 'B.1.617.2': 1}",...,.,1591.661216,2020-01-28,True,5.0,40.0,15.0,True,37.0,36.0

In [42]:
event_nodes = set(type_3_events["closest_recombinant"]) - set(type_1_events["root"])
event_nodes

{242304, 463545, 1073548, 1093814, 1133051, 1178986, 1428716, 1767510}

## Identifying the type II event nodes

We've gone from 5 Type II events to 8. We need some sort of alias for these - we can start with the old ideas which was

{965353: 'XE/XH', 966905: 'XJ', 964555: 'Xx', 1177107: 'XAF', 1348822: 'XBM'}

In [50]:
xb_event = 242304
dfe[dfe["root"].isin(event_nodes - {xb_event})]

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
94,1178986,XM,0,R,31,"{'BA.2': 7, 'XAL': 14}",1178986,0.0,0.0,"{'XM': 31, 'XAL': 14, 'BA.2': 7}",...,Omicron (Unassigned),1333.857513,2020-10-12,True,3.0,25.0,23.0,True,9.0,8.0

In [51]:
dfr.loc[list(event_nodes - {xb_event})]

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
recombinant,,,,,,,,,,,,,,,,,,,,,
1178986,SRR18814882,52,1,1,20056,21618,1,COVID-ARTIC-V4.1,.,2022-01-29,...,Omicron (Unassigned),1333.857513,2020-10-12,True,3,25,23,True,9,8
1073548,ERR12888175,1330,1,1,10448,11283,3,COVID-ARTIC-V3,.,2021-12-30,...,Omicron (Unassigned),1333.857513,2020-10-12,True,3,14,36,True,16,13
1428716,SRR21340546,244601,11,2,23041,26858,4,COVID-ARTIC-V4.1,.,2022-04-09,...,Omicron (BA.2-like),961.384849,2021-10-19,False,2,6,5,True,9,5
1093814,ERR12888689,170,1,1,8394,9424,0,COVID-ARTIC-V3,.,2022-01-08,...,Omicron (Unassigned),1333.857513,2020-10-12,True,4,8,41,True,7,7
1767510,SRR23710835,52,1,1,26276,27874,1,COVID-ARTIC-V4.1,.,2023-02-13,...,Omicron (Unassigned),1333.857513,2020-10-12,True,5,25,1,False,5,4
463545,DRR321273,6,1,1,26768,27390,1,COVID-ARTIC-V3,.,2021-08-12,...,.,1591.661216,2020-01-28,True,5,40,15,True,37,36
1133051,ERR8146303,290,1,1,24504,26060,0,COVID-ARTIC-V4.1,4.1alt,2022-01-19,...,Omicron (Unassigned),1333.857513,2020-10-12,False,4,43,5,True,7,7

In [44]:
assert set(event_aliases.keys()) == set(type_3_events["closest_recombinant"]) - set(type_1_events["root"])

In [31]:
type_2_events = pango_events_tbl[pango_events_tbl["closest_recombinant"].isin(event_aliases.keys())]
type_2_events = type_2_events.groupby("closest_recombinant").first().sort_values("mutations_averted", ascending=False)
type_2_events["alias"] = event_aliases
type_2_events[["root_pango", "alias", "closest_recombinant_descendants", "mutations_averted"]]

,root_pango,alias,closest_recombinant_descendants,mutations_averted
closest_recombinant,,,,
965353,NaN,XE/XH,NaN,NaN
966905,NaN,XJ,NaN,NaN
964555,NaN,Xx,NaN,NaN
1177107,NaN,XAF,NaN,NaN
1348822,NaN,XBM,NaN,NaN

In [32]:
col_name_map = {
    "alias": "alias",
    "mutations_averted": "averted",
    "parent_left_pango": "left p",
    "parent_right_pango": "right p",
    "interval_left": "left",
    "interval_right": "right",
    "closest_recombinant_descendants": "descendants",
}
s = type_2_events[list(col_name_map.keys())].to_latex(
        escape=False, index=False, header=list(col_name_map.values()),
        float_format="%.0f")
s = s.replace("'", "").replace(": ", ":")
#s = s.replace("{BA.2:37, XR:17, XAA:17, XU:1, XAM:21, XAG:6\}", "{BA.2:37, $\star$\}")
print(s)

\begin{tabular}{lrllrrl}
\toprule
alias & averted & left p & right p & left & right & descendants \\
\midrule
XE/XH & NaN & NaN & NaN & NaN & NaN & NaN \\
XJ & NaN & NaN & NaN & NaN & NaN & NaN \\
Xx & NaN & NaN & NaN & NaN & NaN & NaN \\
XAF & NaN & NaN & NaN & NaN & NaN & NaN \\
XBM & NaN & NaN & NaN & NaN & NaN & NaN \\
\bottomrule
\end{tabular}

In [33]:
event_names = {**event_aliases, **{row["root"]: row["root_pango"] for _, row in type_1_events.iterrows()}}

event_names

{965353: 'XE/XH',
 966905: 'XJ',
 964555: 'Xx',
 1177107: 'XAF',
 1348822: 'XBM',
 1875327: 'XDD',
 1843410: 'XCT',
 1732233: 'XBR',
 1731957: 'XBS',
 132899: 'XA',
 1894585: 'XDV.1',
 1799712: 'XBB.2.3',
 1722702: 'XBV',
 1173316: 'XS',
 1837724: 'XCZ',
 1851951: 'XCY',
 1837016: 'XCR',
 1836124: 'XCP',
 1769335: 'XCC',
 1558028: 'XBG',
 1839568: 'XCL',
 1633571: 'XBM',
 1670327: 'XBD',
 1708787: 'XBF',
 1676682: 'XBB',
 1134481: 'XJ',
 1871948: 'XDP',
 1874829: 'XDK',
 1791222: 'XBW',
 1671867: 'XBH',
 1107501: 'XF',
 1886690: 'XDR',
 1878215: 'XDP',
 1791503: 'XBB.1.5',
 1502510: 'XAN',
 1326725: 'XAE',
 1417358: 'XY',
 1378600: 'XW',
 1301504: 'XV',
 1252155: 'XQ',
 1222133: 'XL',
 1895676: 'XDY',
 1829166: 'XCQ',
 1822188: 'XCE',
 1627107: 'XBE',
 1787625: 'XBB.1.5.16',
 1767951: 'XBB.1.5',
 1755170: 'XBB.1.5',
 1786345: 'XBB.1.5',
 1796262: 'XBB.1.5',
 1832383: 'XBB.1.16.4',
 1488660: 'XAZ',
 1866449: 'XDA',
 1844851: 'XCH',
 1730254: 'XBC.1.2.1',
 1726834: 'XAY.2'}

In [34]:
type_3_events["event_name"] = [event_names[u] for u in type_3_events["closest_recombinant"]]
type_3_events = type_3_events.sort_values(["event_name", "pango"])
type_3_events

KeyError: 1070426

In [49]:
col_name_map = {
    "root_pango": "pango",
    "event_name": "name",
    "closest_recombinant_path_len": "path len",
    "closest_recombinant_time": "time",
    "root_mutations": "mutations",
    "descendants": "descendants",
    #"non_pango_samples": "nested",
  
    #"closest_recombinant_descendants": "by pango",
}
s = type_3_events[list(col_name_map.keys())].to_latex(
        escape=True, index=False, header=list(col_name_map.values()),
        float_format="%.0f")
s = s.replace("'", "").replace(": ", ":")
print(s)

\begin{tabular}{llrrrl}
\toprule
pango & name & path len & time & mutations & descendants \\
\midrule
XAF & XAF & 5 & 140 & 8 & {XAF:1} \\
XBM & XBM & 1 & 23 & 1 & {XBM:10} \\
XE & XE/XH & 1 & 19 & 2 & {XE:1116} \\
XH & XE/XH & 1 & 55 & 7 & {XH:2} \\
XJ & XJ & 1 & 5 & 2 & {XJ:68, BA.2:3} \\
XAL & XM & 3 & 65 & 2 & {XAL:3} \\
XAA & XQ & 6 & 33 & 3 & {XAA:17} \\
XAG & XQ & 6 & 53 & 4 & {XAG:6} \\
XAM & XQ & 6 & 40 & 3 & {XAM:21} \\
XR & XQ & 3 & 11 & 4 & {XR:17, BA.2:1} \\
XU & XQ & 6 & 103 & 13 & {XU:1} \\
XAE & Xx & 2 & 47 & 7 & {XAE:9} \\
XAP & Xx & 4 & 66 & 1 & {XAP:20} \\
XZ & Xx & 4 & 48 & 1 & {XZ:48} \\
\bottomrule
\end{tabular}

# Not recombinants

This looks basically the same as before, with the notable loss of XB and a few others lost.

In [86]:
type_4_events = pango_events_tbl[
    pango_events_tbl["closest_recombinant"].isin([-1, xbb_root, ba5_root]) & 
    (pango_events_tbl["closest_recombinant_path_len"] > 3)
    ].copy()
type_4_events = type_4_events.sort_values(["root_mutations", "root_pango"], ascending=True)
type_4_events

,root,root_pango,root_mutations,root_type,pango_samples,non_pango_samples,closest_recombinant,closest_recombinant_path_len,closest_recombinant_time,closest_recombinant_descendants,...,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date,is_rebar_recombinant,parent_pangonet_distance,net_min_supporting_loci_lft,net_min_supporting_loci_rgt,net_min_supporting_loci_lft_rgt_ge_4,k1000_muts,mutations_averted
44,1518721,XAS,1,S,84,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,1472899,XAU,1,S,9,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,1725053,XBK,1,I,178,{'CJ.1': 1},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,1733651,XBQ,1,I,36,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1253868,XN,1,S,141,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,1291412,XP,1,S,48,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,1525011,XAV,3,S,13,{},1428716,7.0,106.000001,{'too_many_to_classify': 244541},...,Omicron (BA.2-like),961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0
76,1711075,XBZ,4,S,165,{},1428716,16.0,265.000001,{'too_many_to_classify': 244541},...,Omicron (BA.2-like),961.384849,2021-10-19,False,2.0,6.0,5.0,True,9.0,5.0
41,1814205,XBL,5,I,13,{},1673437,5.0,189.868325,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
38,1841699,XDF,6,S,1,{},1673437,12.0,481.558324,{'too_many_to_classify': 112021},...,Omicron (BA.2-like),961.384849,2021-10-19,True,6.0,13.0,10.0,True,21.0,7.0
55,1534989,XAJ,11,I,21,{},-1,inf,inf,{},...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
xbb_root, ba5_root

(1673437, 1428716)

In [87]:
tree = ts.first()
root_parent = {}
root_parent_pango = {}
for k, row in type_4_events.iterrows():  
    u = tree.parent_array[row["root"]]
    root_parent[k] = u
    root_parent_pango[k] = df_node.loc[u, "pango"]

type_4_events["root_parent"] = root_parent
type_4_events["root_parent_pango"] = root_parent_pango

In [88]:
format_parent_col(type_4_events, "root_parent", "root_parent_pango")

In [89]:
col_name_map = {
    "root_pango": "pango",
    "root_mutations": "mutations",
    "root_parent_pango": "parent",
    #"parent_is_observed_sample": "parent sample",
    "descendants": "descendants",
  
    #"closest_recombinant_descendants": "by pango",
}
s = type_4_events[list(col_name_map.keys())].to_latex(
        escape=False, index=False, header=list(col_name_map.values()),
        float_format="%.0f")
s = s.replace("'", "").replace(": ", ":")
print(s)

\begin{tabular}{lrll}
\toprule
pango & mutations & parent & descendants \\
\midrule
XAS & 1 & BA.4 & {XAS:84} \\
XAU & 1 & BA.2 & {XAU:9} \\
XBK & 1 & CJ.1 & {XBK:178, CJ.1:1} \\
XBQ & 1 & CJ.1 & {XBQ:36} \\
XN & 1 & \textbf{BA.2} & {XN:141} \\
XP & 1 & \textbf{BA.1.1} & {XP:48} \\
XAV & 3 & BA.5.1.24 & {XAV:13} \\
XBZ & 4 & \textbf{EF.1} & {XBZ:165} \\
XBL & 5 & XBB.1.5.57 & {XBL:13} \\
XDF & 6 & EG.5.1 & {XDF:1} \\
XAJ & 11 & \textbf{BA.2.12} & {XAJ:21} \\
\bottomrule
\end{tabular}

In [90]:
list(type_4_events["root_pango"])

['XAS', 'XAU', 'XBK', 'XBQ', 'XN', 'XP', 'XAV', 'XBZ', 'XBL', 'XDF', 'XAJ']