In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/apps/eb/el8/2023a/epyc/software/Python/3.11.3-GCCcore-12.3.0/easybuild/python', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmp1460z01a/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x95z\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94\x8c6sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated.trees\x94a}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x0fh\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8cAsc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants.csv\x94a}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c0sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated\x94a}\x94(h\x0b}\x94\x8c\x0bRECR_PREFIX\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbh8h5ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0b}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhGhDhIK\x01hKK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8cOlogs/sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants_report.ipynb\x94a}\x94(h\x0b}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhYhVub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x13recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import tszip
import sc2ts.debug as sd
import pandas as pd

In [3]:
ts = tszip.load(snakemake.input[0])
ts

In [4]:
ti = sd.ArgInfo(ts, show_progress=False, pango_source="pango", scorpio_source="scorpio")
ti

In [5]:
dfr = ti.recombinants_summary(show_progress=False)

RE: 128068 interval right shifted from 22227 to 21765

RE: 233437 has more than two parents. Skipping.

RE: 360390 interval right shifted from 28255 to 28252

RE: 445074 interval right shifted from 22030 to 22029

RE: 460790 interval_right >= interval_left; moving from 22027to 22026

RE: 468981 interval right shifted from 22030 to 22029

RE: 489825 interval_right >= interval_left; moving from 22027to 22026

RE: 499622 interval right shifted from 22030 to 22029

RE: 543752 interval right shifted from 25046 to 22194

RE: 579581 interval right shifted from 22030 to 22029

RE: 579585 interval_right >= interval_left; moving from 22027to 22026

RE: 597638 interval_right >= interval_left; moving from 22027to 22026

RE: 623743 interval_right >= interval_left; moving from 22027to 22026

RE: 628790 interval_right >= interval_left; moving from 22027to 22026

RE: 663691 interval_right >= interval_left; moving from 22027to 22026

RE: 672954 interval right shifted from 22030 to 22029

RE: 673179 interval_right >= interval_left; moving from 22027to 22026

RE: 678462 interval right shifted from 22030 to 22029

RE: 687638 interval_right >= interval_left; moving from 22027to 22026

RE: 690014 interval right shifted from 22030 to 22029

RE: 691401 interval_right >= interval_left; moving from 22027to 22026

RE: 694629 interval_right >= interval_left; moving from 22027to 22026

RE: 702675 interval_right >= interval_left; moving from 22027to 22026

RE: 706031 interval right shifted from 22030 to 22029

RE: 707679 interval_right >= interval_left; moving from 22027to 22026

RE: 711981 interval_right >= interval_left; moving from 22027to 22026

RE: 722289 interval_right >= interval_left; moving from 22027to 22026

RE: 722364 interval right shifted from 22030 to 22029

RE: 722986 interval_right >= interval_left; moving from 22027to 22026

RE: 726179 interval_right >= interval_left; moving from 22027to 22026

RE: 731171 interval_right >= interval_left; moving from 22027to 22026

RE: 740335 interval right shifted from 22030 to 22029

RE: 773911 interval right shifted from 22030 to 22029

RE: 779151 interval right shifted from 22030 to 22029

RE: 808949 interval_right >= interval_left; moving from 22027to 22026

RE: 810444 interval_right >= interval_left; moving from 22027to 22026

RE: 810646 interval_right >= interval_left; moving from 22027to 22026

RE: 815861 interval_right >= interval_left; moving from 22027to 22026

RE: 820917 interval_right >= interval_left; moving from 22027to 22026

RE: 821204 interval_right >= interval_left; moving from 22027to 22026

RE: 829773 interval_right >= interval_left; moving from 22027to 22026

RE: 880272 interval_right >= interval_left; moving from 22027to 22026

RE: 896655 interval_right >= interval_left; moving from 22027to 22026

RE: 903847 interval right shifted from 22030 to 22029

RE: 914366 interval_right >= interval_left; moving from 22027to 22026

RE: 914409 interval_right >= interval_left; moving from 22027to 22026

RE: 927640 interval_right >= interval_left; moving from 22027to 22026

RE: 957937 interval_right >= interval_left; moving from 22027to 22026

RE: 969098 interval_right >= interval_left; moving from 22027to 22026

RE: 973080 interval_right >= interval_left; moving from 22027to 22026

RE: 1005070 interval right shifted from 11537 to 11283

RE: 1010431 interval right shifted from 22195 to 22194

RE: 1026251 interval right shifted from 22195 to 22194

RE: 1057060 interval right shifted from 7393 to 6513

RE: 1057755 interval right shifted from 22195 to 22194

RE: 1112124 interval right shifted from 22197 to 22194

RE: 1112124 interval_right >= interval_left; moving from 22196to 22193

RE: 1122069 interval right shifted from 22197 to 22194

RE: 1122069 interval_right >= interval_left; moving from 22196to 22193

RE: 1122633 interval right shifted from 22197 to 22194

RE: 1122633 interval_right >= interval_left; moving from 22196to 22193

RE: 1127704 interval right shifted from 22195 to 22194

RE: 1131800 interval right shifted from 22195 to 22194

RE: 1147275 interval right shifted from 22195 to 22194

RE: 1149797 interval right shifted from 11537 to 11283

RE: 1154233 interval right shifted from 22197 to 22194

RE: 1154233 interval_right >= interval_left; moving from 22196to 22193

RE: 1159269 interval right shifted from 22195 to 22194

RE: 1167811 interval right shifted from 22195 to 22194

RE: 1172384 interval right shifted from 22197 to 22194

RE: 1172384 interval_right >= interval_left; moving from 22196to 22193

RE: 1172556 interval right shifted from 22195 to 22194

RE: 1176908 interval right shifted from 22198 to 22194

RE: 1176908 interval_right >= interval_left; moving from 22197to 22193

RE: 1177219 interval right shifted from 22195 to 22194

RE: 1180855 interval right shifted from 22195 to 22194

RE: 1187697 interval right shifted from 22195 to 22194

RE: 1187728 interval right shifted from 22195 to 22194

RE: 1194104 interval right shifted from 22195 to 22194

RE: 1194165 interval right shifted from 22197 to 22194

RE: 1194165 interval_right >= interval_left; moving from 22196to 22193

RE: 1194176 interval right shifted from 22197 to 22194

RE: 1194176 interval_right >= interval_left; moving from 22196to 22193

RE: 1198028 interval right shifted from 22197 to 22194

RE: 1198028 interval_right >= interval_left; moving from 22196to 22193

RE: 1198339 interval right shifted from 22197 to 22194

RE: 1198339 interval_right >= interval_left; moving from 22196to 22193

RE: 1198805 interval right shifted from 22195 to 22194

RE: 1202248 interval right shifted from 22197 to 22194

RE: 1202248 interval_right >= interval_left; moving from 22196to 22193

RE: 1202253 interval right shifted from 22197 to 22194

RE: 1202253 interval_right >= interval_left; moving from 22196to 22193

RE: 1206130 interval right shifted from 22197 to 22194

RE: 1206130 interval_right >= interval_left; moving from 22196to 22193

RE: 1206171 interval right shifted from 22197 to 22194

RE: 1206171 interval_right >= interval_left; moving from 22196to 22193

RE: 1209530 interval right shifted from 22195 to 22194

RE: 1209532 interval right shifted from 22195 to 22194

RE: 1211408 interval right shifted from 22195 to 22194

RE: 1211417 interval right shifted from 22195 to 22194

RE: 1211822 interval right shifted from 22195 to 22194

RE: 1211824 interval right shifted from 22195 to 22194

RE: 1211826 interval right shifted from 22195 to 22194

RE: 1215361 interval right shifted from 22195 to 22194

RE: 1215393 interval right shifted from 22197 to 22194

RE: 1215393 interval_right >= interval_left; moving from 22196to 22193

RE: 1215407 interval right shifted from 22197 to 22194

RE: 1215407 interval_right >= interval_left; moving from 22196to 22193

RE: 1215409 interval right shifted from 22197 to 22194

RE: 1215409 interval_right >= interval_left; moving from 22196to 22193

RE: 1215560 interval right shifted from 22197 to 22194

RE: 1215560 interval_right >= interval_left; moving from 22196to 22193

RE: 1217446 interval right shifted from 8260 to 6513

RE: 1218156 interval right shifted from 22197 to 22194

RE: 1218156 interval_right >= interval_left; moving from 22196to 22193

RE: 1218425 interval right shifted from 22195 to 22194

RE: 1218427 interval right shifted from 22195 to 22194

RE: 1218431 interval right shifted from 22195 to 22194

RE: 1220715 interval right shifted from 22195 to 22194

RE: 1220826 interval right shifted from 22195 to 22194

RE: 1220855 interval right shifted from 22195 to 22194

RE: 1220874 interval right shifted from 22195 to 22194

RE: 1226916 interval right shifted from 22197 to 22194

RE: 1226916 interval_right >= interval_left; moving from 22196to 22193

RE: 1227048 interval right shifted from 22197 to 22194

RE: 1227048 interval_right >= interval_left; moving from 22196to 22193

RE: 1230829 interval right shifted from 22195 to 22194

RE: 1236102 interval right shifted from 22197 to 22194

RE: 1236102 interval_right >= interval_left; moving from 22196to 22193

RE: 1240285 interval right shifted from 22195 to 22194

RE: 1240642 interval right shifted from 22195 to 22194

RE: 1240859 interval right shifted from 22197 to 22194

RE: 1240859 interval_right >= interval_left; moving from 22196to 22193

RE: 1240897 interval right shifted from 22195 to 22194

RE: 1244249 interval right shifted from 22195 to 22194

RE: 1251004 interval right shifted from 22197 to 22194

RE: 1251004 interval_right >= interval_left; moving from 22196to 22193

RE: 1251221 interval right shifted from 22197 to 22194

RE: 1251221 interval_right >= interval_left; moving from 22196to 22193

RE: 1254141 interval right shifted from 22195 to 22194

RE: 1254145 interval right shifted from 22195 to 22194

RE: 1266297 interval right shifted from 22195 to 22194

RE: 1266299 interval right shifted from 22195 to 22194

RE: 1269391 interval right shifted from 22197 to 22194

RE: 1269391 interval_right >= interval_left; moving from 22196to 22193

RE: 1269577 interval right shifted from 22197 to 22194

RE: 1269577 interval_right >= interval_left; moving from 22196to 22193

RE: 1278956 interval right shifted from 22197 to 22194

RE: 1278956 interval_right >= interval_left; moving from 22196to 22193

RE: 1278976 interval right shifted from 22195 to 22194

RE: 1283418 interval right shifted from 11537 to 11283

RE: 1283815 interval right shifted from 22197 to 22194

RE: 1283815 interval_right >= interval_left; moving from 22196to 22193

RE: 1287173 interval right shifted from 22195 to 22194

RE: 1287548 interval right shifted from 22195 to 22194

RE: 1300504 interval right shifted from 22195 to 22194

RE: 1303759 interval right shifted from 22195 to 22194

RE: 1303775 interval right shifted from 22195 to 22194

RE: 1309256 interval right shifted from 22195 to 22194

RE: 1309259 interval right shifted from 22195 to 22194

RE: 1309539 interval right shifted from 22195 to 22194

RE: 1314902 interval right shifted from 22197 to 22194

RE: 1314902 interval_right >= interval_left; moving from 22196to 22193

RE: 1321517 interval right shifted from 22195 to 22194

RE: 1325193 interval right shifted from 22195 to 22194

RE: 1332843 interval right shifted from 9693 to 6513

RE: 1335155 interval right shifted from 22195 to 22194

RE: 1343006 interval right shifted from 22195 to 22194

RE: 1344730 interval right shifted from 22195 to 22194

RE: 1345236 interval right shifted from 11537 to 11283

RE: 1347393 interval right shifted from 11537 to 11283

RE: 1347903 interval right shifted from 22195 to 22194

RE: 1349756 interval right shifted from 22195 to 22194

RE: 1352889 interval right shifted from 22195 to 22194

RE: 1363771 interval right shifted from 22195 to 22194

RE: 1416943 interval right shifted from 22792 to 21765

RE: 1450811 interval right shifted from 22917 to 21765

RE: 1521225 interval right shifted from 22917 to 21765

RE: 1553539 interval right shifted from 1627 to 693

RE: 1553539 interval_right >= interval_left; moving from 695to 692

RE: 1585338 interval right shifted from 22001 to 21765

RE: 1603903 interval right shifted from 21810 to 21765

RE: 1605346 has more than two parents. Skipping.

RE: 1610667 has more than two parents. Skipping.

RE: 1615910 interval right shifted from 22599 to 21991

RE: 1630666 interval right shifted from 22001 to 21765

RE: 1631416 interval right shifted from 22001 to 21765

RE: 1653824 interval right shifted from 21994 to 21991

RE: 1701949 has more than two parents. Skipping.

RE: 1715820 interval right shifted from 22295 to 22194

RE: 1718382 interval_right >= interval_left; moving from 21620to 21619

RE: 1725040 interval_right >= interval_left; moving from 21625to 21624

RE: 1728531 interval_right >= interval_left; moving from 21625to 21624

In [6]:
dfr

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,oldest_child,oldest_child_pango,oldest_child_scorpio,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date
981,ERR10306538,1,1,1,692,693,0,COVID-ARTIC-V4.1,.,2022-09-20,...,1553538,BA.5.2,Omicron (BA.5-like),625.000000,2022-09-20,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
849,ERR9939974,1895,1,1,695,958,1,COVID-ARTIC-V4.1,.,2022-06-27,...,1437053,BA.4.1,Omicron (BA.4-like),711.557882,2022-06-28,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
372,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,2021-10-21,...,715498,AY.44,Delta (B.1.617.2-like),959.000000,2021-10-21,233487,B.1.617.2,Delta (B.1.617.2-like),1267.767955,2020-12-17
938,ERR10150242,1,1,1,695,1598,1,COVID-ARTIC-V4.1,.,2022-08-21,...,1518113,BA.4,Omicron (BA.4-like),655.000000,2022-08-21,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
815,ERR9848224,2214,1,1,695,1627,1,COVID-ARTIC-V4.1,.,2022-05-30,...,1400450,BA.5.2.1,Omicron (BA.5-like),738.000000,2022-05-30,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898,SRR22472502,1,1,1,28372,29729,1,COVID-ARTIC-V4.1,.,2022-07-24,...,1482467,BA.5.2.1,Omicron (BA.5-like),683.000000,2022-07-24,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
1071,ERR10933490,6,1,1,27916,29729,2,COVID-ARTIC-V4.1,4.1alt,2023-02-13,...,1636763,XBB.1.5.4,Omicron (XBB.1.5-like),479.000000,2023-02-13,914293,BA.2,Omicron (BA.2-like),918.000000,2021-12-01
637,SRR18234565,20,2,1,25923,29734,2,COVID-VARSKIP-V1a-2b,.,2022-02-08,...,1241129,BA.1.18,Omicron (BA.1-like),868.000000,2022-01-20,860420,BA.1,Omicron (BA.1-like),946.739514,2021-11-03
863,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,2022-07-06,...,1449711,BA.5.2.1,Omicron (BA.5-like),701.000000,2022-07-06,1731105,B.1.1.529,Probable Omicron (Unassigned),1498.242165,2020-04-30
623,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,2022-01-29,...,1099679,BA.1.17,Omicron (BA.1-like),859.000000,2022-01-29,67,B.1,.,1591.543317,2020-01-28

In [7]:
dfr.describe()

,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,group_size,recombinant,recombinant_time,recombinant_date,...,parent_left_date,parent_right,parent_right_time,parent_right_date,oldest_child,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_time,parent_mrca_date
count,1.174000e+03,1174.000000,1174.000000,1174.000000,1174.000000,1174.000000,1174.000000,1.174000e+03,1174.000000,1174,...,1174,1.174000e+03,1174.000000,1174,1.174000e+03,1174.000000,1174,1.174000e+03,1174.000000,1174
mean,1.458381e+03,1.148211,1.006814,18657.132027,21022.054514,1.441227,2.182283,1.036925e+06,833.915587,2022-02-23 10:14:30,...,2022-01-14 01:52:50,8.796086e+05,909.627665,2021-12-09 13:24:38,1.051183e+06,818.931124,2022-03-10 02:23:30,7.301116e+05,1131.277573,2021-05-02 05:42:12
min,1.000000e+00,1.000000,1.000000,223.000000,693.000000,0.000000,2.000000,1.723000e+03,30.120103,2020-03-18 00:00:00,...,2020-02-24 00:00:00,9.730000e+02,61.000000,2019-12-26 00:00:00,1.722000e+03,15.000000,2020-03-22 00:00:00,1.000000e+00,283.725524,2019-12-26 00:00:00
25%,1.000000e+00,1.000000,1.000000,15017.000000,21610.000000,1.000000,2.000000,6.736135e+05,713.773045,2021-09-26 06:00:00,...,2021-08-21 00:00:00,3.938985e+05,783.422121,2021-06-26 00:00:00,6.783715e+05,697.250000,2021-10-11 00:00:00,2.334870e+05,922.690040,2020-12-17 00:00:00
50%,1.000000e+00,1.000000,1.000000,21624.000000,22027.000000,1.000000,2.000000,1.020931e+06,896.500000,2021-12-22 12:00:00,...,2021-11-27 12:00:00,9.332620e+05,936.681046,2021-11-13 00:00:00,1.031542e+06,888.500000,2021-12-30 12:00:00,8.564905e+05,1267.767955,2020-12-17 00:00:00
75%,3.000000e+00,1.000000,1.000000,22193.000000,23980.000000,2.000000,2.000000,1.462930e+06,983.905775,2022-06-23 18:00:00,...,2022-05-08 00:00:00,1.378746e+06,1076.000000,2022-04-14 18:00:00,1.470985e+06,969.000000,2022-07-09 18:00:00,1.312227e+06,1267.767955,2021-11-27 00:00:00
max,1.154010e+06,35.000000,4.000000,29701.000000,29751.000000,17.000000,50.000000,1.730564e+06,1541.000000,2024-05-07 00:00:00,...,2024-03-09 00:00:00,1.729675e+06,1624.000000,2024-04-06 00:00:00,3.104326e+06,1537.000000,2024-05-22 00:00:00,1.731105e+06,1624.000000,2023-08-28 00:00:00
std,3.499698e+04,1.290734,0.130399,6509.525569,5871.424722,1.294438,1.780110,4.488135e+05,235.240044,NaN,...,NaN,5.022606e+05,245.553697,NaN,4.663719e+05,236.687555,NaN,5.774706e+05,280.776083,NaN

In [8]:
dfr.to_csv(snakemake.output[0]);