In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/apps/eb/el8/2023a/epyc/software/Python/3.11.3-GCCcore-12.3.0/easybuild/python', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmp0_yj8c04/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x957\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c\x19sc2ts_v2_2024-06-06.trees\x94\x8c)sc2ts_v2_2024-06-06_recombinants_lbs.json\x94\x8c\x1csc2ts_v2_2024-06-06_pr.trees\x94e}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x11h\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94}\x94(h\r}\x94h\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\r}\x94h\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c\x13sc2ts_v2_2024-06-06\x94a}\x94(h\r}\x94\x8c\nRRR_PREFIX\x94K\x00N\x86\x94sh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbh9h6ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\r}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbhHhEhJK\x01hLK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8c9logs/sc2ts_v2_2024-06-06_rewire-recombinants-report.ipynb\x94a}\x94(h\r}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbhZhWub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x1arewire_recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import sc2ts.inference as si
import json
import pandas as pd
import numpy as np
import tszip

In [3]:
rematch_data = snakemake.input[1]

ts_in = tszip.load(snakemake.input[0])
ts_out =  tszip.load(snakemake.input[2])

records = {}
with open(rematch_data) as f:
    for d in json.load(f):
        r = si.RematchRecombinantsLbsResult.fromdict(d)
        records[r.recombinant] = r

In [4]:
tree_in = ts_in.first()
tree_out = ts_out.first()
data = []
for r in records.values():
   
    lbs = r.long_branch_split
    hmm_match = None
    if lbs is None:
        assert len(r.recomb_match.path) == 1
        hmm_match = r.recomb_match
    elif len(lbs.hmm_match.parents) == 1:
        hmm_match = lbs.hmm_match

    if hmm_match is not None:
        old_descendants = tree_in.num_samples(r.recombinant)
        new_descendants = tree_out.num_samples(r.recombinant)
        assert old_descendants == new_descendants
        data.append({
            "recombinant": r.recombinant,
            "num_descendant_samples": old_descendants,
            "rewire_existing": lbs is None,
            "original_muts": len(r.original_match.mutations),
            "new_muts": len(hmm_match.mutations),
        })
df = pd.DataFrame(data).set_index("recombinant")
df["muts_gained"] = df["new_muts"] - df["original_muts"]
df

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1480245,1,True,1,4,3
1499937,1,False,2,5,3
1721379,1,True,3,6,3
1206024,1,True,0,3,3
1432563,1,True,1,4,3
...,...,...,...,...,...
423902,1,True,0,3,3
491791,6,False,0,3,3
314741,3,True,3,3,0
475407,5,True,1,2,1
170980,2,False,3,6,3

In [5]:
ts_in.num_trees, ts_out.num_trees

(514, 466)

In [6]:
ts_out.num_mutations - ts_in.num_mutations

275

In [7]:
ts_out.num_nodes - ts_in.num_nodes

40

# Rewire existing

In [8]:
df["rewire_existing"].value_counts()

rewire_existing
True     71
False    40
Name: count, dtype: int64

In [9]:
df_re = df[df["rewire_existing"]]
df_re

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1480245,1,True,1,4,3
1721379,1,True,3,6,3
1206024,1,True,0,3,3
1432563,1,True,1,4,3
1700939,10,True,1,3,2
...,...,...,...,...,...
22872,1,True,0,3,3
396394,4,True,1,3,2
423902,1,True,0,3,3
314741,3,True,3,3,0
475407,5,True,1,2,1

In [10]:
df_re["muts_gained"].value_counts()

muts_gained
3    42
2    15
1    10
0     4
Name: count, dtype: int64

In [11]:
df_re["muts_gained"].sum()

np.int64(166)

In [12]:
df_re["num_descendant_samples"].value_counts()

num_descendant_samples
1      40
2       8
5       5
4       5
3       3
6       2
10      1
53      1
15      1
58      1
19      1
481     1
27      1
13      1
Name: count, dtype: int64

In [13]:
df_re["num_descendant_samples"].median()

np.float64(1.0)

In [14]:
df_re["num_descendant_samples"].sum()

np.int64(798)

# Rewire long branch splits

In [15]:
df_lbs = df[~df["rewire_existing"]]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1499937,1,False,2,5,3
1110732,5,False,1,3,2
1722023,1,False,0,3,3
1383362,1,False,0,3,3
1326885,1,False,2,5,3
1371979,5,False,1,4,3
1713452,1,False,3,6,3
1163325,1,False,0,3,3
1671821,2,False,3,3,0
1568983,2,False,0,3,3
1673570,1,False,2,3,1
1693578,4,False,2,5,3
1656236,1,False,3,6,3
1239359,15,False,2,2,0
1657206,1,False,0,2,2
1640987,1,False,2,4,2
1655790,1,False,0,3,3
1697371,1,False,1,2,1
1235061,1,False,0,3,3
891730,442777,False,33,19,-14
900541,1,False,2,5,3
951088,1,False,1,4,3
792759,2,False,3,4,1
892608,15,False,12,12,0
870255,4,False,0,1,1
903125,1,False,1,3,2
536875,4,False,0,1,1
903978,5,False,2,3,1
816603,2,False,0,1,1
551161,1,False,2,4,2
94974,8,False,3,4,1
359902,1,False,0,3,3
236335,1,False,2,4,2
402138,248,False,1,3,2
342842,1,False,2,5,3
360842,1,False,0,3,3
209172,33317,False,25,10,-15
385731,23,False,0,3,3
491791,6,False,0,3,3
170980,2,False,3,6,3

In [16]:
df_lbs["muts_gained"].value_counts()

muts_gained
 3     20
 1      8
 2      7
 0      3
-14     1
-15     1
Name: count, dtype: int64

## Look at majority first

In [17]:
df_lbs = df_lbs[df_lbs["muts_gained"] >= 0]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1499937,1,False,2,5,3
1110732,5,False,1,3,2
1722023,1,False,0,3,3
1383362,1,False,0,3,3
1326885,1,False,2,5,3
1371979,5,False,1,4,3
1713452,1,False,3,6,3
1163325,1,False,0,3,3
1671821,2,False,3,3,0
1568983,2,False,0,3,3
1673570,1,False,2,3,1
1693578,4,False,2,5,3
1656236,1,False,3,6,3
1239359,15,False,2,2,0
1657206,1,False,0,2,2
1640987,1,False,2,4,2
1655790,1,False,0,3,3
1697371,1,False,1,2,1
1235061,1,False,0,3,3
900541,1,False,2,5,3
951088,1,False,1,4,3
792759,2,False,3,4,1
892608,15,False,12,12,0
870255,4,False,0,1,1
903125,1,False,1,3,2
536875,4,False,0,1,1
903978,5,False,2,3,1
816603,2,False,0,1,1
551161,1,False,2,4,2
94974,8,False,3,4,1
359902,1,False,0,3,3
236335,1,False,2,4,2
402138,248,False,1,3,2
342842,1,False,2,5,3
360842,1,False,0,3,3
385731,23,False,0,3,3
491791,6,False,0,3,3
170980,2,False,3,6,3

In [18]:
df_lbs["muts_gained"].value_counts()

muts_gained
3    20
1     8
2     7
0     3
Name: count, dtype: int64

In [19]:
df_lbs["muts_gained"].sum()

np.int64(82)

In [20]:
df_lbs["num_descendant_samples"].sum()

np.int64(373)

## Now the outliers

In [21]:
df_lbs = df[~df["rewire_existing"]]
df_lbs = df_lbs[df_lbs["muts_gained"] < 0]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
891730,442777,False,33,19,-14
209172,33317,False,25,10,-15