In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmpdrtxr2py/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x957\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c\x19sc2ts_v2_2024-06-06.trees\x94\x8c)sc2ts_v2_2024-06-06_recombinants_lbs.json\x94\x8c\x1csc2ts_v2_2024-06-06_pr.trees\x94e}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x11h\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94}\x94(h\r}\x94h\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\r}\x94h\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c\x13sc2ts_v2_2024-06-06\x94a}\x94(h\r}\x94\x8c\nRRR_PREFIX\x94K\x00N\x86\x94sh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbh9h6ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\r}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbhHhEhJK\x01hLK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8c9logs/sc2ts_v2_2024-06-06_rewire-recombinants-report.ipynb\x94a}\x94(h\r}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\x0f]\x94(h\x11h\x12eh\x11h\x14)\x81\x94}\x94h\x17h\x11sbh\x12h\x14)\x81\x94}\x94h\x17h\x12sbhZhWub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x1arewire_recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import sc2ts.inference as si
import json
import pandas as pd
import numpy as np
import tszip

In [3]:
rematch_data = snakemake.input[1]

ts_in = tszip.load(snakemake.input[0])
ts_out =  tszip.load(snakemake.input[2])

records = {}
with open(rematch_data) as f:
    for d in json.load(f):
        r = si.RematchRecombinantsLbsResult.fromdict(d)
        records[r.recombinant] = r

In [4]:
tree_in = ts_in.first()
tree_out = ts_out.first()
data = []
for r in records.values():
   
    lbs = r.long_branch_split
    hmm_match = None
    if lbs is None:
        assert len(r.recomb_match.path) == 1
        hmm_match = r.recomb_match
    elif len(lbs.hmm_match.parents) == 1:
        hmm_match = lbs.hmm_match

    if hmm_match is not None:
        assert len(r.original_match.path) == 2
        bp = r.original_match.path[0].right
        tree_in.seek(bp)
        tree_out.seek(bp)
        old_descendants = tree_in.num_samples(r.recombinant)
        new_descendants = tree_out.num_samples(r.recombinant)
        assert old_descendants == new_descendants
        data.append({
            "recombinant": r.recombinant,
            "num_descendant_samples": old_descendants,
            "rewire_existing": lbs is None,
            "original_muts": len(r.original_match.mutations),
            "new_muts": len(hmm_match.mutations),
        })
df = pd.DataFrame(data).set_index("recombinant")
df["muts_gained"] = df["new_muts"] - df["original_muts"]
df

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1117370,62,True,1,3,2
1516169,1,True,2,5,3
1882145,1,True,2,5,3
1212311,1,True,2,5,3
1617364,1,True,0,3,3
...,...,...,...,...,...
150430,1,True,0,1,1
323484,960,True,3,5,2
158153,7,True,2,2,0
461282,4,True,0,3,3
491564,1,True,2,5,3

In [5]:
ts_in.num_trees, ts_out.num_trees

(558, 509)

In [6]:
ts_out.num_mutations - ts_in.num_mutations

331

In [7]:
ts_out.num_nodes - ts_in.num_nodes

33

# Rewire existing

In [8]:
df["rewire_existing"].value_counts()

rewire_existing
True     98
False    33
Name: count, dtype: int64

In [9]:
df_re = df[df["rewire_existing"]]
df_re

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1117370,62,True,1,3,2
1516169,1,True,2,5,3
1882145,1,True,2,5,3
1212311,1,True,2,5,3
1617364,1,True,0,3,3
...,...,...,...,...,...
150430,1,True,0,1,1
323484,960,True,3,5,2
158153,7,True,2,2,0
461282,4,True,0,3,3
491564,1,True,2,5,3

In [10]:
df_re["muts_gained"].value_counts()

muts_gained
 3    55
 2    25
 1    12
 0     5
-2     1
Name: count, dtype: int64

In [11]:
df_re["muts_gained"].sum()

np.int64(225)

In [12]:
df_re["num_descendant_samples"].value_counts()

num_descendant_samples
1      54
3       9
2       7
4       7
5       4
6       3
7       2
62      1
504     1
17      1
53      1
19      1
10      1
31      1
71      1
9       1
8       1
254     1
960     1
Name: count, dtype: int64

In [13]:
df_re["num_descendant_samples"].median()

np.float64(1.0)

In [14]:
df_re["num_descendant_samples"].sum()

np.int64(2173)

# Rewire long branch splits

In [15]:
df_lbs = df[~df["rewire_existing"]]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1331192,1,False,0,3,3
1611543,1,False,2,5,3
1487743,1,False,0,3,3
1475822,5,False,1,4,3
1822688,1,False,2,3,1
1690817,1,False,1,4,3
1683966,2,False,0,3,3
1884216,1,False,0,3,3
1428456,1,False,2,5,3
1195263,5,False,1,3,2
1806148,2,False,3,6,3
1853046,1,False,1,2,1
1253834,1,False,0,3,3
1796313,1,False,2,4,2
1848565,4,False,2,5,3
1692913,1,False,1,4,3
1128051,1,False,2,5,3
563884,6,False,0,1,1
952624,1,False,1,3,2
835957,2,False,3,4,1
961781,1,False,2,5,3
917721,4,False,0,1,1
953540,5,False,2,3,1
941389,17,False,12,12,0
1074491,1,False,1,2,1
940472,504034,False,33,19,-14
1004537,1,False,1,4,3
579362,1,False,2,4,2
217141,628078,False,24,9,-15
230292,5,False,2,3,1
402083,27,False,0,3,3
177427,31,False,3,6,3
20200,1,False,2,4,2

In [16]:
df_lbs["muts_gained"].value_counts()

muts_gained
 3     17
 1      8
 2      5
 0      1
-14     1
-15     1
Name: count, dtype: int64

## Look at majority first

In [17]:
df_lbs = df_lbs[df_lbs["muts_gained"] >= 0]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
1331192,1,False,0,3,3
1611543,1,False,2,5,3
1487743,1,False,0,3,3
1475822,5,False,1,4,3
1822688,1,False,2,3,1
1690817,1,False,1,4,3
1683966,2,False,0,3,3
1884216,1,False,0,3,3
1428456,1,False,2,5,3
1195263,5,False,1,3,2
1806148,2,False,3,6,3
1853046,1,False,1,2,1
1253834,1,False,0,3,3
1796313,1,False,2,4,2
1848565,4,False,2,5,3
1692913,1,False,1,4,3
1128051,1,False,2,5,3
563884,6,False,0,1,1
952624,1,False,1,3,2
835957,2,False,3,4,1
961781,1,False,2,5,3
917721,4,False,0,1,1
953540,5,False,2,3,1
941389,17,False,12,12,0
1074491,1,False,1,2,1
1004537,1,False,1,4,3
579362,1,False,2,4,2
230292,5,False,2,3,1
402083,27,False,0,3,3
177427,31,False,3,6,3
20200,1,False,2,4,2

In [18]:
df_lbs["muts_gained"].value_counts()

muts_gained
3    17
1     8
2     5
0     1
Name: count, dtype: int64

In [19]:
df_lbs["muts_gained"].sum()

np.int64(69)

In [20]:
df_lbs["num_descendant_samples"].sum()

np.int64(133)

## Now the outliers

In [21]:
df_lbs = df[~df["rewire_existing"]]
df_lbs = df_lbs[df_lbs["muts_gained"] < 0]
df_lbs

,num_descendant_samples,rewire_existing,original_muts,new_muts,muts_gained
recombinant,,,,,
940472,504034,False,33,19,-14
217141,628078,False,24,9,-15