In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/sbk774/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmp7_cjy87l/file/gpfs3/well/kelleher/users/sbk774/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/sbk774/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x95k\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94\x8c6sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated.trees\x94a}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x0fh\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8cAsc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants.csv\x94a}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c0sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated\x94a}\x94(h\x0b}\x94\x8c\x0bRECR_PREFIX\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbh8h5ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0b}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhGhDhIK\x01hKK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8cOlogs/sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants_report.ipynb\x94a}\x94(h\x0b}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhYhVub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x13recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cJ/gpfs3/well/kelleher/users/sbk774/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/sbk774/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import tszip
import sc2ts.debug as sd
import pandas as pd

In [3]:
ts = tszip.load(snakemake.input[0])
ts

In [4]:
ti = sd.ArgInfo(ts, show_progress=False, pango_source="pango", scorpio_source="scorpio")
ti

In [5]:
dfr = ti.recombinants_summary(show_progress=False)

RE: 132996 interval right shifted from 22227 to 21765

RE: 242319 has more than two parents. Skipping.

RE: 376401 interval right shifted from 28255 to 28252

RE: 462279 interval_right >= interval_left; moving from 22027to 22026

RE: 465566 interval right shifted from 22030 to 22029

RE: 482354 interval_right >= interval_left; moving from 22027to 22026

RE: 513386 interval_right >= interval_left; moving from 22027to 22026

RE: 523559 interval right shifted from 22030 to 22029

RE: 557790 interval_right >= interval_left; moving from 22027to 22026

RE: 571211 interval right shifted from 25046 to 22194

RE: 604986 interval_right >= interval_left; moving from 22027to 22026

RE: 609423 interval right shifted from 22030 to 22029

RE: 609427 interval_right >= interval_left; moving from 22027to 22026

RE: 628342 interval_right >= interval_left; moving from 22027to 22026

RE: 655511 interval_right >= interval_left; moving from 22027to 22026

RE: 656274 interval_right >= interval_left; moving from 22027to 22026

RE: 698384 interval_right >= interval_left; moving from 22027to 22026

RE: 708357 interval right shifted from 22030 to 22029

RE: 708528 interval_right >= interval_left; moving from 22027to 22026

RE: 714048 interval right shifted from 22030 to 22029

RE: 723583 interval_right >= interval_left; moving from 22027to 22026

RE: 726240 interval right shifted from 22030 to 22029

RE: 731011 interval_right >= interval_left; moving from 22027to 22026

RE: 739374 interval_right >= interval_left; moving from 22027to 22026

RE: 742999 interval right shifted from 22030 to 22029

RE: 744648 interval_right >= interval_left; moving from 22027to 22026

RE: 749059 interval_right >= interval_left; moving from 22027to 22026

RE: 749096 interval_right >= interval_left; moving from 22027to 22026

RE: 752968 interval_right >= interval_left; moving from 22027to 22026

RE: 760307 interval right shifted from 22030 to 22029

RE: 760333 interval_right >= interval_left; moving from 22027to 22026

RE: 761064 interval_right >= interval_left; moving from 22027to 22026

RE: 764318 interval_right >= interval_left; moving from 22027to 22026

RE: 764357 interval_right >= interval_left; moving from 22027to 22026

RE: 769519 interval_right >= interval_left; moving from 22027to 22026

RE: 779255 interval right shifted from 22030 to 22029

RE: 779361 interval_right >= interval_left; moving from 22027to 22026

RE: 796998 interval_right >= interval_left; moving from 22027to 22026

RE: 820465 interval right shifted from 22030 to 22029

RE: 853425 interval_right >= interval_left; moving from 22027to 22026

RE: 853625 interval_right >= interval_left; moving from 22027to 22026

RE: 859224 interval_right >= interval_left; moving from 22027to 22026

RE: 859533 interval_right >= interval_left; moving from 22027to 22026

RE: 864858 interval_right >= interval_left; moving from 22027to 22026

RE: 865155 interval_right >= interval_left; moving from 22027to 22026

RE: 873890 interval_right >= interval_left; moving from 22027to 22026

RE: 927344 interval_right >= interval_left; moving from 22027to 22026

RE: 944743 interval_right >= interval_left; moving from 22027to 22026

RE: 951680 interval right shifted from 22030 to 22029

RE: 963603 interval_right >= interval_left; moving from 22027to 22026

RE: 963649 interval_right >= interval_left; moving from 22027to 22026

RE: 978071 interval_right >= interval_left; moving from 22027to 22026

RE: 1024281 interval_right >= interval_left; moving from 22027to 22026

RE: 1029213 interval_right >= interval_left; moving from 22027to 22026

RE: 1061146 interval right shifted from 22227 to 22194

RE: 1061146 interval_right >= interval_left; moving from 22196to 22193

RE: 1073563 interval right shifted from 11537 to 11283

RE: 1097940 interval right shifted from 22197 to 22194

RE: 1125906 interval right shifted from 22197 to 22194

RE: 1125908 interval right shifted from 22197 to 22194

RE: 1132049 interval right shifted from 7393 to 6513

RE: 1152127 interval right shifted from 22195 to 22029

RE: 1183015 interval right shifted from 22197 to 22194

RE: 1193667 interval right shifted from 22197 to 22194

RE: 1204454 interval right shifted from 22197 to 22194

RE: 1205099 interval right shifted from 22197 to 22194

RE: 1215389 interval right shifted from 22197 to 22194

RE: 1216144 interval right shifted from 22197 to 22194

RE: 1233233 interval right shifted from 22197 to 22194

RE: 1237090 interval right shifted from 22197 to 22194

RE: 1237783 interval right shifted from 11537 to 11283

RE: 1237930 interval right shifted from 22197 to 22195

RE: 1237930 interval_right >= interval_left; moving from 22196to 22194

RE: 1240531 interval right shifted from 22197 to 22194

RE: 1241580 interval right shifted from 22197 to 21766

RE: 1241580 interval_right >= interval_left; moving from 21767to 21765

RE: 1245775 interval right shifted from 22197 to 22194

RE: 1245893 interval right shifted from 22197 to 22194

RE: 1254682 interval right shifted from 22197 to 22194

RE: 1254692 interval right shifted from 22199 to 22194

RE: 1259945 interval right shifted from 22197 to 22194

RE: 1260191 interval right shifted from 22197 to 22194

RE: 1265117 interval right shifted from 22197 to 22194

RE: 1265161 interval right shifted from 22197 to 22194

RE: 1266068 interval right shifted from 22197 to 22194

RE: 1266068 interval_right >= interval_left; moving from 22195to 22193

RE: 1269371 interval right shifted from 22197 to 22194

RE: 1276747 interval right shifted from 22197 to 22194

RE: 1283670 interval_right >= interval_left; moving from 22197to 22196

RE: 1283727 interval right shifted from 22197 to 22194

RE: 1283736 interval right shifted from 22197 to 22194

RE: 1287553 interval right shifted from 22197 to 22194

RE: 1287925 interval right shifted from 22197 to 22194

RE: 1292106 interval right shifted from 22197 to 22194

RE: 1296604 interval right shifted from 22197 to 22194

RE: 1296649 interval right shifted from 22197 to 22194

RE: 1300132 interval right shifted from 22197 to 22194

RE: 1300137 interval right shifted from 22197 to 22194

RE: 1302534 interval right shifted from 22197 to 22194

RE: 1302795 interval right shifted from 22195 to 22194

RE: 1302797 interval right shifted from 22195 to 22194

RE: 1302799 interval right shifted from 22195 to 22194

RE: 1305051 interval right shifted from 22197 to 22194

RE: 1306808 interval right shifted from 22197 to 22194

RE: 1306814 interval right shifted from 22197 to 22194

RE: 1306889 interval right shifted from 22197 to 22194

RE: 1307003 interval right shifted from 22197 to 22194

RE: 1308795 interval right shifted from 8260 to 6513

RE: 1309806 interval right shifted from 22197 to 22194

RE: 1309808 interval right shifted from 22197 to 22194

RE: 1312717 interval right shifted from 22197 to 22194

RE: 1312735 interval right shifted from 22197 to 22194

RE: 1319267 interval_right >= interval_left; moving from 22197to 22196

RE: 1319300 interval right shifted from 22197 to 22194

RE: 1319419 interval right shifted from 22197 to 22194

RE: 1323065 interval right shifted from 22195 to 22194

RE: 1333074 interval right shifted from 22197 to 22194

RE: 1333486 interval right shifted from 22197 to 22194

RE: 1333542 interval right shifted from 22197 to 22194

RE: 1337067 interval right shifted from 22197 to 22194

RE: 1344215 interval right shifted from 22197 to 22194

RE: 1344320 interval right shifted from 22197 to 22194

RE: 1347827 interval right shifted from 22197 to 22194

RE: 1357232 interval right shifted from 22197 to 22194

RE: 1360661 interval right shifted from 22197 to 22194

RE: 1364172 interval right shifted from 22197 to 22194

RE: 1364261 interval right shifted from 22197 to 22194

RE: 1373835 interval right shifted from 22197 to 22194

RE: 1373851 interval right shifted from 22197 to 22194

RE: 1379306 interval right shifted from 22197 to 22194

RE: 1379639 interval right shifted from 11537 to 11283

RE: 1382805 interval right shifted from 22197 to 22194

RE: 1382957 interval right shifted from 22197 to 22194

RE: 1386235 interval right shifted from 22197 to 22194

RE: 1396671 interval right shifted from 22197 to 22194

RE: 1400016 interval right shifted from 22197 to 22194

RE: 1404827 interval right shifted from 22197 to 22194

RE: 1410413 interval right shifted from 22197 to 22194

RE: 1412023 interval right shifted from 22197 to 22194

RE: 1418629 interval right shifted from 22197 to 22194

RE: 1422942 interval right shifted from 22197 to 22194

RE: 1431268 interval right shifted from 9693 to 6513

RE: 1436977 interval right shifted from 22197 to 22194

RE: 1441955 interval right shifted from 22197 to 22194

RE: 1443784 interval right shifted from 22197 to 22194

RE: 1444462 interval right shifted from 11537 to 11283

RE: 1446726 interval right shifted from 22197 to 22194

RE: 1446986 interval right shifted from 11537 to 11283

RE: 1521456 interval right shifted from 22792 to 21765

RE: 1556492 interval right shifted from 22917 to 21765

RE: 1631476 interval right shifted from 22917 to 21765

RE: 1698581 interval right shifted from 22001 to 21765

RE: 1719457 interval right shifted from 21810 to 21765

RE: 1723601 has more than two parents. Skipping.

RE: 1727022 has more than two parents. Skipping.

RE: 1758239 interval right shifted from 22001 to 21765

RE: 1759571 interval right shifted from 22001 to 21765

RE: 1854754 has more than two parents. Skipping.

RE: 1873163 interval right shifted from 22295 to 22194

RE: 1876328 interval_right >= interval_left; moving from 21620to 21619

RE: 1884625 interval_right >= interval_left; moving from 21625to 21624

RE: 1888989 interval_right >= interval_left; moving from 21625to 21624

In [6]:
dfr

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,oldest_child,oldest_child_pango,oldest_child_scorpio,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date
860,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,2022-04-15,...,1438484,BA.2,Omicron (BA.2-like),783.0,2022-04-15,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
919,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,2022-06-27,...,1540097,BA.4.1,Omicron (BA.4-like),710.0,2022-06-27,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
402,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,2021-10-21,...,752969,AY.44,Delta (B.1.617.2-like),959.0,2021-10-21,167127,B.1.617.2,Delta (B.1.617.2-like),1268.824906,2020-12-16
1023,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,2022-08-30,...,1639592,BA.4,Omicron (BA.4-like),646.0,2022-08-30,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
1175,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,2023-03-20,...,1798226,DV.6,Omicron (BA.2-like),444.0,2023-03-20,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,2023-01-20,...,1750110,BQ.1.1,Omicron (BA.5-like),503.0,2023-01-20,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
1152,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,2023-01-30,...,1756401,EF.1,Omicron (BA.5-like),493.0,2023-01-30,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
936,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,2022-07-06,...,1556609,BA.5.2.1,Omicron (BA.5-like),701.0,2022-07-06,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11
681,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,2022-01-29,...,1179997,BA.1.17,Omicron (BA.1-like),859.0,2022-01-29,68,B.1,.,1591.684194,2020-01-28
1162,ERR11006399,1,1,1,28704,29754,3,COVID-ARTIC-V4.1,.,2023-02-16,...,1771530,FY.1,Omicron (XBB.1-like),476.0,2023-02-16,871743,B.1.1.529,Omicron (Unassigned),1334.549092,2020-10-11

In [7]:
dfr.describe()

,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,group_size,recombinant,recombinant_time,recombinant_date,...,parent_left_date,parent_right,parent_right_time,parent_right_date,oldest_child,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_time,parent_mrca_date
count,1320.000000,1320.000000,1320.000000,1320.000000,1320.000000,1320.000000,1320.000000,1.320000e+03,1320.000000,1320,...,1320,1.320000e+03,1320.000000,1320,1.320000e+03,1320.000000,1320,1.320000e+03,1320.000000,1320
mean,463.268939,1.112879,1.000758,18624.231818,21006.023485,1.412121,2.127273,1.132745e+06,811.865388,2022-03-17 11:38:10,...,2022-02-03 15:42:32,9.645663e+05,892.727320,2021-12-26 09:45:49,1.142785e+06,796.394541,2022-04-01 15:07:38,6.671082e+05,1103.328841,2021-05-30 07:17:27
min,1.000000,1.000000,1.000000,223.000000,670.000000,0.000000,2.000000,1.894000e+03,31.263776,2020-03-18 00:00:00,...,2020-02-23 00:00:00,1.067000e+03,93.000000,2019-12-26 00:00:00,1.893000e+03,29.000000,2020-03-22 00:00:00,1.000000e+00,232.144988,2019-12-26 00:00:00
25%,1.000000,1.000000,1.000000,14828.500000,21610.000000,1.000000,2.000000,7.150128e+05,693.993302,2021-09-27 00:00:00,...,2021-08-22 00:00:00,4.112375e+05,759.000000,2021-06-29 00:00:00,7.193022e+05,680.000000,2021-10-11 18:00:00,1.671270e+05,961.932564,2020-12-16 00:00:00
50%,1.000000,1.000000,1.000000,21596.000000,22027.000000,1.000000,2.000000,1.130134e+06,879.841556,2022-01-08 12:00:00,...,2021-12-05 12:00:00,1.029406e+06,920.000000,2021-11-29 00:00:00,1.154637e+06,870.500000,2022-01-17 12:00:00,8.717290e+05,1268.824906,2020-12-16 00:00:00
75%,3.000000,1.000000,1.000000,22035.000000,24208.000000,2.000000,2.000000,1.608590e+06,983.425142,2022-07-13 06:00:00,...,2022-05-29 00:00:00,1.508922e+06,1073.000000,2022-05-09 00:00:00,1.616353e+06,968.250000,2022-07-27 00:00:00,8.717430e+05,1268.824906,2021-10-19 00:00:00
max,244601.000000,17.000000,2.000000,29701.000000,29754.000000,14.000000,21.000000,1.892451e+06,1541.000000,2024-05-06 00:00:00,...,2024-05-01 00:00:00,1.890542e+06,1624.000000,2024-03-05 00:00:00,3.421966e+06,1537.000000,2024-05-08 00:00:00,1.855189e+06,1624.000000,2023-10-28 00:00:00
std,9995.170045,0.789517,0.027524,6594.585351,5978.287142,1.160967,0.972954,5.024594e+05,260.459091,NaN,...,NaN,5.647325e+05,274.572223,NaN,5.131623e+05,260.957576,NaN,5.540300e+05,279.976402,NaN

In [8]:
dfr.to_csv(snakemake.output[0]);