In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmpaepk6_4x/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x95z\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94\x8c6sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated.trees\x94a}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x0fh\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8cAsc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants.csv\x94a}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c0sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated\x94a}\x94(h\x0b}\x94\x8c\x0bRECR_PREFIX\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbh8h5ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0b}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhGhDhIK\x01hKK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8cOlogs/sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants_report.ipynb\x94a}\x94(h\x0b}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhYhVub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x13recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import tszip
import sc2ts.debug as sd
import pandas as pd

In [3]:
ts = tszip.load(snakemake.input[0])
ts

In [4]:
ti = sd.ArgInfo(ts, show_progress=False, pango_source="pango", scorpio_source="scorpio")
ti

In [5]:
dfr = ti.recombinants_summary(show_progress=False)

RE: 132899 interval right shifted from 22227 to 21765

RE: 242115 has more than two parents. Skipping.

RE: 374839 interval right shifted from 28255 to 28252

RE: 462380 interval_right >= interval_left; moving from 22027to 22026

RE: 465856 interval right shifted from 22030 to 22029

RE: 482611 interval_right >= interval_left; moving from 22027to 22026

RE: 513378 interval_right >= interval_left; moving from 22027to 22026

RE: 523725 interval right shifted from 22030 to 22029

RE: 557894 interval_right >= interval_left; moving from 22027to 22026

RE: 571227 interval right shifted from 25046 to 22194

RE: 605265 interval_right >= interval_left; moving from 22027to 22026

RE: 609567 interval right shifted from 22030 to 22029

RE: 609571 interval_right >= interval_left; moving from 22027to 22026

RE: 628766 interval_right >= interval_left; moving from 22027to 22026

RE: 655648 interval_right >= interval_left; moving from 22027to 22026

RE: 656456 interval_right >= interval_left; moving from 22027to 22026

RE: 698662 interval_right >= interval_left; moving from 22027to 22026

RE: 708398 interval right shifted from 22030 to 22029

RE: 708631 interval_right >= interval_left; moving from 22027to 22026

RE: 714173 interval right shifted from 22030 to 22029

RE: 723905 interval_right >= interval_left; moving from 22027to 22026

RE: 726372 interval right shifted from 22030 to 22029

RE: 731290 interval_right >= interval_left; moving from 22027to 22026

RE: 739926 interval_right >= interval_left; moving from 22027to 22026

RE: 743461 interval right shifted from 22030 to 22029

RE: 745267 interval_right >= interval_left; moving from 22027to 22026

RE: 749747 interval_right >= interval_left; moving from 22027to 22026

RE: 749784 interval_right >= interval_left; moving from 22027to 22026

RE: 753469 interval_right >= interval_left; moving from 22027to 22026

RE: 760683 interval right shifted from 22030 to 22029

RE: 760710 interval_right >= interval_left; moving from 22027to 22026

RE: 761491 interval_right >= interval_left; moving from 22027to 22026

RE: 764869 interval_right >= interval_left; moving from 22027to 22026

RE: 764908 interval_right >= interval_left; moving from 22027to 22026

RE: 770197 interval_right >= interval_left; moving from 22027to 22026

RE: 779985 interval right shifted from 22030 to 22029

RE: 780089 interval_right >= interval_left; moving from 22027to 22026

RE: 798011 interval_right >= interval_left; moving from 22027to 22026

RE: 821489 interval right shifted from 22030 to 22029

RE: 854651 interval_right >= interval_left; moving from 22027to 22026

RE: 854847 interval_right >= interval_left; moving from 22027to 22026

RE: 860413 interval_right >= interval_left; moving from 22027to 22026

RE: 860716 interval_right >= interval_left; moving from 22027to 22026

RE: 865698 interval_right >= interval_left; moving from 22027to 22026

RE: 865984 interval_right >= interval_left; moving from 22027to 22026

RE: 874963 interval_right >= interval_left; moving from 22027to 22026

RE: 928374 interval_right >= interval_left; moving from 22027to 22026

RE: 945701 interval_right >= interval_left; moving from 22027to 22026

RE: 953406 interval right shifted from 22030 to 22029

RE: 964786 interval_right >= interval_left; moving from 22027to 22026

RE: 964832 interval_right >= interval_left; moving from 22027to 22026

RE: 979069 interval_right >= interval_left; moving from 22027to 22026

RE: 1024949 interval_right >= interval_left; moving from 22027to 22026

RE: 1029695 interval_right >= interval_left; moving from 22027to 22026

RE: 1070426 interval right shifted from 11537 to 11283

RE: 1099083 interval right shifted from 22195 to 22194

RE: 1128444 interval right shifted from 22195 to 22194

RE: 1128446 interval right shifted from 22195 to 22194

RE: 1134806 interval right shifted from 7393 to 6513

RE: 1155453 interval right shifted from 22578 to 22029

RE: 1186478 interval right shifted from 22197 to 22194

RE: 1186478 interval_right >= interval_left; moving from 22196to 22193

RE: 1196901 interval right shifted from 22197 to 22194

RE: 1196901 interval_right >= interval_left; moving from 22196to 22193

RE: 1208018 interval right shifted from 22197 to 22194

RE: 1208018 interval_right >= interval_left; moving from 22196to 22193

RE: 1208682 interval right shifted from 22197 to 22194

RE: 1208682 interval_right >= interval_left; moving from 22196to 22193

RE: 1219014 interval right shifted from 22195 to 22194

RE: 1219198 interval right shifted from 22197 to 22194

RE: 1219198 interval_right >= interval_left; moving from 22196to 22193

RE: 1236369 interval right shifted from 22195 to 22194

RE: 1239071 interval right shifted from 11537 to 11283

RE: 1240644 interval right shifted from 22197 to 22194

RE: 1240644 interval_right >= interval_left; moving from 22196to 22193

RE: 1244008 interval right shifted from 22197 to 22194

RE: 1244008 interval_right >= interval_left; moving from 22196to 22193

RE: 1245185 interval right shifted from 22197 to 21766

RE: 1245185 interval_right >= interval_left; moving from 22196to 21765

RE: 1249360 interval right shifted from 22197 to 22194

RE: 1249360 interval_right >= interval_left; moving from 22196to 22193

RE: 1249463 interval right shifted from 22195 to 22194

RE: 1258703 interval right shifted from 22195 to 22194

RE: 1263649 interval right shifted from 22197 to 22194

RE: 1263649 interval_right >= interval_left; moving from 22196to 22193

RE: 1263875 interval right shifted from 22195 to 22194

RE: 1268585 interval right shifted from 22197 to 22194

RE: 1268585 interval_right >= interval_left; moving from 22196to 22193

RE: 1268852 interval right shifted from 22195 to 22194

RE: 1268898 interval right shifted from 22195 to 22194

RE: 1273019 interval right shifted from 22195 to 22194

RE: 1280399 interval right shifted from 22195 to 22194

RE: 1280434 interval right shifted from 22195 to 22194

RE: 1287258 interval right shifted from 22195 to 22194

RE: 1287319 interval right shifted from 22197 to 22194

RE: 1287319 interval_right >= interval_left; moving from 22196to 22193

RE: 1287330 interval right shifted from 22197 to 22194

RE: 1287330 interval_right >= interval_left; moving from 22196to 22193

RE: 1291461 interval right shifted from 22197 to 22194

RE: 1291461 interval_right >= interval_left; moving from 22196to 22193

RE: 1291855 interval right shifted from 22197 to 22194

RE: 1291855 interval_right >= interval_left; moving from 22196to 22193

RE: 1296017 interval right shifted from 22197 to 22194

RE: 1296017 interval_right >= interval_left; moving from 22196to 22193

RE: 1300270 interval right shifted from 22197 to 22194

RE: 1300270 interval_right >= interval_left; moving from 22196to 22193

RE: 1300315 interval right shifted from 22197 to 22194

RE: 1300315 interval_right >= interval_left; moving from 22196to 22193

RE: 1303909 interval right shifted from 22195 to 22194

RE: 1303914 interval right shifted from 22195 to 22194

RE: 1305970 interval right shifted from 22195 to 22194

RE: 1305979 interval right shifted from 22195 to 22194

RE: 1306394 interval right shifted from 22195 to 22194

RE: 1306396 interval right shifted from 22195 to 22194

RE: 1306398 interval right shifted from 22195 to 22194

RE: 1308518 interval right shifted from 22195 to 22194

RE: 1310232 interval right shifted from 22195 to 22194

RE: 1310263 interval right shifted from 22197 to 22194

RE: 1310263 interval_right >= interval_left; moving from 22196to 22193

RE: 1310277 interval right shifted from 22197 to 22194

RE: 1310277 interval_right >= interval_left; moving from 22196to 22193

RE: 1310279 interval right shifted from 22197 to 22194

RE: 1310279 interval_right >= interval_left; moving from 22196to 22193

RE: 1310429 interval right shifted from 22197 to 22194

RE: 1310429 interval_right >= interval_left; moving from 22196to 22193

RE: 1312418 interval right shifted from 8260 to 6513

RE: 1313529 interval right shifted from 22195 to 22194

RE: 1313531 interval right shifted from 22195 to 22194

RE: 1313535 interval right shifted from 22195 to 22194

RE: 1316047 interval right shifted from 22195 to 22194

RE: 1316175 interval right shifted from 22195 to 22194

RE: 1316201 interval right shifted from 22195 to 22194

RE: 1316204 interval right shifted from 22195 to 22194

RE: 1316220 interval right shifted from 22195 to 22194

RE: 1322643 interval right shifted from 22197 to 22194

RE: 1322643 interval_right >= interval_left; moving from 22196to 22193

RE: 1322797 interval right shifted from 22197 to 22194

RE: 1322797 interval_right >= interval_left; moving from 22196to 22193

RE: 1326793 interval right shifted from 22195 to 22194

RE: 1336743 interval right shifted from 22195 to 22194

RE: 1337328 interval right shifted from 22197 to 22194

RE: 1337328 interval_right >= interval_left; moving from 22196to 22193

RE: 1337378 interval right shifted from 22195 to 22194

RE: 1340951 interval right shifted from 22195 to 22194

RE: 1348125 interval right shifted from 22197 to 22194

RE: 1348125 interval_right >= interval_left; moving from 22196to 22193

RE: 1348367 interval right shifted from 22197 to 22194

RE: 1348367 interval_right >= interval_left; moving from 22196to 22193

RE: 1351435 interval right shifted from 22195 to 22194

RE: 1351439 interval right shifted from 22195 to 22194

RE: 1361117 interval right shifted from 22195 to 22194

RE: 1364241 interval right shifted from 22195 to 22194

RE: 1364243 interval right shifted from 22195 to 22194

RE: 1367508 interval right shifted from 22197 to 22194

RE: 1367508 interval_right >= interval_left; moving from 22196to 22193

RE: 1367701 interval right shifted from 22197 to 22194

RE: 1367701 interval_right >= interval_left; moving from 22196to 22193

RE: 1377509 interval right shifted from 22197 to 22194

RE: 1377509 interval_right >= interval_left; moving from 22196to 22193

RE: 1377528 interval right shifted from 22195 to 22194

RE: 1382306 interval right shifted from 11537 to 11283

RE: 1382743 interval right shifted from 22197 to 22194

RE: 1382743 interval_right >= interval_left; moving from 22196to 22193

RE: 1386246 interval right shifted from 22195 to 22194

RE: 1386627 interval right shifted from 22195 to 22194

RE: 1389603 interval right shifted from 22195 to 22194

RE: 1400242 interval right shifted from 22195 to 22194

RE: 1403690 interval right shifted from 22195 to 22194

RE: 1403705 interval right shifted from 22195 to 22194

RE: 1409567 interval right shifted from 22195 to 22194

RE: 1409572 interval right shifted from 22195 to 22194

RE: 1409861 interval right shifted from 22195 to 22194

RE: 1413994 interval right shifted from 22195 to 22194

RE: 1415622 interval right shifted from 22197 to 22194

RE: 1415622 interval_right >= interval_left; moving from 22196to 22193

RE: 1420035 interval right shifted from 22195 to 22194

RE: 1422713 interval right shifted from 22195 to 22194

RE: 1425126 interval right shifted from 22195 to 22194

RE: 1426618 interval right shifted from 22195 to 22194

RE: 1434677 interval right shifted from 9693 to 6513

RE: 1437187 interval right shifted from 22195 to 22194

RE: 1440384 interval right shifted from 22195 to 22194

RE: 1445412 interval right shifted from 22195 to 22194

RE: 1447247 interval right shifted from 22195 to 22194

RE: 1447759 interval right shifted from 11537 to 11283

RE: 1450015 interval right shifted from 11537 to 11283

RE: 1450588 interval right shifted from 22195 to 22194

RE: 1452563 interval right shifted from 22195 to 22194

RE: 1455940 interval right shifted from 22195 to 22194

RE: 1467261 interval right shifted from 22195 to 22194

RE: 1523675 interval right shifted from 22792 to 21765

RE: 1559772 interval right shifted from 22917 to 21765

RE: 1633997 interval right shifted from 22917 to 21765

RE: 1701815 interval right shifted from 22001 to 21765

RE: 1722702 interval right shifted from 21810 to 21765

RE: 1726834 has more than two parents. Skipping.

RE: 1730254 has more than two parents. Skipping.

RE: 1761475 interval right shifted from 22001 to 21765

RE: 1762728 interval right shifted from 22001 to 21765

RE: 1857980 has more than two parents. Skipping.

RE: 1876385 interval right shifted from 22295 to 22194

RE: 1879554 interval_right >= interval_left; moving from 21620to 21619

RE: 1887849 interval_right >= interval_left; moving from 21625to 21624

RE: 1892214 interval_right >= interval_left; moving from 21625to 21624

In [6]:
dfr

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,oldest_child,oldest_child_pango,oldest_child_scorpio,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date
875,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,2022-04-15,...,1441962,BA.2,Omicron (BA.2-like),783.0,2022-04-15,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
939,ERR9939974,17,1,1,695,958,1,COVID-ARTIC-V4.1,.,2022-06-27,...,1543487,BA.4.1,Omicron (BA.4-like),710.0,2022-06-27,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
403,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,2021-10-21,...,753470,AY.44,Delta (B.1.617.2-like),959.0,2021-10-21,242168,B.1.617.2,Delta (B.1.617.2-like),1273.399240,2020-12-11
1192,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,2023-03-20,...,1801170,DV.6,Omicron (BA.2-like),444.0,2023-03-20,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
1032,ERR10150242,1,1,1,695,1598,1,COVID-ARTIC-V4.1,.,2022-08-21,...,1630770,BA.4,Omicron (BA.4-like),655.0,2022-08-21,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,SRR18234565,16,2,1,25923,29734,2,COVID-VARSKIP-V1a-2b,.,2022-02-08,...,1337547,BA.1.18,Omicron (BA.1-like),868.0,2022-01-20,898614,BA.1,Omicron (BA.1-like),953.290830,2021-10-27
1170,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,2023-01-30,...,1759454,EF.1,Omicron (BA.5-like),493.0,2023-01-30,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
953,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,2022-07-06,...,1558617,BA.5.2.1,Omicron (BA.5-like),701.0,2022-07-06,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
1163,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,2023-01-20,...,1753016,BQ.1.1,Omicron (BA.5-like),503.0,2023-01-20,1896655,B.1.1.529,Probable Omicron (Unassigned),1492.502163,2020-05-06
680,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,2022-01-29,...,1182939,BA.1.17,Omicron (BA.1-like),859.0,2022-01-29,67,B.1,.,1591.515332,2020-01-28

In [7]:
dfr.describe()

,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,group_size,recombinant,recombinant_time,recombinant_date,...,parent_left_date,parent_right,parent_right_time,parent_right_date,oldest_child,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_time,parent_mrca_date
count,1.337000e+03,1337.000000,1337.000000,1337.000000,1337.000000,1337.000000,1337.000000,1.337000e+03,1337.000000,1337,...,1337,1.337000e+03,1337.000000,1337,1.337000e+03,1337.000000,1337,1.337000e+03,1337.000000,1337
mean,1.386023e+03,1.130142,1.002244,18752.590875,21042.880329,1.412865,2.154076,1.136736e+06,812.063749,2022-03-17 06:48:11,...,2022-02-04 12:16:41,9.698725e+05,891.195310,2021-12-27 22:32:45,1.144892e+06,796.993071,2022-04-01 00:45:14,8.089401e+05,1111.509354,2021-05-21 20:19:12
min,1.000000e+00,1.000000,1.000000,223.000000,670.000000,0.000000,2.000000,1.844000e+03,31.263776,2020-03-18 00:00:00,...,2020-02-24 00:00:00,1.072000e+03,93.000000,2019-12-26 00:00:00,1.843000e+03,29.000000,2020-03-22 00:00:00,1.000000e+00,231.072115,2019-12-26 00:00:00
25%,1.000000e+00,1.000000,1.000000,15238.000000,21610.000000,1.000000,2.000000,7.167010e+05,697.956544,2021-09-28 00:00:00,...,2021-08-23 00:00:00,4.110590e+05,759.000000,2021-06-30 00:00:00,7.239040e+05,682.000000,2021-10-12 00:00:00,2.421680e+05,922.010023,2020-12-11 00:00:00
50%,1.000000e+00,1.000000,1.000000,21596.000000,22027.000000,1.000000,2.000000,1.155720e+06,877.000000,2022-01-11 00:00:00,...,2021-12-12 00:00:00,1.043149e+06,915.000000,2021-12-04 00:00:00,1.181756e+06,869.000000,2022-01-19 00:00:00,8.986140e+05,1273.399240,2020-12-11 00:00:00
75%,3.000000e+00,1.000000,1.000000,22193.000000,23987.000000,2.000000,2.000000,1.598516e+06,982.839065,2022-07-10 00:00:00,...,2022-05-24 00:00:00,1.509856e+06,1072.000000,2022-05-09 00:00:00,1.611650e+06,968.000000,2022-07-25 00:00:00,1.412770e+06,1273.399240,2021-11-27 00:00:00
max,1.241363e+06,38.000000,4.000000,29701.000000,29751.000000,14.000000,53.000000,1.895676e+06,1541.000000,2024-05-06 00:00:00,...,2024-05-01 00:00:00,1.893765e+06,1624.000000,2024-03-05 00:00:00,3.422505e+06,1537.000000,2024-05-08 00:00:00,1.896655e+06,1624.000000,2023-10-28 00:00:00
std,3.536184e+04,1.248758,0.082046,6484.992531,5872.025344,1.194454,1.667823,5.015926e+05,259.013404,NaN,...,NaN,5.635638e+05,272.741455,NaN,5.083309e+05,259.451251,NaN,6.406321e+05,305.255209,NaN

In [8]:
dfr.to_csv(snakemake.output[0]);