In [1]:
######## snakemake preamble start (automatically inserted, do not edit) ########
import sys;sys.path.extend(['/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing', '/gpfs3/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/bin', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/lib-dynload', '/users/kelleher/sbk774/.local/lib/python3.12/site-packages', '/well/kelleher/users/sbk774/conda/skylake/envs/sc2ts/lib/python3.12/site-packages', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/src/pangonet/src', '/users/kelleher/sbk774/.cache/snakemake/snakemake/source-cache/snakemake-runtime-cache/tmpp_4sudn0/file/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks', '/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks']);import pickle;snakemake = pickle.loads(b'\x80\x04\x95z\x04\x00\x00\x00\x00\x00\x00\x8c\x16snakemake.iocontainers\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94h\x00\x8c\nInputFiles\x94\x93\x94)\x81\x94\x8c6sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated.trees\x94a}\x94(\x8c\x06_names\x94}\x94\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x0fh\x00\x8c\x0eAttributeGuard\x94\x93\x94)\x81\x94}\x94\x8c\x04name\x94h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\x06output\x94h\x00\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94\x8cAsc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants.csv\x94a}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_store\x94h\x00\x8c\x06Params\x94\x93\x94)\x81\x94}\x94(h\x0b}\x94h\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbub\x8c\r_params_types\x94}\x94\x8c\twildcards\x94h\x00\x8c\tWildcards\x94\x93\x94)\x81\x94\x8c0sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated\x94a}\x94(h\x0b}\x94\x8c\x0bRECR_PREFIX\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbh8h5ub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x00\x8c\x0cResourceList\x94\x93\x94)\x81\x94(\x8c\x04/tmp\x94K\x01K\x01e}\x94(h\x0b}\x94(\x8c\x06tmpdir\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06_cores\x94K\x02N\x86\x94uh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhGhDhIK\x01hKK\x01ub\x8c\x03log\x94h\x00\x8c\x03Log\x94\x93\x94)\x81\x94\x8cOlogs/sc2ts_v2_2024-06-06_pr_pp_mp_aph_bps_pango_dated_recombinants_report.ipynb\x94a}\x94(h\x0b}\x94\x8c\x08notebook\x94K\x00N\x86\x94sh\r]\x94(h\x0fh\x10eh\x0fh\x12)\x81\x94}\x94h\x15h\x0fsbh\x10h\x12)\x81\x94}\x94h\x15h\x10sbhYhVub\x8c\x06config\x94}\x94\x8c\x04rule\x94\x8c\x13recombinants_report\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cY/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing/notebooks\x94ub.');from snakemake.logging import logger;from snakemake.iocontainers import Snakemake;import os; os.chdir(r'/gpfs3/well/kelleher/users/nrn539/sc2ts_revision/sc2ts-paper/arg_postprocessing');
######## snakemake preamble end #########

In [2]:
import tszip
import sc2ts.debug as sd
import pandas as pd

In [3]:
ts = tszip.load(snakemake.input[0])
ts

In [4]:
ti = sd.ArgInfo(ts, show_progress=False, pango_source="pango", scorpio_source="scorpio")
ti

In [5]:
dfr = ti.recombinants_summary(show_progress=False)

RE: 132996 interval right shifted from 22227 to 21765

RE: 242304 has more than two parents. Skipping.

RE: 376386 interval right shifted from 28255 to 28252

RE: 462264 interval_right >= interval_left; moving from 22027to 22026

RE: 465551 interval right shifted from 22030 to 22029

RE: 482339 interval_right >= interval_left; moving from 22027to 22026

RE: 513371 interval_right >= interval_left; moving from 22027to 22026

RE: 523544 interval right shifted from 22030 to 22029

RE: 557775 interval_right >= interval_left; moving from 22027to 22026

RE: 571196 interval right shifted from 25046 to 22194

RE: 604971 interval_right >= interval_left; moving from 22027to 22026

RE: 609408 interval right shifted from 22030 to 22029

RE: 609412 interval_right >= interval_left; moving from 22027to 22026

RE: 628327 interval_right >= interval_left; moving from 22027to 22026

RE: 655496 interval_right >= interval_left; moving from 22027to 22026

RE: 656259 interval_right >= interval_left; moving from 22027to 22026

RE: 698369 interval_right >= interval_left; moving from 22027to 22026

RE: 708342 interval right shifted from 22030 to 22029

RE: 708513 interval_right >= interval_left; moving from 22027to 22026

RE: 714033 interval right shifted from 22030 to 22029

RE: 723568 interval_right >= interval_left; moving from 22027to 22026

RE: 726225 interval right shifted from 22030 to 22029

RE: 730996 interval_right >= interval_left; moving from 22027to 22026

RE: 739359 interval_right >= interval_left; moving from 22027to 22026

RE: 742984 interval right shifted from 22030 to 22029

RE: 744633 interval_right >= interval_left; moving from 22027to 22026

RE: 749044 interval_right >= interval_left; moving from 22027to 22026

RE: 749081 interval_right >= interval_left; moving from 22027to 22026

RE: 752953 interval_right >= interval_left; moving from 22027to 22026

RE: 760292 interval right shifted from 22030 to 22029

RE: 760318 interval_right >= interval_left; moving from 22027to 22026

RE: 761049 interval_right >= interval_left; moving from 22027to 22026

RE: 764303 interval_right >= interval_left; moving from 22027to 22026

RE: 764342 interval_right >= interval_left; moving from 22027to 22026

RE: 769504 interval_right >= interval_left; moving from 22027to 22026

RE: 779240 interval right shifted from 22030 to 22029

RE: 779346 interval_right >= interval_left; moving from 22027to 22026

RE: 796983 interval_right >= interval_left; moving from 22027to 22026

RE: 820450 interval right shifted from 22030 to 22029

RE: 853410 interval_right >= interval_left; moving from 22027to 22026

RE: 853610 interval_right >= interval_left; moving from 22027to 22026

RE: 859209 interval_right >= interval_left; moving from 22027to 22026

RE: 859518 interval_right >= interval_left; moving from 22027to 22026

RE: 864843 interval_right >= interval_left; moving from 22027to 22026

RE: 865140 interval_right >= interval_left; moving from 22027to 22026

RE: 873875 interval_right >= interval_left; moving from 22027to 22026

RE: 927329 interval_right >= interval_left; moving from 22027to 22026

RE: 944728 interval_right >= interval_left; moving from 22027to 22026

RE: 951665 interval right shifted from 22030 to 22029

RE: 963588 interval_right >= interval_left; moving from 22027to 22026

RE: 963634 interval_right >= interval_left; moving from 22027to 22026

RE: 978056 interval_right >= interval_left; moving from 22027to 22026

RE: 1024266 interval_right >= interval_left; moving from 22027to 22026

RE: 1029198 interval_right >= interval_left; moving from 22027to 22026

RE: 1061131 interval right shifted from 22227 to 22194

RE: 1061131 interval_right >= interval_left; moving from 22196to 22193

RE: 1073548 interval right shifted from 11537 to 11283

RE: 1097925 interval right shifted from 22197 to 22194

RE: 1125891 interval right shifted from 22197 to 22194

RE: 1125893 interval right shifted from 22197 to 22194

RE: 1132034 interval right shifted from 7393 to 6513

RE: 1152112 interval right shifted from 22195 to 22029

RE: 1183000 interval right shifted from 22197 to 22194

RE: 1193652 interval right shifted from 22197 to 22194

RE: 1204439 interval right shifted from 22197 to 22194

RE: 1205084 interval right shifted from 22197 to 22194

RE: 1215374 interval right shifted from 22197 to 22194

RE: 1216129 interval right shifted from 22197 to 22194

RE: 1233218 interval right shifted from 22197 to 22194

RE: 1237075 interval right shifted from 22197 to 22194

RE: 1237768 interval right shifted from 11537 to 11283

RE: 1237915 interval right shifted from 22197 to 22195

RE: 1237915 interval_right >= interval_left; moving from 22196to 22194

RE: 1240516 interval right shifted from 22197 to 22194

RE: 1241565 interval right shifted from 22197 to 21766

RE: 1241565 interval_right >= interval_left; moving from 21767to 21765

RE: 1245760 interval right shifted from 22197 to 22194

RE: 1245878 interval right shifted from 22197 to 22194

RE: 1254667 interval right shifted from 22197 to 22194

RE: 1254677 interval right shifted from 22199 to 22194

RE: 1259930 interval right shifted from 22197 to 22194

RE: 1260176 interval right shifted from 22197 to 22194

RE: 1265102 interval right shifted from 22197 to 22194

RE: 1265146 interval right shifted from 22197 to 22194

RE: 1266053 interval right shifted from 22197 to 22194

RE: 1266053 interval_right >= interval_left; moving from 22195to 22193

RE: 1269356 interval right shifted from 22197 to 22194

RE: 1276732 interval right shifted from 22197 to 22194

RE: 1283655 interval_right >= interval_left; moving from 22197to 22196

RE: 1283712 interval right shifted from 22197 to 22194

RE: 1283721 interval right shifted from 22197 to 22194

RE: 1287538 interval right shifted from 22197 to 22194

RE: 1287910 interval right shifted from 22197 to 22194

RE: 1292091 interval right shifted from 22197 to 22194

RE: 1296589 interval right shifted from 22197 to 22194

RE: 1296634 interval right shifted from 22197 to 22194

RE: 1300117 interval right shifted from 22197 to 22194

RE: 1300122 interval right shifted from 22197 to 22194

RE: 1302519 interval right shifted from 22197 to 22194

RE: 1302780 interval right shifted from 22195 to 22194

RE: 1302782 interval right shifted from 22195 to 22194

RE: 1302784 interval right shifted from 22195 to 22194

RE: 1305036 interval right shifted from 22197 to 22194

RE: 1306793 interval right shifted from 22197 to 22194

RE: 1306799 interval right shifted from 22197 to 22194

RE: 1306874 interval right shifted from 22197 to 22194

RE: 1306988 interval right shifted from 22197 to 22194

RE: 1308780 interval right shifted from 8260 to 6513

RE: 1309791 interval right shifted from 22197 to 22194

RE: 1309793 interval right shifted from 22197 to 22194

RE: 1312702 interval right shifted from 22197 to 22194

RE: 1312720 interval right shifted from 22197 to 22194

RE: 1319252 interval_right >= interval_left; moving from 22197to 22196

RE: 1319285 interval right shifted from 22197 to 22194

RE: 1319404 interval right shifted from 22197 to 22194

RE: 1323050 interval right shifted from 22195 to 22194

RE: 1333059 interval right shifted from 22197 to 22194

RE: 1333471 interval right shifted from 22197 to 22194

RE: 1333527 interval right shifted from 22197 to 22194

RE: 1337052 interval right shifted from 22197 to 22194

RE: 1344200 interval right shifted from 22197 to 22194

RE: 1344305 interval right shifted from 22197 to 22194

RE: 1347812 interval right shifted from 22197 to 22194

RE: 1357217 interval right shifted from 22197 to 22194

RE: 1360646 interval right shifted from 22197 to 22194

RE: 1364157 interval right shifted from 22197 to 22194

RE: 1364246 interval right shifted from 22197 to 22194

RE: 1373820 interval right shifted from 22197 to 22194

RE: 1373836 interval right shifted from 22197 to 22194

RE: 1379291 interval right shifted from 22197 to 22194

RE: 1379624 interval right shifted from 11537 to 11283

RE: 1382790 interval right shifted from 22197 to 22194

RE: 1382942 interval right shifted from 22197 to 22194

RE: 1386220 interval right shifted from 22197 to 22194

RE: 1396656 interval right shifted from 22197 to 22194

RE: 1400001 interval right shifted from 22197 to 22194

RE: 1404812 interval right shifted from 22197 to 22194

RE: 1410398 interval right shifted from 22197 to 22194

RE: 1412008 interval right shifted from 22197 to 22194

RE: 1418614 interval right shifted from 22197 to 22194

RE: 1422927 interval right shifted from 22197 to 22194

RE: 1431253 interval right shifted from 9693 to 6513

RE: 1436962 interval right shifted from 22197 to 22194

RE: 1441940 interval right shifted from 22197 to 22194

RE: 1443769 interval right shifted from 22197 to 22194

RE: 1444447 interval right shifted from 11537 to 11283

RE: 1446711 interval right shifted from 22197 to 22194

RE: 1446971 interval right shifted from 11537 to 11283

RE: 1521441 interval right shifted from 22792 to 21765

RE: 1556477 interval right shifted from 22917 to 21765

RE: 1631461 interval right shifted from 22917 to 21765

RE: 1698566 interval right shifted from 22001 to 21765

RE: 1719442 interval right shifted from 21810 to 21765

RE: 1723586 has more than two parents. Skipping.

RE: 1727007 has more than two parents. Skipping.

RE: 1758224 interval right shifted from 22001 to 21765

RE: 1759556 interval right shifted from 22001 to 21765

RE: 1854739 has more than two parents. Skipping.

RE: 1873148 interval right shifted from 22295 to 22194

RE: 1876313 interval_right >= interval_left; moving from 21620to 21619

RE: 1884610 interval_right >= interval_left; moving from 21625to 21624

RE: 1888974 interval_right >= interval_left; moving from 21625to 21624

In [6]:
dfr

,sample_id,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,Viridian_amplicon_scheme,Artic_primer_version,date_added,...,oldest_child,oldest_child_pango,oldest_child_scorpio,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_pango,parent_mrca_scorpio,parent_mrca_time,parent_mrca_date
859,SRR19695004,1,1,1,519,670,2,COVID-AMPLISEQ-V1,.,2022-04-15,...,1438469,BA.2,Omicron (BA.2-like),783.0,2022-04-15,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
918,ERR9939974,1,1,1,695,958,1,COVID-ARTIC-V4.1,.,2022-06-27,...,1540082,BA.4.1,Omicron (BA.4-like),710.0,2022-06-27,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
401,SRR20259474,1,1,1,510,1222,1,COVID-AMPLISEQ-V1,.,2021-10-21,...,752954,AY.44,Delta (B.1.617.2-like),959.0,2021-10-21,167127,B.1.617.2,Delta (B.1.617.2-like),1268.244029,2020-12-16
1022,ERR10219711,2,1,1,695,1453,2,COVID-ARTIC-V4.1,.,2022-08-30,...,1639577,BA.4,Omicron (BA.4-like),646.0,2022-08-30,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
1174,ERR11184433,1,1,1,695,1545,2,COVID-ARTIC-V4.1,.,2023-03-20,...,1798211,DV.6,Omicron (BA.2-like),444.0,2023-03-20,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,ERR12781803,6,1,1,29509,29739,1,COVID-ARTIC-V3,.,2022-07-06,...,1556594,BA.5.2.1,Omicron (BA.5-like),701.0,2022-07-06,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
1144,ERR13040343,1,1,1,29509,29739,1,COVID-ARTIC-V3,.,2023-01-20,...,1750095,BQ.1.1,Omicron (BA.5-like),503.0,2023-01-20,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
1151,ERR13041473,2,1,1,29509,29739,2,COVID-ARTIC-V3,.,2023-01-30,...,1756386,EF.1,Omicron (BA.5-like),493.0,2023-01-30,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12
680,SRR25727637,1,1,1,29422,29751,1,COVID-MIDNIGHT-1200,.,2022-01-29,...,1179982,BA.1.17,Omicron (BA.1-like),859.0,2022-01-29,68,B.1,.,1591.661216,2020-01-28
1161,ERR11006399,1,1,1,28704,29754,3,COVID-ARTIC-V4.1,.,2023-02-16,...,1771515,FY.1,Omicron (XBB.1-like),476.0,2023-02-16,871728,B.1.1.529,Omicron (Unassigned),1333.857513,2020-10-12

In [7]:
dfr.describe()

,num_descendant_samples,num_samples,distinct_sample_pango,interval_left,interval_right,num_mutations,group_size,recombinant,recombinant_time,recombinant_date,...,parent_left_date,parent_right,parent_right_time,parent_right_date,oldest_child,oldest_child_time,oldest_child_date,parent_mrca,parent_mrca_time,parent_mrca_date
count,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1319.000000,1.319000e+03,1319.000000,1319,...,1319,1.319000e+03,1319.000000,1319,1.319000e+03,1319.000000,1319,1.319000e+03,1319.000000,1319
mean,463.618650,1.112964,1.000758,18621.645944,21004.300986,1.410917,2.127369,1.133191e+06,811.525331,2022-03-17 19:45:37,...,2022-02-03 22:08:38,9.648941e+05,892.606148,2021-12-26 13:59:32,1.143139e+06,796.225077,2022-04-01 19:11:46,6.673415e+05,1102.907760,2021-05-30 10:03:43
min,1.000000,1.000000,1.000000,223.000000,670.000000,0.000000,2.000000,1.894000e+03,31.263776,2020-03-18 00:00:00,...,2020-02-23 00:00:00,1.067000e+03,93.000000,2019-12-26 00:00:00,1.893000e+03,29.000000,2020-03-22 00:00:00,1.000000e+00,232.006024,2019-12-26 00:00:00
25%,1.000000,1.000000,1.000000,14821.000000,21610.000000,1.000000,2.000000,7.150795e+05,693.677937,2021-09-27 00:00:00,...,2021-08-22 00:00:00,4.111800e+05,759.000000,2021-06-29 00:00:00,7.204480e+05,680.000000,2021-10-12 00:00:00,1.671270e+05,961.384849,2020-12-16 00:00:00
50%,1.000000,1.000000,1.000000,21596.000000,22027.000000,1.000000,2.000000,1.132034e+06,879.676221,2022-01-09 00:00:00,...,2021-12-07 00:00:00,1.030941e+06,918.000000,2021-12-01 00:00:00,1.156864e+06,870.000000,2022-01-18 00:00:00,8.717140e+05,1268.244029,2020-12-16 00:00:00
75%,3.000000,1.000000,1.000000,22035.000000,24208.000000,2.000000,2.000000,1.608724e+06,983.086965,2022-07-13 12:00:00,...,2022-05-29 00:00:00,1.509098e+06,1073.000000,2022-05-09 00:00:00,1.616395e+06,968.000000,2022-07-27 00:00:00,8.717280e+05,1268.244029,2021-10-19 00:00:00
max,244601.000000,17.000000,2.000000,29701.000000,29754.000000,14.000000,21.000000,1.892436e+06,1541.000000,2024-05-06 00:00:00,...,2024-05-01 00:00:00,1.890523e+06,1624.000000,2024-03-05 00:00:00,3.407626e+06,1537.000000,2024-05-08 00:00:00,1.855174e+06,1624.000000,2023-10-28 00:00:00
std,9998.953042,0.789810,0.027535,6596.417104,5980.226962,1.160583,0.973317,5.023715e+05,260.610423,NaN,...,NaN,5.648088e+05,274.755649,NaN,5.129767e+05,260.990522,NaN,5.541644e+05,279.954745,NaN

In [8]:
dfr.to_csv(snakemake.output[0]);